### ISSUE TITLE
Created Dedicated Card Set Pages

### ISSUE THREAD

**Issue by AlanOC91** [AlanOC91/YGOPRODeck#108]
Instead of linking card sets to the advanced search page, we should also have dedicated card set pages.

These would be similar to the Card Information page where it's one template dynamically updated.

An example url structure would be: https://db.ygoprodeck.com/set/?search=Metal%20Raiders

Various information would be shown on this page:

- Set Release Date
- All Cards
- Card Breakdown

**Comment by AexDEye9** [comment]
merging my suggestion with the older thread, see #188

**Comment by AlanOC91** [comment]
Beginning work on this now

**Comment by AlanOC91** [comment]
Very early design example:

![Early](https://user-images.githubusercontent.com/37552458/93487996-c2647800-f8fd-11ea-86ce-6e54f38d9496.png)

**Comment by AexDEye9** [comment]
looking great so far! would like to see details & prices by hovering over cards 🤔

**Comment by AlanOC91** [comment]
- Refined code to dynamically create all rarity areas in an optimized fashion
- Added Lazy Loading of images

**Comment by AlanOC91** [comment]
- Added pack information (number of cards, release date).
- Added SEO information.
- Added Opengraph/Twitter information.

Twitter Card Example:
![Twitter](https://user-images.githubusercontent.com/37552458/93866270-5ac47900-fcbf-11ea-85f4-972fbdd339e2.png)

Open Graph Example:
![Open Graph](https://user-images.githubusercontent.com/37552458/93866324-67e16800-fcbf-11ea-8247-945e2162e624.png)

**Comment by AlanOC91** [comment]
First version pushed live.

Here is an example: [https://db.ygoprodeck.com/set/?search=Legendary%20Duelists%3A%20Rage%20of%20Ra](https://db.ygoprodeck.com/set/?search=Legendary%20Duelists%3A%20Rage%20of%20Ra)

![Rage of Ra](https://user-images.githubusercontent.com/37552458/94239443-b84c0600-ff09-11ea-88df-72781503b992.png)

Our [Sets page](https://db.ygoprodeck.com/sets/) has also been updated. The set links now directly link to the new styled pages.

**Comment by AlanOC91** [comment]
OCG Sets have now also been added: https://db.ygoprodeck.com/sets/

Closing for now as this first phase is complete.

**Comment by AlanOC91** [comment]
- Card names are now also printed under each card.

**Comment by AexDEye9** [comment]
Here's a suggestion:
Let each card set page use the correct alternate art images.
EG: Shonen jump vol 1 issue uses the moon art of blue-eyes.

and on how to handle sets with multiple arts... maybe there could be multiple entries, with what is considered the alternate art marked as so.
