### ISSUE TITLE
New API: return archetype master

### ISSUE THREAD

**Issue by Doarakko** [AlanOC91/YGOPRODeck#118]
Now it is difficult to know what kind of archetype is supported for your api.

I can know from here, but it is a little inconvenient for API user.
![](https://user-images.githubusercontent.com/21009186/69402548-842d1500-0d3b-11ea-919a-2e0f8234ee67.png)

I think if API user can get archetype master from API, it will be more convenient.

Although it is an aside, I developed some library and cli using your API.

- [go-yugioh](https://github.com/Doarakko/go-yugioh)
    - Go library for accessing the Yu-Gi-Oh! API by YGOPRODeck.
- [draw](https://github.com/Doarakko/draw)
    - Draw Yu-Gi-Oh! Card in command line.

Thanks for your great work!

**Comment by AlanOC91** [comment]
Hey there!
Thanks for the feedback on the API. I've added an endpoint that returns all the Archetypes we store. 

`https://db.ygoprodeck.com/api/v5/archetypes.php`

Documentation has also been updated:

https://db.ygoprodeck.com/api-guide/

Great job on the work you have done with the API! I love seeing it be put to good use!

**Comment by Doarakko** [comment]
I am surprised and appreciate at the quick response.
