### ISSUE TITLE
API: Find cards using set code

### ISSUE THREAD

**Issue by severinkaderli** [AlanOC91/YGOPRODeck#126]
I'm building a card collection tracker for myself and it would be great if it was possible to find cards using their set code. E.g. https://db.ygoprodeck.com/api/v5/cardinfo.php?set_code=SDY-046 would return the response for Man-Eater Bug.

**Comment by AlanOC91** [comment]
Shouldn't be too difficult for me to implement.

I'll try get a test version going in the morning!

**Comment by severinkaderli** [comment]
Are there any updates about this?

**Comment by AlanOC91** [comment]
Hey!

I've been investigating this the last few days and it seems too messy right now to implement into the `cardinfo` endpoint due to the way the data is set up in the back-end.

However, it shouldn't be much difficulty setting up a new endpoint for it.
What kind of information would you need returned?

All card information or something simple like only the card name which could then be passed into the `cardinfo` endpoint?

**Comment by severinkaderli** [comment]
Just the name should be enough I think.

**Comment by AlanOC91** [comment]
Have it completed and currently updating the API documentation.

Example: https://db.ygoprodeck.com/api/v5/cardsetsinfo.php?setcode=SDY-046

Response:

```
{
	"id": 9596126,
	"name": "Chaos Sorcerer",
	"set_name": "Dragons Collide Structure Deck",
	"set_code": "SDDC-EN014",
	"set_rarity": "Common",
	"set_price": "$1.69"
}
```

Let me know if you need anything else. Simply re-open this! Thanks.

**Comment by severinkaderli** [comment]
@AlanOC91 Thank for adding the endpoint, it seems to work as I need it. Just one thing I noticed. It seems the object keys are quoted twice:
![image](https://user-images.githubusercontent.com/3110114/72896099-3e7ecf80-3d1f-11ea-8f2b-e8ad050cd828.png)

**Comment by AlanOC91** [comment]
Should be fixed now!

**Comment by severinkaderli** [comment]
Thank you very much. Everything now seems to work except some set codes that don't seem to work / don't exist:

* Cards in the Spell Ruler set with code "SRL" can't be found only "MRL" works for them.
* Polymerization in the set "Fusion Enforcers" FUEN-EN049 and "Duelist Pack: Yugi" DPYG-EN020   is missing. Most likely because this is the alternative artwork of the card.
* Spiral Flame Strike from "Legendary Dragon Decks" LEDD-ENC16 is missing

**Comment by AlanOC91** [comment]
Hi!
I checked Spell Ruler and it seems to work fine for me. Can you give an example?
https://db.ygoprodeck.com/api/v5/cardsetsinfo.php?setcode=SRL-007
https://db.ygoprodeck.com/api/v5/cardsetsinfo.php?setcode=MRL-007

I've inserted the other missing entries you've listed. Thanks!

**Comment by severinkaderli** [comment]
Sorry, I had a problem in my code that's why they didn't work correctly.

But I found that the alternative Artwork Dark Magician from Yugi's Legendary Decks YGLD-ENB02 is not working. That's the last card in my collection that's not working.

Thanks a lot for your work on this!
