### ISSUE TITLE
Card Collection 

### ISSUE THREAD

**Issue by AlanOC91** [AlanOC91/YGOPRODeck#128]
Look into adding the functionality of card collection tracking.

This would allow users to create a custom list of cards they own in their collection.

Minimum required info:
- Card Name
- Card Set
- Card Rarity
- Card Set Code
- Card Edition
- Number in Collection

We'll also need a login system to keep the information stored. This is the bigger issue. The database db.ygoprodeck.com currently uses no login system. Ygoprodeck uses a login system and I could try cross sync them but this is messy. Will need to investigate. I already have an offline login system created for it but not implement or tested fully yet.

**Comment by AlanOC91** [comment]
Alpha Collection Tracking now in place.

What it does currently:

- Load WordPress Core for User Authentication
- Add/Remove Single Card to a Database and output Contents to User
- Show Card Image + Card Name (hyperlinked to DB)
- Early Design Complete

**Comment by AlanOC91** [comment]
- Overhauled Search API for the Card Collection.
- Shows total number of cards in collection.
- Allows user to change card condition.
- Modified UI/CSS.

**Comment by AlanOC91** [comment]
- Added Caching to Search Results

**Comment by AlanOC91** [comment]
- Delete Collection Completed
- Bulk Import Completed

**Comment by AlanOC91** [comment]
Current Bugs:

- Mobile needs more work.
- Pricing not fully sorted.
- Multiple Rarities of Cards with the same set code don't appear. For example Treeborn Frog from Shadow of Infinity.

**Comment by AlanOC91** [comment]
- Download Collection as CSV file complete.

**Comment by AlanOC91** [comment]
- Search/Filter Collection complete.

**Comment by AlanOC91** [comment]
- Price Collection from TCGplayer complete.
- Card Edition complete.

**Comment by AlanOC91** [comment]
- Updated Mobile CSS but still needs work.
- Success message on updating price.
- If a price is not shown for a card it now shows "N/A".
- Fixed a bug when adding Cards with special characters in their name.

**Comment by AlanOC91** [comment]
- Fixed issue where multiple Rarities of Cards with the same set code don't appear. For example Treeborn Frog from Shadow of Infinity.

**Comment by AlanOC91** [comment]
- Changed to load JS and CSS externally instead of inline.

**Comment by AlanOC91** [comment]
- Two page refreshes may sometimes be needed to show your full up to date collection. This is due to our service worker caching the old request and showing your collection in a previous state. An additional refresh solves this. We are currently working on this bug.

**Comment by AlanOC91** [comment]
- Open Beta Release

**Comment by AlanOC91** [comment]
Rework price check to match card set code instead of card set name. This is done due to difference in card set naming schemes from tcgplayer.

**Comment by AlanOC91** [comment]
- Reworked collection pricing to match by card set code (example MVP1-ENS47) instead of card set name. This bypasses the issue where tcgplayer was failing to get prices due to set name differences.

**Comment by AlanOC91** [comment]
- Look into disabling caching on JSON call when checking prices, otherwise price button will need to be hit twice.

**Comment by AlanOC91** [comment]
- Fixed a bug with special characters. See #157 
- Added code to stop the potential spam of the download collection button. It now operates the same as the button to price the collection. Once the user hits the button, the button is inaccessible until the request has completed.
- Added versioning to the js file.

**Comment by AlanOC91** [comment]
- Added button to bulk import a full card set. For example, you can bulk import all cards from "Ignition Assault".

**Comment by AlanOC91** [comment]
- Added `jQuery.ajaxSetup({ cache: false });` to the page which gets rid of the cache problem causes by `getJSON`

**Comment by AlanOC91** [comment]
TODO:

- Allow user to set default option when mass importing cards (card condition, card edition, etc).
- Allow import of CSV (in the same syntax as the CSV download). This will be tricky and will require a lot of error handling.
- TCGPlayer purchase fails when too many cards are added, look into that.

**Comment by AlanOC91** [comment]
- You can now choose a default card condition/card edition when using the 2 import buttons.
- Added some slight error checking to the original import button (the card set import already had this error checking).
- Added user avatar from WordPress and removed star icon.

**Comment by AlanOC91** [comment]
- Import from CSV is essentially done, just needs to some error checking and refining before making it public.

**Comment by AlanOC91** [comment]
Added a decent bit of error checking to the CSV Import.

- Checks if column count does not match what expected.
- Checks if Card Quantity contains non numeric characters.
- Checks if Card ID contains non numeric characters.
- Checks if Card Rarity, Card Condition and Card Edition contains only alphabetic characters.
- Checks if the Card Set Code is in valid format.

**Comment by AlanOC91** [comment]
- Error checking completed for the most part on CSV import.
- Added a "Loading Prices..." animated message when prices are loading (usually for large collections).
- Fixed an issue with CSV files where cards with double quotes in their name were causing issues.
- Added versioning to CSS file.

**Comment by AlanOC91** [comment]
- CSV Upload feature is now live.

**Comment by AlanOC91** [comment]
- Removed all brackets from card names from the Internal TCG Player Database. For example `Stardust Dragon (Ghost)` is now `Stardust Dragon`
- Removed all brackets incoming from the TCGPlayer API.
- Updated price checking to include Card Rarity which further narrows down correct card pricing.

**Comment by AlanOC91** [comment]
- TCGPlayer seem to have some card rarities listed incorrectly. For example [all these cards](https://www.tcgplayer.com/search/yugioh/power-of-chaos-joey-the-passion?productLineName=yugioh&setName=power-of-chaos-joey-the-passion) should be `Prismatic Secret` Rare but they are listed incorrectly. This is causing price match issues on our end. TCGPlayer have told me they are correcting the issue.

**Comment by AlanOC91** [comment]
- Added 3 sort buttons.

The 3 are: Sort by Name (A-Z), Sort by Rarity and Sort by Quantity.
I have an almost working sort by price but there is a few quirks with it.

![SearchCollection](https://user-images.githubusercontent.com/37552458/83877891-2f7b4580-a733-11ea-86bb-af0b582a4c28.png)

**Comment by AlanOC91** [comment]
- Sort by Price added.

**Comment by AlanOC91** [comment]
- Added validation so that sorting by prices can only be done after prices are loaded.

**Comment by AlanOC91** [comment]
- Added Sort by Card Set Name.
- Added Undo Sort button to go back to default sorting (replaced Sort by Name).

**Comment by AlanOC91** [comment]
- Added back pagination button when searching.

**Comment by AlanOC91** [comment]
- Updated Collection Manager message area when logged out.

![Logged Out](https://user-images.githubusercontent.com/37552458/84497550-e97c2f80-aca6-11ea-9b7c-54caeb0486d7.png)

**Comment by AlanOC91** [comment]
- Added "Default Card Condition" button so you can set a default card condition when adding cards.

**Comment by AlanOC91** [comment]
- Collection Search updated to pull directly from the TCGplayer database instead of the old weird hybrid mixture of both. This should prove for better updates going forward along with some more accurate data.

**Comment by AlanOC91** [comment]
- Adding a card of the same condition, rarity, edition and setcode will now simply increment the count x1 if it already exists. Previously it would append a new one but this was highly redundant.

This required a bit of a structural overhaul on the database as I needed to add a unique key to the database. Once this was done, I then needed to update each script with an `ON DUPLICATE KEY UPDATE` clause. I then needed to update the JavaScript code to handle incrementing the count if a card match the key already exists when inserting. 

Everything should be working with the exception of csv import. This is currently disabled as I need to re-write it now. 

This change was required (and a good change regardless) for syncing the Collection Manager.

**Comment by AlanOC91** [comment]
- Upload CSV button has been re-instated. CSV Uploader has been modified. It will now update rows that already exist (rather than always appending).

**Comment by AexDEye9** [comment]
i've wanted the ability to share your collection in-site/externally ever since the collection feature was added, when do you think this might be added?

**Comment by AlanOC91** [comment]
What kind of share options are you thinking of? We can currently export to PDF but I've been considering allowing you to share some form of URL link too.

**Comment by jermol123** [comment]
Hi! I was wondering if we could get "Price Collection from Cardmarket" option for Europe players in card collection section :) ?

**Comment by AlanOC91** [comment]
> Hi! I was wondering if we could get "Price Collection from Cardmarket" option for Europe players in card collection section :) ?

I can look into this for sure but our Cardmarket pricing is a little bit trickier since we don't have completely accurate pricing for 1st Edition/Unlimited. I'll check it out though!

**Comment by AlanOC91** [comment]
- Made searches case insensitive 
- You can now also search by card set code such as: YS18-EN008

**Comment by AlanOC91** [comment]
- Newly inserted cards are now added to the top of the list instead of the bottom

**Comment by AlanOC91** [comment]
We have some issues with performance when users have really large datasets. I've spent most of the morning trying to code an optimal code re-write solution but due to the nature of the collection system, none performed well.

The only option is to add some form of pagination to the user collection. This involves:

- Limit Results to 1000 per page.
- Add paging buttons.
- Enhance the getCollection API for Pagination.
- Update Search box to use getCollection API instead of using jQuery.
- Change sorting buttons to use getCollection API.

**Comment by AlanOC91** [comment]
While I am working on the above, I deployed a temporary work-around fix that optimizes loading of large data-sets in the collection manager. This is now live.

**Comment by SlaggyWolfie** [comment]
Would it be possible to export your entire collection through .ydk file or a way to convert the .csv collection to a .ydk? Granted I could do this myself, but my friends are not as tech-savvy. I'm mainly asking because it's already possible to download the drafts from the entire set as a .ydk. In this case, I understand that it might not be possible because only automatic simulators usually have the capability to display that many cards at a single time. I theorize it might become necessary to split up all the cards into multiple .ydk files.

Or alternatively, allow for the deck builder to only be able to access the collection for deckbuilding purposes. The reason I'm asking is for a progression series with my friends, for which I apologize that it's for such an activity, and I apologize for this sort of feature request. I understand it if it's not currently on the radar or unfeasible.

**Comment by AlanOC91** [comment]
> Would it be possible to export your entire collection through .ydk file or a way to convert the .csv collection to a .ydk? Granted I could do this myself, but my friends are not as tech-savvy. I'm mainly asking because it's already possible to download the drafts from the entire set as a .ydk. In this case, I understand that it might not be possible because only automatic simulators usually have the capability to display that many cards at a single time. I theorize it might become necessary to split up all the cards into multiple .ydk files.
> 
> Or alternatively, allow for the deck builder to only be able to access the collection for deckbuilding purposes. The reason I'm asking is for a progression series with my friends, for which I apologize that it's for such an activity, and I apologize for this sort of feature request. I understand it if it's not currently on the radar or unfeasible.

Howdy SlaggyWolfie.

Firstly, we are currently working on a format filter (such as TCG, OCG, etc) for "Card Collection" on the Deck Builder. This will basically allow you to query your Collection through the Deck Builder interface which will make building decks out of your Collection much easier!

This should solve your problem.

Alternatively in theory I could generate a .ydk file out of the collection. However many system do generally have limits on main deck size and so on.

**Comment by AlanOC91** [comment]
- Added a button to the Collection Manager to that opens the Collection in our Online Deck Builder.

**(this is not a replacement for our future plan of adding a "Collection" format to our online deck builder that will query your collection)**

**Comment by cmiley** [comment]
Would it be possible to add a way to select edition while adding a card? Sometimes its confusing when adding a card that has the same set code (that is already in your collection) but of a different edition. 

Ex. SDJ-001 1st Edition vs Unlimited

**Comment by AlanOC91** [comment]
> Would it be possible to add a way to select edition while adding a card? Sometimes its confusing when adding a card that has the same set code (that is already in your collection) but of a different edition.
> 
> Ex. SDJ-001 1st Edition vs Unlimited

I had planned on adding an general "Edition" drop-down similar to the one we currently have for "Condition". However this caused problems when attempting to add cards with editions that do not exist. I can try revisit and see if I can come up with a cleaner solution.

At the moment if you need to do this, change the general condition tab at the bottom of your collection to something else to add the card.

**Comment by AlanOC91** [comment]
- You can now link a search query via URL for the card collection. Example: https://db.ygoprodeck.com/collection/?search=Time%20Wizard
- The card information pages have been updated. Clicking "Save Card" now brings you to the collection page with the card search initiated.

**Comment by Cubikon** [comment]
>     * Added Sort by Card Set Name.
> 
>     * Added Undo Sort button to go back to default sorting (replaced Sort by Name).

Can you add a Sort by Set Number after the Set Name Sort? E.g LOB and then from Card 1 to 125 and Not Alphabetical

**Comment by IceshadeComets** [comment]
Would it be possible to change the amount of cards a Random Deck would generate? Because on default it seems it uses a set ratio and always gives 60 cards and 15 extra deck cards.

**Comment by AexDEye9** [comment]
Duelist League 1 European Promos do not exist within the card collection
Time Wizard (DL1-E001)
Barrel Dragon (DL1-E002)
if i find more, i'll edit this comment.

**Comment by AexDEye9** [comment]
When adding cards via the top searchbar, the total number of cards between pages (in brackets) adds 1 onto the end of the number, instead of adding 1 *to* the number, hillarious but a legit bug!
![image](https://user-images.githubusercontent.com/61853861/111893561-794fc680-89fb-11eb-95ec-fa9f9896767a.png)

**Comment by AexDEye9** [comment]
Followup on Kuwagata α: Pressing "Save Card" on it's card page leads to null.
![image](https://user-images.githubusercontent.com/61853861/111894056-7f47a680-89ff-11eb-935e-7bc5d9ac7dd3.png)

**Comment by AlanOC91** [comment]
> When adding cards via the top searchbar, the total number of cards between pages (in brackets) adds 1 onto the end of the number, instead of adding 1 _to_ the number, hillarious but a legit bug!
> ![image](https://user-images.githubusercontent.com/61853861/111893561-794fc680-89fb-11eb-95ec-fa9f9896767a.png)

This is fixed now!

Will look into missing cards. This seems to be a re-occuring issues due to the fact we are linking in with TCGplayer Data and they are sometimes excluding cards/using weird naming schemes causing table joins to fail.

Will also look into Kuwagata. I also hate that alpha symbol!

**Comment by AexDEye9** [comment]
> > When adding cards via the top searchbar, the total number of cards between pages (in brackets) adds 1 onto the end of the number, instead of adding 1 _to_ the number, hillarious but a legit bug!
> > ![image](https://user-images.githubusercontent.com/61853861/111893561-794fc680-89fb-11eb-95ec-fa9f9896767a.png)
> 
> This is fixed now!
> 
> Will look into missing cards. This seems to be a re-occuring issues due to the fact we are linking in with TCGplayer Data and they are sometimes excluding cards/using weird naming schemes causing table joins to fail.
> 
> Will also look into Kuwagata. I also hate that alpha symbol!

Thanks for the help!
i do wish some of yugioh's historical data was kept static and not fed off of some API... i only typed out all the missing cards currently available on my discord's progression series.

**Comment by zephyros-dev** [comment]
> > ```
> > * Added Sort by Card Set Name.
> > 
> > * Added Undo Sort button to go back to default sorting (replaced Sort by Name).
> > ```
> 
> Can you add a Sort by Set Number after the Set Name Sort? E.g LOB and then from Card 1 to 125 and Not Alphabetical

Would love to have this included also since I sorted my cards using Set Code
