### ISSUE TITLE
Race, Attribute and Type Endpoint

### ISSUE THREAD

**Issue by TomasGranda** [AlanOC91/YGOPRODeck#132]
I think a String Endpoint to validate all this hardcoded string will be good to keep maintainable the applications... You know what i mean?

**Comment by AlanOC91** [comment]
Hi there,

Could you expand on what you mean with a rough example?

**Comment by TomasGranda** [comment]
I mean an endpoint like Archetype endpoint.

`https://db.ygoprodeck.com/api/v5/archetypes.php`

An endpoint that respond with an array of valid strings.

Am i explaining me?

**Comment by AlanOC91** [comment]
Hi there,

The archetype endpoint you provide is intended to have no additional parameters/strings. It wouldn't make sense as it's entire purpose is to simply output a list of all archetypes. 

The reason being is that you can then use the card endpoint to know exactly what archetype you want to call (from the available list). Example:

https://db.ygoprodeck.com/api/v5/cardinfo.php?archetype=Blue-Eyes

Which can then be used in conjunction with other parameters:

https://db.ygoprodeck.com/api/v5/cardinfo.php?archetype=Blue-Eyes&attribute=DARK&type=Ritual%20Effect%20Monster

Hopefully I understood what you were trying to explain!

**Comment by TomasGranda** [comment]
I understand. Thanks for your time :D
