### ISSUE TITLE
[Question API v6] How to use misc param?

### ISSUE THREAD

**Issue by Doarakko** [AlanOC91/YGOPRODeck#138]
I tried bool and string, but does not work.

> The following endpoint parameters can be passed:
> ...
> - misc - Show additional response info (Card Views, Beta Name, etc.).

Please show me uri.

**Comment by AlanOC91** [comment]
Here is an example:

`https://db.ygoprodeck.com/api/v6/cardinfo.php?name=Tornado%20Dragon&misc=yes`

So it's: `&misc=yes`

I'll update the API docs to reflect this.

**Comment by Doarakko** [comment]
Tkanks!
