### ISSUE TITLE
Pack Opener - Deck Builder

### ISSUE THREAD

**Issue by AlanOC91** [AlanOC91/YGOPRODeck#141]
Add Deck Builder feature to the Pack Opener.

- Tick/Turn on Deck Builder Mode.
- When you open a pack, click a button near the cards to add all/specific card to the current deck being built.
- Have persistent information at the top of the screen about the current deck.

Persistent Deck Information:

- Number of Cards (card breakdown?)
- View Deck
- Download Deck (download .ydk)
- Delete Deck

**Comment by AlanOC91** [comment]
Beta version of this released for public use: https://db.ygoprodeck.com/pack-open/

Reddit writeup here: https://www.reddit.com/r/yugioh/comments/f5fxpe/yugioh_pack_opener_deck_builder_mode/

**Comment by AlanOC91** [comment]
- Add ,csv file export as a deck builder option.

Columns: ID, Name, Type

More columns can be added if necessary.

**Comment by AexDEye9** [comment]
[suggestion]

there are alot of other packs that have released over the years, including but not limited to the kaiba mega pack, the gold series, and dark beginnings/dark revelation series, and the star packs.

**Comment by AlanOC91** [comment]
- Star Packs added.

Looked into adding Dark Beginnings 1/2 but they are difficult to implement. According to the wiki:

> Dark Beginning (and all other Reprint Packs) always contain 6 Monster Cards, 3 Trap Cards, 3 Spell Cards, 1 Tip Card and 1 or even 2 rares.

This will be difficult to implement at the moment. Will look into adding other packs first.

**Comment by AexDEye9** [comment]
order of implementation isn't really important, as long as it is done in the end.
(tip card isn't counted)
