### ISSUE TITLE
TCG Release Date - Wrong on Some Cards

### ISSUE THREAD

**Issue by AlanOC91** [AlanOC91/YGOPRODeck#146]
For example, Starter Deck Kaiba Evolved cards have the initial release date from Starter Deck Kaiba.

One good example is [D. Tribe](https://db.ygoprodeck.com/card/?search=2833249) which has a date of 2002-03-29.

**Comment by AexDEye9** [comment]
**Full List of Incorrect Dates Between Starter Deck: Kaiba and Starter Deck: Kaiba Evolution:**

- D. Tribe
- Hyozanryu
- Opticlops
- Spirit Ryu
- Shadow Spell
- Riryoku Field
- Rush Recklessly
- Luster Dragon #2
- Premature Burial
- White Dragon Ritual
- Nobleman of Crossout
- Light of Intervention
- Paladin of White Dragon
I think that is all of them, but i am not 100% sure.

**Comment by AlanOC91** [comment]
Dates updated! Had to update pretty much every card you listed. 
However, not all dates are as early as Starter Deck: Kaiba Evolution.

For example: Paladin of White Dragon

It has a WorldWide TCG Date of: 2004-03-01 with Starter Deck Kaiba Evolution.

However it has a North America TCG Date of: 2003-10-10 with Magician's Force.

Since it's earliest TCG date is 2003-10-10, that's what I marked it as on the Database since out tcg_date is the **earliest** a card was made available. 

Thanks again for the list, it was super useful.

**Comment by AexDEye9** [comment]
Hmmm, seems like it's taking a while to take effect fully

i'll check back in 48 hours and prompt again if it's still not fixed

**Comment by AlanOC91** [comment]
Ah sorry I don't have the server side cache cleared. Will clear it all in a few mins.
