### ISSUE TITLE
Shonen Jump Vol. 1 Issue 1 promotional card missing in advanced., but visible on card page.

### ISSUE THREAD

**Issue by AexDEye9** [AlanOC91/YGOPRODeck#147]
https://imgur.com/a/KjPYBT4

**Comment by AlanOC91** [comment]
I've identified the issue with certain card sets being checked where they are returning 0 results.

This will be fixed but will be rolled into #144

**Comment by AexDEye9** [comment]
Issue Fixed, Closed.
