### ISSUE TITLE
all but 15 cards released in spell ruler have the wrong initial release date (2004-03-01 again)

### ISSUE THREAD

**Issue by AexDEye9** [AlanOC91/YGOPRODeck#148]
how to recreate:
use advanced search
set TCG release range around 16th september 2002
the 15 results that appear all seem to lack reprints.

**Comment by AlanOC91** [comment]
Will do a check on the full Spell Ruler set over the coming days. Thanks!

**Comment by AexDEye9** [comment]
looked into it more, and found some of the cards have the incorrect initial release date of 2004-10-12, dark beginnings 1, a reprint set with only 2 debut dards. that pack contains a total of 250 cards.

**Comment by AexDEye9** [comment]
Megamorph (ID: 22046459) Still has Release date of Starter Deck: Kaiba when it should be the release date of Spell Ruler.

**Comment by AlanOC91** [comment]
Updated Magic Ruler cards to "2002-09-16". Will take some time to update on cache
