### ISSUE TITLE
Some Database discrepencies

### ISSUE THREAD

**Issue by deathbymanga** [AlanOC91/YGOPRODeck#151]
Vision Fusion should be listed in the Vision HERO archetype list.

Predaplant Verte anaconda's effect is not correctly worded. Compare the wording on the [YGOpro Database](https://db.ygoprodeck.com/card/?search=Predaplant%20Verte%20Anaconda) vs the wording on the [Official Konami Card Database](https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=14944)

**Comment by AlanOC91** [comment]
I've just updated Vision Fusion now. It will take a while to reflect this on the site as I need to update the cache.

I also just updated over 1800 card descriptions and Predaplant Verte Anaconda was one of them! Thanks.
