### ISSUE TITLE
Allow searching for cards by ID

### ISSUE THREAD

**Issue by parasiteoflife** [AlanOC91/YGOPRODeck#154]
Currently there is no way to search for a card by its ID other than using the API.
Can you please add this to the website?

**Comment by AlanOC91** [comment]
Hey there, I've now added this to our advanced search page. If the card name input only detects numeric values, it will search by ID instead.

Example:
https://db.ygoprodeck.com/search/?&id=25833572&num=30&offset=0&view=Gallery

Our Card Info page also supports IDs:
https://db.ygoprodeck.com/card/?search=25833572

**Comment by parasiteoflife** [comment]
> Hey there, I've now added this to our advanced search page. If the card name input only detects numeric values, it will search by ID instead.
> 
> Example:
> https://db.ygoprodeck.com/search/?&id=25833572&num=30&offset=0&view=Gallery
> 
> Our Card Info page also supports IDs:
> https://db.ygoprodeck.com/card/?search=25833572

Thank you!
Great website btw.
