### ISSUE TITLE
Some Formats not showing in Misc Info

### ISSUE THREAD

**Issue by NoahReyson** [AlanOC91/YGOPRODeck#156]
Hi, and congratulations on your v6, I upgraded to it and have not encountered any issues yet.

However, I noticed a slight detail: in the documentation you specify that the possible returned formats are: "tcg", "ocg", "goat", "ocg_goat", "speed duel", "duel links" and "rush duel".
But in my few tests, I have never seen the mentions "tcg" and "ocg" even for obvious cards like Dark Magician or Blue-Eyes White Dragon.
Is it normal?

By the way, the Blue-Eyes White Dragon result also does not return the mentions Rush Duel and Duel Links, while I think it is present in both formats.

EDIT: 
I just realized that "misc_info" is an array containing only one object.
It is a little redundant as it is: either it is an array containing unnamed objects but in this case we lose the labels "tcg_date", "formats", etc. either it is a JSON object.
Unless there is a specific reason, I would recommend removing the array to return only a JSON object.

EDIT 2:
It seems impossible to use the parameter "misc=yes" with the global URL "https://db.ygoprodeck.com/api/v6/cardinfo.php" as "https://db.ygoprodeck.com/api/v6/cardinfo.php&misc=yes".

**Comment by AlanOC91** [comment]
Hi there! Thanks for using the API!

I can check this in more detail later once I get a bit of time but to quickly answer a couple of things:

- This is the correct syntax for all cards + misc: https://db.ygoprodeck.com/api/v6/cardinfo.php?misc=yes

- Blue-Eyes does not show rush duel as it's actually a separate card for DB purposes. I may change this later. Blue-Eyes White Dragon (Rush Duel) is the card.

- I recommend trying the currently undocumented v7 of the API. This is the API I'm currently migrating the whole DB site into (which currently use old internal APIs). It's mostly the same with lots of bug fixes (such as tcg, ocg formats) and slight data return changes. It's used on our advanced search page and our deck builder. Here is an example: https://db.ygoprodeck.com/api/v7/cardinfo.php?name=Time%20Wizard&misc=yes

- In v7, Rush Duel cards are hidden by default but `&format=all` shows them. Example: https://db.ygoprodeck.com/api/v7/cardinfo.php?name=1%20up&format=all

I do agree that misc_info should not be an array. However that will probably not be changed until a potential v8.

If you've anymore questions feel free to ask and I'll try answer later!
