### ISSUE TITLE
Incorrect card price on Amazon

### ISSUE THREAD

**Issue by PackSciences** [AlanOC91/YGOPRODeck#160]
It seems like certain cards like "Eldlich the Golden Lord" don't have the correct Amazon price attached to them.

Example:
Eldlich the Golden Lord is currently attached to Norito the Moral Leader (PGL3-EN074) - Premium Gold: Infinite Gold - 1st Edition - Gold Rare on Amazon!

I don't know if this issue is general, or only with this card.

**Comment by AlanOC91** [comment]
I'll have a look at this but in general the Amazon prices are a bit wonky thanks to the notoriously difficult Amazon API that doesn't do a great job in narrowing down card specific searches. This is why in general over the last few months we've slowly been pushing Amazon and eBay into lower priority prices and TCGPlayer, Cardmarket and CoolStuffInc into higher priority pricing.
