### ISSUE TITLE
Database auto-sorting

### ISSUE THREAD

**Issue by PackSciences** [AlanOC91/YGOPRODeck#162]
In the database tool, you can sort out cards based off multiple criterias and then you can either pick "Asc" for ascending, "Desc" for descending or "Auto" which I assume means automatic.

For the criteria "Newest" which would imply "the card that is the newest in the database", the "Auto" settings is set to "Asc" (meaning the oldest) and not to "Desc" (the newest); so it is counter-intuitive to select "Newest" and you automatically get the oldest.

Two possibilities to solve this issue exist: Either assign "Auto" to "Desc" for this case; or rename "Newest" to Oldest.

**Comment by AlanOC91** [comment]
Thanks for the suggestion! I agree. I have rolled out a fix for this where "auto" is assigned to "desc" when "Newest" is selected.

![sort order](https://user-images.githubusercontent.com/37552458/81070757-99f25900-8edb-11ea-822b-4d139f6d47c3.png)

You may need to refresh your web browser cache to immediately see the change.
