### ISSUE TITLE
Typo in the Syntax page.

### ISSUE THREAD

**Issue by PackSciences** [AlanOC91/YGOPRODeck#163]
"These rulings are combined from multiple rule categories: OCG Rulings, TCG Rulings, Q&A Rulings, Mentions in Other Cards **Rulgins** and so on." should be "These rulings are combined from multiple rule categories: OCG Rulings, TCG Rulings, Q&A Rulings, Mentions in Other Cards **Rulings** and so on."

**Comment by AlanOC91** [comment]
Good catch, fixed!
