### ISSUE TITLE
[suggestion] Combo tree

### ISSUE THREAD

**Issue by PackSciences** [AlanOC91/YGOPRODeck#164]
As Yu-Gi-Oh is quite a combo game, it is sometimes possible to have multiple targets for certain cards. When you read a decklist and you don't know the deck already, it is hard to guess what the best target for an effect is. Therefore, I suggest a tree-like horizontal diagram in which you can show the branching of cards and add texts on the branching. That way, it is easy to see the combo inherent to the deck. This tool would have one "diagram view" and hovering over the cards would display the effects.

![image](https://user-images.githubusercontent.com/10787214/81609997-15bb3c80-93d9-11ea-9291-8b097511bc91.png)

**Comment by AexDEye9** [comment]
this will probably never happen

**Comment by NaturalHarmonia** [comment]
> this will probably never happen

Why not? Why do you say that?
