### ISSUE TITLE
Homepage Re-design

### ISSUE THREAD

**Issue by AlanOC91** [AlanOC91/YGOPRODeck#166]
Going to do some further re-designs to the homepage. The first half of the page will probably be removed and I'll prioritize most popular decks of the week/month along with creating a similar section for articles to drive a few more viewers to the articles we are outputting.

The second half of the homepage will remain the same for now.

**Comment by AlanOC91** [comment]
- Removed large buttons on the homepage that were completely unnecessary as they simply replicated what was in the navigation bar. 
- Moved Most Popular Decks of the Week and Month to the top.
- Added Yugituber section and assigned Yugituber role to uploaders with over 5k YouTube subs. 

TODO: Expaned Yugituber section into a fully fledged page.

**Comment by AlanOC91** [comment]
- Added header notification banner that can be toggled for whenever we need to make site-wide announcements.

**Comment by AexDEye9** [comment]
could potentially close this issue, although im not too sure
