### ISSUE TITLE
Altergeist Fifinellag not listed as Tuner

### ISSUE THREAD

**Issue by aDudman** [AlanOC91/YGOPRODeck#170]
In the YGOPRODeck database, [Altergeist Fifinellag](https://db.ygoprodeck.com/card/?search=Altergeist%20Fifinellag) is not listed as a Tuner monster even though it should be. This issue also occurs through the API.

**Comment by AlanOC91** [comment]
Hey there, 

This is fixed now! Please give it ~30 minutes for cache to update.

Thanks!
