### ISSUE TITLE
Red-Eyes Black Dragon is misnamed in the DB. 

### ISSUE THREAD

**Issue by Jadehex** [AlanOC91/YGOPRODeck#171]
When you changed "Red-Eyes B. Dragon" to "Red Eyes Black Dragon" to accommodate the new name change, you guys forgot the hyphen (which is still there in the name changed card, it's archetypal text). It broke a couple things in our scripts because your name is wrong. It should be "Red-Eyes Black Dragon"

https://ygorganization.com/red-eyes-b-dragon-name-update/ Proof that the english name change keeps the hyphen.

Thanks in advance,
Cheers!

**Comment by AlanOC91** [comment]
Thanks for the report! My bad on that one. 

I have it fixed now. Please allow up to 20 minutes for the cache to update.
