### ISSUE TITLE
King fog, Larvas both Have wrong TCG initial release, Matching Master collection vol. 1 and Duelist league 6 participation card.

### ISSUE THREAD

**Issue by AexDEye9** [AlanOC91/YGOPRODeck#172]
![kingfogbroken1](https://user-images.githubusercontent.com/61853861/86810371-bbef8f80-c074-11ea-8d2b-cded54380d7e.png)

**Comment by AlanOC91** [comment]
This is fixed now, thanks for the report!

They have both been set to "2002-03-08" for TCG which is the North America release of [Legend of Blue Eyes White Dragon](https://yugipedia.com/wiki/King_Fog)
