### ISSUE TITLE
[suggestion] add the OCG sets

### ISSUE THREAD

**Issue by f-master** [AlanOC91/YGOPRODeck#174]
Adding the ocg sets for pack sim and card list.

**Comment by AexDEye9** [comment]
that's a monumental task to accomplish, and i doubt it will happen at all

**Comment by AlanOC91** [comment]
Yeah this is an exceptionally large task with little pay-off honestly. We currently don't store ANY OCG pack information in our databases. It's all TCG and there is already a massive amount of data to wrangle with the TCG along. 

I don't think we'll be adding OCG pack data any time in the near future. I'll never say never but it's unlikely as of right now.

**Comment by f-master** [comment]
would it be possible for me to take on the task?
