### ISSUE TITLE
Dragunity Knight - Luin is missing its "Tuner" Type

### ISSUE THREAD

**Issue by Jadehex** [AlanOC91/YGOPRODeck#175]
Title, Dragunity Knight - Luin is a Synchro Tuner but the DB only has its Synchro type. It's funny because it just got announced for Duel Links but some people thought it was more playable because the DB entry didnt say it was a tuner. Thanks in advance.

Cheers,

**Comment by AlanOC91** [comment]
Thanks for the report! This has been updated now.

Please give it an hour or so for caches to update on the database.
