### ISSUE TITLE
2 more cards have incorrect TCG release due to card set naming bug

### ISSUE THREAD

**Issue by AexDEye9** [AlanOC91/YGOPRODeck#176]
Incorrect date listed is 03/29/2002, yet again, the issue seems to be related to how the first starter decks had similar names to the "evolution" version of themselves, released at a later date.
- Rush Recklessly (Supposed to be 09/16/2002, Magic/Spell Ruler)
- Dust Tornado (Supposed to be 10/20/2002, Pharoh's Servant)

**Comment by AlanOC91** [comment]
Updated both Rush Recklessly and Dust Tornado. Cache will take a while to update.

**Comment by AexDEye9** [comment]
you weren't wrong when you said it would take a while to update, 12 hours have passed.

**Comment by AlanOC91** [comment]
I'm not going to manually clear the full API cache (which slows everything down) for 2 date release changes so I'm going to let it fully expire naturally.
