### ISSUE TITLE
Duplicate card images for Offerings to the Doomed

### ISSUE THREAD

**Issue by stephenlrandall** [AlanOC91/YGOPRODeck#177]
The card Offerings to the Doomed has the same art (JP) for both entries in the card images field. The international art (19230407) is missing, since that entry is currently using the JP art:

![](https://storage.googleapis.com/ygoprodeck.com/pics/19230407.jpg)

**Comment by AlanOC91** [comment]
Thanks for the report Stephen. I'll have this fixed in the morning.

**Comment by AlanOC91** [comment]
Updated!

![19230408](https://user-images.githubusercontent.com/37552458/87639348-08099680-c73d-11ea-8596-e9e52970529d.jpg)
