### ISSUE TITLE
Offerings to the Doomed Artwork Query

### ISSUE THREAD

**Issue by Jadehex** [AlanOC91/YGOPRODeck#178]
https://cdn.discordapp.com/attachments/416815782866190336/735354509189971988/unknown.png

Im unsure if this is on our end or your end, but it looks like Offerings to the Doomed isn't properly split off from its alternate art. 

For Reference the one with 19230408 Should be the Red Original TCG art from LON. Cheers!

**Comment by AlanOC91** [comment]
Hey mate,

I think the issue may be on your end?
https://ygoprodeck.com/pics/19230408.jpg

And from the API:
https://db.ygoprodeck.com/api/v7/cardinfo.php?name=Offerings%20to%20the%20Doomed

Breaking down into art:
19230408
![19230408](https://user-images.githubusercontent.com/37552458/88145052-c4f26c00-cbf1-11ea-855a-f69b51d7f6f1.jpg)

19230407
![19230407](https://user-images.githubusercontent.com/37552458/88145069-c7ed5c80-cbf1-11ea-8e5a-053f5d1352cb.jpg)

Maybe a caching issue on your end?

**Comment by Jadehex** [comment]
Ok we'll check it out, apparently someone brought it up previously and it has been since fixed, I think its just a caching issue now, cheers
