### ISSUE TITLE
[Suggestion] Skip to draft

### ISSUE THREAD

**Issue by f-master** [AlanOC91/YGOPRODeck#179]
I have a feeling there is a reason this is not on here.
But the ability to instantly open a whole set and skip to the full draft.
Is there already a console command for this?

**Comment by AlanOC91** [comment]
It does slightly defeat the purpose of opening packs that the simulator provides but options are always good. We current'y **don't** have this feature but I will think about it and potentially look into implementing it.

**Comment by f-master** [comment]
cool, I know it beats the purpose, but I love just opening sets to see what my collection could have been. Like your rarest card against mine. Open a 100 packs and have a rarest card gauntlet.

**Comment by NeosBestDeck** [comment]
I would really enjoy this feature. A lot of people are using Ygoprodeck for their own homebrewn progression/draft and I think this would be extremely useful for a lot of people (including me).

**Comment by AexDEye9** [comment]
I'm backing this suggestion, some draft servers (mainly progression series) require you to open s huge amount of packs to join midway, which takes a huge amount of time to go through

Adding a way to skip alot of that process will drastically decrease how much time it takes to get started

**Comment by AlanOC91** [comment]
https://github.com/AlanOC91/YGOPRODeck/issues/289#issuecomment-914230644
