### ISSUE TITLE
Set Opening Simulator

### ISSUE THREAD

**Issue by AexDEye9** [AlanOC91/YGOPRODeck#181]
Hey again, new idea.

There are many sets in the pack opening simulator that don't feel complete without:
1: Promotional cards (E.G: Mega Tins, And the new Legendary duellists season 1)
2: Special Edition Bonuses, which despite being discontinued, are a part of history nonetheless.

Sets like duel power or duel overload don't matter much as each have inapplicable or guaranteed promotional features,

**Comment by AlanOC91** [comment]
Closing this for now as I think this would require some over-investment for little return at the moment. Having to code in promo cards/special editions along with linking the sets to the original set (Ignition Assault with Ignition Assault: Special Edition for example) would require a huge amount of work for a feature I wouldn't be entirely excited about.

I may return to this in the future but closing for now.
