### ISSUE TITLE
What does this search request mean?

### ISSUE THREAD

**Issue by vogosvagen** [AlanOC91/YGOPRODeck#182]
https://db.ygoprodeck.com/api/v7/cardinfo.php?startdate=2013-08-30&enddate=2013-12-25

I'm trying to get all the cards released (original release) using the above request. Is the response just that, or will it return something that was printed before startdate and rereleased between startdate and enddate?

**Comment by AlanOC91** [comment]
What you have searched above is all cards released between 2013-08-30 and 2013-13-25.

So all cards on and in those release dates.

However what it checks is "initial release date". So only cards that have initially been released for the first time in those dates. Not ALL cards printed in those dates (that may have been printed at an earlier time also).
