### ISSUE TITLE
Kuwagata Alpha missing set data

### ISSUE THREAD

**Issue by AexDEye9** [AlanOC91/YGOPRODeck#183]
![image](https://user-images.githubusercontent.com/61853861/89170604-cc156480-d577-11ea-9cba-b1c88373f960.png)
Should be in tournament pack: 1st season

**Comment by AlanOC91** [comment]
Added set data for it now. It will take a while for server cache to update and show this.

**Comment by AexDEye9** [comment]
extra info, searching the name in the top bar autocompletes to "Kuwagata ?"

the reason that this issue happened was because of the alpha symbol, and there are still some lasting effects.
should probably make a separate issue about the top search bar not recognising unicode...

**Comment by AlanOC91** [comment]
Completed in #184
