### ISSUE TITLE
'Gashadokuro, the Skeletal Mayakashi' has the wrong ATK

### ISSUE THREAD

**Issue by RandomPl0x** [AlanOC91/YGOPRODeck#187]
In the database, the card "Gashadokuro, the Skeletal Mayakashi" has the **ATK** set to **3600** instead of **3300**.

Thanks and have a good day!

**Comment by AlanOC91** [comment]
Thanks for the report! This has been fixed now.

I will take some time to update the cache to reflect this change on the live database.
