### ISSUE TITLE
Suggestion: Pack Opening Simulator: Jump to Booster pack

### ISSUE THREAD

**Issue by AexDEye9** [AlanOC91/YGOPRODeck#189]
in a desktop or laptop environment, the pack series selection box has loads of empty space to the sides, which could be used.

so, i'd wish that the series selection box would be expanded to fit the size of the screen, or at least half of it.

**Comment by AlanOC91** [comment]
Made some slight tweaks and adjustments like giving it 3 columns instead of 2 now along with some sizing changes.

![Table of Contents](https://user-images.githubusercontent.com/37552458/92591245-711d0e80-f295-11ea-929f-a1f8c9a35f54.png)
