### ISSUE TITLE
Track No. Packs Opener per User

### ISSUE THREAD

**Issue by AlanOC91** [AlanOC91/YGOPRODeck#194]
Adding pack tracking for user accounts in the pack opening simulator. This will allow users to see how many packs they have opened and which pack they have opened the most for example.

**Comment by AexDEye9** [comment]
i'm all for this feature, even i haven't opened every pack on the site yet...

**Comment by AlanOC91** [comment]
This is now implemented with a Pack Stats page: https://db.ygoprodeck.com/pack-stats/

![Pack Stats Example](https://user-images.githubusercontent.com/37552458/92461432-2fbb2f00-f1c1-11ea-96cf-310449311993.png)

There is also a link to this from the pack opener page:

![Pack Stats](https://user-images.githubusercontent.com/37552458/92461448-32b61f80-f1c1-11ea-913a-00fc3a47cdbe.png)

This may be further enhanced in the future but for now info logging + viewing is available
