### ISSUE TITLE
Query cardinfo endpoint with language

### ISSUE THREAD

**Issue by BlackRose01** [AlanOC91/YGOPRODeck#195]
Hello,

I would like to query the cardinfo endpoint with the language parameter but I only get errors. I tried the following queries:

1. **`https://db.ygoprodeck.com/api/v7/cardinfo.php?fname=Red-Eyes%20Darkness%20Metal%20Dragon&language=de`** (works without language parameter)
`{"error":"No card matching your query was found in the database. Please see https:\/\/db.ygoprodeck.com\/api-guide\/ for syntax usage."}`
2. **`https://db.ygoprodeck.com/api/v7/cardinfo.php?language=de`**
`{"error":"No valid parameter set. This API accepts the following parameters: 'name', 'fname', 'desc', 'effect', 'sort', 'sortorder', 'num', 'offset', 'type', 'atk', 'def', 'level', 'race', 'attribute', 'set', 'rarity', 'archetype', 'set', 'banlist', 'link', 'scale', 'linkmarker', 'format', 'staple', 'misc', 'includeAliased', 'startdate', 'enddate', 'dateregion', 'startprice', 'endprice', 'num', 'offset'."}`

KR,
BlackRose01

**Comment by AlanOC91** [comment]
Hey there!

For **1**, you are passing an English name while calling the German language. You need to pass in the German name to get a result. However I think you raise a good point about possibly returning all translated names when passing the English language (#197).

https://db.ygoprodeck.com/api/v7/cardinfo.php?fname=Rot%C3%A4ugiger%20finsterer%20Metalldrache&language=de

For **2**, this was a bug! Thanks for catching it. It should work now! 

https://db.ygoprodeck.com/api/v7/cardinfo.php?language=de
