### ISSUE TITLE
Remove data node in cardinfo endpoint

### ISSUE THREAD

**Issue by BlackRose01** [AlanOC91/YGOPRODeck#200]
Please remove the data node in the endpoint.

Currently:
```json
{"data": [{CARDINFO}, {CARDINFO}] }
```

Preferable:
```json
[{CARDINFO}, {CARDINFO}]
```

Thank you in advance.

**Comment by AlanOC91** [comment]
This will not be removed on an API level. Especially when it's getting tens of thousands of hits per day.

You'll easily be able to accommodate this change yourself on your chosen programming language.
