### ISSUE TITLE
API Glitch: 4 cards changed to wrong TCG release date

### ISSUE THREAD

**Issue by AexDEye9** [AlanOC91/YGOPRODeck#201]
- Hane-Hane
- Mountain
- Skull Red Bird
- Uraby
Listed Release date:  2002-03-29
Official Release date: 2002-03-08
yet ANOTHER glitch in the system related to the yugi/kaiba starter decks,
there's alot more of these issues i still need to pinpoint, if there were a way to stop these bad release dates popping up, that'd be great.

**Comment by AlanOC91** [comment]
Updated and fixed
