### ISSUE TITLE
Searching the API for the set "Magic Ruler" returns 90 cards instead of 104

### ISSUE THREAD

**Issue by larikk** [AlanOC91/YGOPRODeck#205]
When I access [https://db.ygoprodeck.com/api/v7/cardinfo.php?cardset=Magic%20Ruler](https://db.ygoprodeck.com/api/v7/cardinfo.php?cardset=Magic%20Ruler) I get 90 cards back. The set however has 104 cards.

The missing cards seem to be:
MRL-001 Penguin Knight
MRL-007 Metal Fish
MRL-009 Queen Bird
MRL-011 Peacock
MRL-014 Fire Kraken
MRL-018 Ancient One of the Deep Forest
MRL-019 Dark Witch
MRL-021 Mechanical Snail
MRL-022 Giant Turtle Who Feeds on Flames
MRL-023 Liquid Beast
MRL-025 High Tide Gyojin
MRL-027 Whiptail Crow
MRL-030 Red Archery Girl
MRL-048 Giant Trunade

**Comment by AlanOC91** [comment]
This should be fixed now.

Please allow a few hours for cache to update.
