### ISSUE TITLE
API: Kuwagata α has no TP1 (NA version of Tournament Pack 1) listing in card_sets

### ISSUE THREAD

**Issue by larikk** [AlanOC91/YGOPRODeck#206]
This request includes two cards of Tournament Pack 1, the problematic card and another one from the same set: https://db.ygoprodeck.com/api/v7/cardinfo.php?id=60802233,95144193

Every card in this pack has the NA (TP1-) and EU (TP1-E) version in "card_sets" except Kuwagata α; there is only the EU (TP1-E) version listed.

I'm okay if this won't be fixed (the cards seems very irrelevant and I can just use the EU version) but I still wanted to notify you.

**Comment by AlanOC91** [comment]
This is now fixed. Will take time for cachings to update on the site.
