### ISSUE TITLE
API: War of the Giants: Round 2 is missing two cards

### ISSUE THREAD

**Issue by larikk** [AlanOC91/YGOPRODeck#207]
War of the Giants: Round 2 is missing two cards:
BP02-EN072 Machine Lord Ür (Common/Mosaic Rare)
BP02-EN084 Beast Machine King Barbaros Ür (Rare/Mosaic Rare)

Query with both of these cards: https://db.ygoprodeck.com/api/v7/cardinfo.php?id=96938777,19028307

**Comment by AlanOC91** [comment]
These are now inserted. Will take a couple hours for cachings to update.
