### ISSUE TITLE
Sea Monster of Theseus Not Listed as Tuner

### ISSUE THREAD

**Issue by Jadehex** [AlanOC91/YGOPRODeck#212]
https://db.ygoprodeck.com/card/?search=Sea%20Monster%20of%20Theseus

Again just a minor one as someone was trying to search for it using Tuner + Fusion and came up with nothing. 

Thanks in advance,
Cheers!

**Comment by AlanOC91** [comment]
We currently don't have a sub-typing of "Tuner" for fusion monsters. I can look into the possibility of adding this but it requires some structural re-writes in my back-end. 

Thanks for the report!
