### ISSUE TITLE
Malefic Red-Eyes Black Dragon Name Change

### ISSUE THREAD

**Issue by Jadehex** [AlanOC91/YGOPRODeck#213]
https://db.ygoprodeck.com/card/?search=Malefic%20Red-Eyes%20B.%20Dragon - 

Again just a minor one - our mismatch with how Malefic Red Eyes had it's named change with the vanilla - With the reprint of LD:S1 I think it's name got updated in the TCG. 

Thanks Again,
Cheers!

**Comment by AlanOC91** [comment]
Thanks for the report! Updated now.
