### ISSUE TITLE
Sharing Data of the Pack Opening Simulator [API Enhancement]

### ISSUE THREAD

**Issue by CAS-ual-TY** [AlanOC91/YGOPRODeck#215]
Hello,  
first of all: Your homepage is clear, structured and has easy colors and the API is well documented. So thank you for that.  

Now, to my question: You are providing pretty much every data there is (and we use it very well), except for one more thing that we would be very interested in: The set data, and I dont mean which cards _can_ be pulled, but rather: Which cards _are_ pulled. So an extension of the cards-per-set-list that includes how the cards are pulled and in what ratio.  
You have a Pack Opening Simulator and we would like to ask You if you could make the data behind it public in one form or another? If You are looking for a format to publish it on, we can draft one, if You would like.  
  
About us: We are currently reworking the Ygo Dueling Mod for Minecraft. We consist of a bunch of people, including a relatively large Q&A team, texture and model contributors, and a bunch of developers including me (lead dev) and a ygopro dev who is interested in contributing and automating our dueling system. The core plan is to add cards and sets for trading and an improved and more interactive version of a "free" dueling simulator (like dueling book). Here is a screenshot of the current milestone:  
![2020-10-30_11 16 22](https://user-images.githubusercontent.com/41904979/97700044-746d9300-1aab-11eb-8987-2e01df5266ff.png)
  
Really hoping to get into contact with you!
Cheers!

**Comment by AlanOC91** [comment]
I'll have to give this some thought before getting back to you.

**Comment by CAS-ual-TY** [comment]
Alright! To repeat myself: If You are looking for a format to publish it on, we can draft one, if You would like.  
We obviously have a lot of data ourselves and had to safe said data using the json format. The single format allows us to cover all different kinds of sets that exist, so "hardcoded" pulling (structure decks), random pulling (booster packs), sub sets (sets included in other sets), multiple card pools (battle packs) ...  
Also, this data is not available for programms to use anywhere, from what we have seen. And to give you some insight; We have some website scrapers which parse html and provide some inaccurate and unpredictable data, but generally all sets still requre manual work and review and the circumstances currently require us to host our own DB, which is not ideal.  
(make sure you also check out my response in #152 )

**Comment by AexDEye9** [comment]
oh damn i didnt expect this, big fan of your team's work, man!
set ratios would be a really neat feature, not just for your mod.

**Comment by AexDEye9** [comment]
found out today that the mod's now in public beta, well done to @CAS-ual-TY for all he's done!
can close this issue.

**Comment by CAS-ual-TY** [comment]
Thank you. But why can this issue be closed? We are still in need of the data.

**Comment by AexDEye9** [comment]
> Thank you. But why can this issue be closed? We are still in need of the data.

sorry, i didn't know that
