### ISSUE TITLE
Providing API Iteration/Minor-Version Number [Minor API Enhancement]

### ISSUE THREAD

**Issue by CAS-ual-TY** [AlanOC91/YGOPRODeck#216]
Add some sort of iteration number; eg. just an integer being incremented every time the DB changes. We cache all card results locally and it would be really useful to identify changes

- when new cards have been added
- when cards have been modified (eg. "infernity_hell_archfiend" had a null-entry in its "level" field and that was fixed someday recently)
- ...

In order to update the cached result. If there is already such a result then I am sorry, I was not able to find that in your docs.
Cheers!

**Comment by AlanOC91** [comment]
Good idea. I'll begin working on this.

**Comment by AlanOC91** [comment]
New API for version checking: https://db.ygoprodeck.com/api/v7/checkDBVer.php

This is not a cached endpoint and `database_version` and `date` are incremented when:

- New card is added to the database.
- Card information is updated/modified on the main database. 

Will update the API docs to show this.

**Comment by CAS-ual-TY** [comment]
Wow youre quick! One thing though: You dont have to increment the version when you add a card, but rather when you add card(s) (if you know what I mean, sure you do). Anyways, this is perfect, thank you!
