### ISSUE TITLE
Add OCG Set Information

### ISSUE THREAD

**Issue by AlanOC91** [AlanOC91/YGOPRODeck#217]
OCG set information is something that would be decently useful to the site.

I started work on this last week and have completed the following:

- OCG set information in our Database.
- OCG sets added to APIv7 using `cardsetocg`.
- Advanced Search page updated to accommodate OCG sets. Example: [https://db.ygoprodeck.com/search/?&cardsetocg=20th%20Anniversary%20Duelist%20Box&num=30&offset=0&view=List](https://db.ygoprodeck.com/search/?&cardsetocg=20th%20Anniversary%20Duelist%20Box&num=30&offset=0&view=List)
- Sets page updated to include a secondary OCG sets table: https://db.ygoprodeck.com/sets/
- Set information page updated to showcase OCG sets. Example: [https://db.ygoprodeck.com/set/?search=Collection%20Pack%202020&region=OCG](https://db.ygoprodeck.com/set/?search=Collection%20Pack%202020&region=OCG)

Potentially TODO:
- Show OCG set information on Card Detail pages?
- Look into OCG card pricing (unlikely to happen unfortunately)

**Comment by f-master** [comment]
Don't know how to describe how awesome it was to see the OCG Packs added, even the Vol.1-7 and Boosters, I demand a Progression series using these packs!

**Comment by AexDEye9** [comment]
Thought i'd put this issue in a comment instead of a post: 
(OCG) Starter Deck: Kaiba is missing Blue-Eyes Ultimate dragon, at least in card sets. (037 i think?)

**Comment by AlanOC91** [comment]
> Thought i'd put this issue in a comment instead of a post:
> (OCG) Starter Deck: Kaiba is missing Blue-Eyes Ultimate dragon, at least in card sets. (037 i think?)

Thanks! Fixed!

**Comment by f-master** [comment]
I spotted a mistake in the (OCG) Pharaoh's Inheritance: It has Fury of the Kairyu-Shin, believe it's supposed to be Dark Magic Attack instead

**Comment by AlanOC91** [comment]
Great catch.
This led me on a bit of an investigation and I discovered Fury of the Kairyu-Shin was inserted into many sets. This happened due to my script calling my API and passing a blank name (when it found a blank line) which for some reason ends up calling the Fury of the Kairyu-Shin card and using that ID and then inserting it as part of the set. I've removed all entries of this (except for Rise of the Duelist) and fixed the bug in the script.
I then discovered a further bug with cards that had `(card)` appended to their name. Such as `Labyrinth of nightmare (card)`. My script was supposed to find instances of this, remove `(card)` and insert the card but I made a mistake and it was instead deleting the name causing it to not be inserted. 
This has also been fixed! Thanks for spotting this! I'll have to re-run my script across most sets to make sure these issues are fixed across other OCG sets.

**Comment by f-master** [comment]
Glad to help, I enjoy looking through old sets so I will most likely spot things like this. You fix things very quickly.

**Comment by f-master** [comment]
I see that the first Starter Box is missing from the database

**Comment by AlanOC91** [comment]
> I see that the first Starter Box is missing from the database

Starter Box is now added!

https://db.ygoprodeck.com/set/?search=Starter%20Box&region=OCG

**Comment by f-master** [comment]
awesome!

**Comment by darellchua2** [comment]
Hi I have created a website that automatically collects OCG data and store it in my own CSV style database. 

You can see the results of the database through www.tekkx.com

I combined my own automation of OCG Cards price update from 2 known sites and listed card prices as my own to sell my second hand cards.

You noticed that all the images are pulled from a certain source.

Not sure would this help or not.
