### ISSUE TITLE
No Effect/Non-Effect Extra-Deck Monster Distinction

### ISSUE THREAD

**Issue by CAS-ual-TY** [AlanOC91/YGOPRODeck#218]
Hello again,  
so we have compared our cards data with yours and found absolutely no errors (...on your side; we found 2 typos on our side hehe) or differences, which is great.  
However, using your DB there is no way of being able to distinct between all Effect and Non-Effect Extra-Deck Monsters (eg. Fusion, Pendulum...).  
Why is this important? Eg. for the headline above the card text. Where it says eg. [ Dragon / Fusion / Effect ]  
Example cards for this: "Dragoness the Wicked Knight" vs. "Five-Headed Dragon".  
My suggestion for this would be to move the Effect classification from the Type value to an independent "has_effect" flag that is included for all monsters. This way you can also greatly simplify the amount of different Types.

**Comment by CAS-ual-TY** [comment]
Oh, if you need a list of extra deck monsters that have no effect, but can not be recognized as that, I uploaded it for you:  
https://pastebin.com/kE6pgKPb

**Comment by AlanOC91** [comment]
Good idea. Implemented.

Using `&misc=yes` will show the value in the `misc_info` response section.

![misc](https://user-images.githubusercontent.com/37552458/98253014-75eaff80-1f72-11eb-88b8-467b7f221eec.png)

You can also specifically call it to check:

https://db.ygoprodeck.com/api/v7/cardinfo.php?has_effect=true
https://db.ygoprodeck.com/api/v7/cardinfo.php?has_effect=false

You can pass the following to `has_effect`: true, 1, false, 0.

You can also obviously use this with other parameters:

https://db.ygoprodeck.com/api/v7/cardinfo.php?type=Link%20Monster&has_effect=false

Will update API documentation to reflect this.
