### ISSUE TITLE
Add search by set code and release date

### ISSUE THREAD

**Issue by Teferi92** [AlanOC91/YGOPRODeck#222]
I've been scouring the API docs for a way to do this and so far, I've failed.

I'm working on a project that will use the API a lot, but there's some functionalities I cannot implement if I can't search cards by the set code (i.e. MRD) or by release date (i.e. "released earlier than 2005-04-01".)

I really don't want to have to download the whole card database and I'd rather use the API. Is this something that can be implemented?

**Comment by AlanOC91** [comment]
This is actually implemented but not documented I believe.

Give me a couple hours to get home to my PC and I'll update you + update the API docs.

**Comment by AlanOC91** [comment]
Apologies for the delay.

Searching by release dates you must use `&startdate` and `&enddate `parameters along with `&dateregion`.

Start Date: Start date you want to query.
End Date: End date you want to query.
Date Region: TCG or OCG release dates.

Example: https://db.ygoprodeck.com/api/v7/cardinfo.php?&startdate=Sat%20Jan%2001%202000&enddate=Fri%20Aug%2023%202002&dateregion=tcg_date&num=30&offset=0

Get all TCG cards release between Jan 01 2000 and August 23rd 2002. 

What you pass to `startdate` and `enddate` can be slightly varied as our API picks up different formats and converts it regardless. For example:

Sat Jan 01 2002
Fri Aug 23 2002
Jan 01 2002
Aug 23 2002
01/01/2000
08/23/2002

Card Set Codes can be queried on our `cardsetsinfo` endpoint.

For example: https://db.ygoprodeck.com/api/v7/cardsetsinfo.php?setcode=SDY-046

**Comment by Teferi92** [comment]
Thanks for the reply! The startdate, enddate and dateregion parameters are super useful.

However, I have an issue with the cardsetsinfo endpoint. Querying for a single card is supported (and appreciated!) but I would like to query for an entire set, since the alternative is to query for every card in a set individually and that would undoubtedly strain the server.

**Comment by AlanOC91** [comment]
I can potentially cobble something together but if you are searching full sets do you need to use card set codes?
You could just use the set name, as an example:

https://db.ygoprodeck.com/api/v7/cardinfo.php?cardset=metal%20raiders
