### ISSUE TITLE
7 Colored Fish || Faulty Set Entries

### ISSUE THREAD

**Issue by CAS-ual-TY** [AlanOC91/YGOPRODeck#224]
7 Colored Fish lists Metal Raiders 3 times in their card_sets array with 3 different set codes (2 of them being faulty ofc). I havent checked for other Metal Raiders cards.

**Comment by AlanOC91** [comment]
MRD-EN = English Release
MRD- = North American English Release
MRD-E = European English Release

This is how the old Yu-Gi-Oh! Sets worked with English Releases. I will look into potentially filtering them but they are **not faulty or incorrect.**

**Comment by CAS-ual-TY** [comment]
I just found out about that. Idk if you should filter them out. Technically, they are correct, but listing all english releases seems overkill, too. Your judgment here. Can close.

**Comment by AlanOC91** [comment]
> I just found out about that. Idk if you should filter them out. Technically, they are correct, but listing all english releases seems overkill, too. Your judgment here. Can close.

Yeah I agree that it's potentially overkill.
A strange scenario because users don't necessarily need to know about the various English releases despite it being technically correct information. I'll ponder on it for a little bit.

**Comment by CAS-ual-TY** [comment]
Yep, you nailed it. Same with dark crisis. Unless the sets differ, then its another point to take into account.

**Comment by AlanOC91** [comment]
Taken over in #229
