### ISSUE TITLE
Archfiend Soldier || Listed twice in Dark Crisis

### ISSUE THREAD

**Issue by CAS-ual-TY** [AlanOC91/YGOPRODeck#225]
Archfiend Soldier contains the card_sets entry for Dark Crisis twice. Once for the English region (DCR-EN001), once for the North American English region (DCR-001). I dont know if this is on purpose. I thought I would let you know. This seems more like Konami made a mistake here to make us all suffer and implement exceptions for Dark Crisis.

**Comment by CAS-ual-TY** [comment]
Just re-read the wiki. I think you did it on purpose, but just wanna make sure

**Comment by AlanOC91** [comment]
Taken over in #229
