### ISSUE TITLE
Yubel - Terror Incarnate || Listed in Ra Yellow Mega Pack - EN and IT

### ISSUE THREAD

**Issue by CAS-ual-TY** [AlanOC91/YGOPRODeck#226]
This card lists both the EN and IT version of the Ra Yellow Mega Pack despite both language versions being exactly the same in this case.

**Comment by AlanOC91** [comment]
Thanks! This must have been a mistake by Yu-Gi-Oh! prices API that got pulled into our DB. It was the only instance of IT set code in the database.

I've removed it and will updated the cache.
