### ISSUE TITLE
Mokey Mokey King || Faulty Set Entry

### ISSUE THREAD

**Issue by CAS-ual-TY** [AlanOC91/YGOPRODeck#227]
This card lists the set Dark Revelation Volume 3 twice (same set codes), with one of the listing having C as set rarity (not the rarity code!) and emptry strings as set rarity code.

**Comment by AlanOC91** [comment]
Fixed! This card was the only instance where it had a rarity of "C" instead of "Common".

These entries have been removed from the DB now.
