### ISSUE TITLE
Mezuki || Wrong rarity: Duel Terminal Normal ~Rare~ Parallel Rare

### ISSUE THREAD

**Issue by CAS-ual-TY** [AlanOC91/YGOPRODeck#228]
This card lists "Duel Terminal Normal Rare Parallel Rare" as one of the rarities, but it must be renamed to "Duel Terminal Normal Parallel Rare" (first "Rare" removed)

**Comment by CAS-ual-TY** [comment]
Blue-Eyes White Dragon also contains a wrong Duel Terminal entry: Both "Duel Terminal Normal Parallel" and "Duel Terminal Normal Parallel Rare" are listed (first one missing "Rare").

**Comment by CAS-ual-TY** [comment]
Ally of Justice Clausolas also lists both "Duel Terminal Normal Parallel" and "Duel Terminal Normal Parallel Rare"

**Comment by AlanOC91** [comment]
All of these have now been fixed in the Database. Cache updates will soon follow.
