### ISSUE TITLE
[Suggestion] Add "getSetCards" method on the API

### ISSUE THREAD

**Issue by NeleB54Gold** [AlanOC91/YGOPRODeck#230]
Add getSetCards method to get all cards of a specific set

**Comment by AlanOC91** [comment]
Hi there!

Have you read our API docs? I believe we already have what you are looking for. For example, get all cards from Metal Raiders:
https://db.ygoprodeck.com/api/v7/cardinfo.php?cardset=Metal%20Raiders

**Comment by NeleB54Gold** [comment]
> Hi there!
> 
> Have you read our API docs? I believe we already have what you are looking for. For example, get all cards from Metal Raiders:
> https://db.ygoprodeck.com/api/v7/cardinfo.php?cardset=Metal%20Raiders

Oh sorry, thank you.
