### ISSUE TITLE
Add the images support for collection and regions

### ISSUE THREAD

**Issue by NeleB54Gold** [AlanOC91/YGOPRODeck#231]
You can add the support for multi images in the API for cards with something like this:
`{
 "images": {
  "SP15-EN036": "url for this set",
  "NECH-EN053": "url for this other set"
 }
}`

Maybe there are no images for all sets, in which case the image becomes optional...
If there is a way to help you, I'm ready!

**Comment by AlanOC91** [comment]
Hi there,

We have no plans to add either multi-language card images or multi-setcode card images at this time. The benefits for me to do so are very very minimal and the workload required to do so is extraordinarily high.
