### ISSUE TITLE
Booster Packs missing cards and typos in set entries

### ISSUE THREAD

**Issue by CAS-ual-TY** [AlanOC91/YGOPRODeck#236]
Hello! I parsed all the set entries in every card, prioritizing Worldwide > NA > EU (the most left one is always parsed if available, the others are ignored). I found some things which I believe are errors. I have gone through everything, comparing it to Yugipedia. I listed everything here for you to verify:  
  
Missing Entries:  
"Falchionβ" needs an entry for "Ancient Prophecy"  
"Beast Machine King Barbaros Ür" needs an entry for "Ancient Prophecy"  
"Chirubimé, Princess of Autumn Leaves" ... "2014 Mega-Tin Mega Pack"  
"Polymerization" ... "Duelist Pack: Yugi"  
"Damage Vaccine Ω MAX" ... "Generation Force"  
"Number F0: Utopic Future Slash" ... "Battles of Legend: Armageddon"  
"Chirubimé, Princess of Autumn Leaves" ... "Legacy of the Valiant"  
"Machine Lord Ür" ... "Crossroads of Chaos"  
"Polymerization" ... "Fusion Enforcers"
  
Wrong (?) Entries:  
"Spell Power Grasp" has the correct entry, as well as a wrong entry (so 1 correct entry, 1 false entry) for "Speed Duel: Scars of Battle": "S**D**SC-EN004" listed as set_code in the false entry  
"Karakuri Trick House" ist listed in "Storm of Ragnarok" instead of "Starstrike Blast" in the set_name (the set_code is correct)  
"Tuner's Scheme" has the wrong set_code number: Needs to be "ABPF-EN077" instead of "ABPF-EN074"  
"Ninjitsu Art Notebook" has the wrong set_code number: Needs to be "OP08-EN023" instead of "OP08-EN022"  
  
Cheers!

**Comment by CAS-ual-TY** [comment]
To clarify: I have only gone through sets that are listed on Yugipedia as booster packs! The query I used ( on https://yugipedia.com/index.php?title=Special:Ask&#search ):  
  
Condition:  
[[Category:TCG sets]] [[Category:Booster Packs]]  

Printout Selection:  
?English (EN) release date  
?English (NA) release date  
?English (E) release date  
?Set type

**Comment by AlanOC91** [comment]
Thanks for these! Interestingly enough some of the instances of wrong set-codes were also reflected on Yugipedia on the card page itself (https://yugipedia.com/wiki/Ninjitsu_Art_Notebook).

I've fixed these up now and cleared the cache for the API.

Thanks!

**Comment by CAS-ual-TY** [comment]
Nice!  
I have rerun the script, I only get 1 error which you might have overseen:  
"Spell Power Grasp" still has 2 entries for "Speed Duel: Scars of Battle":  
- "S**B**SC-EN004" (correct entry)  
- "S**D**SC-EN004" (wrong entry)  
Cheers!

**Comment by AlanOC91** [comment]
Thanks! This should also be fixed now!
