### ISSUE TITLE
Question about Set Release Dates

### ISSUE THREAD

**Issue by CAS-ual-TY** [AlanOC91/YGOPRODeck#239]
in cardsets.php you show the release dates.  
- Are those always TCG?  
- How are they chosen if EU/NA/World are different?  
- Always the earliest?  Or always eg. NA prioritized?  

I hope its clear what I am trying to ask. Thanks!

**Comment by AlanOC91** [comment]
Hey there.

To get these I originally ran a script that checked them against Yugipedia. These dates are to signify the earliest release of the card (regardless of set). So the earliest availability of the card.

It may not be fully accurate but the script did compare dates and try to pull the earliest found.

**Comment by CAS-ual-TY** [comment]
Wow, youre quick. Always the TCG earliest of all regions, or only the english regions? Sometimes they are released first in eg. Germany.

**Comment by AlanOC91** [comment]
Hmm I'd have to re-check the script but off the top of my head I think it's the earliest of the English Regions.

**Comment by AlanOC91** [comment]
I completely misinterpreted this initially. I thought you were asking about the release dates we have on the cards themselves (Dark Magician, Time Wizard, etc etc).

The release dates in cardsets is the earliest **ENGLISH** release date for that set. Automatically pulled using a script. The data should be relatively accurate.
