### ISSUE TITLE
"Alternate Rare" and "Unknown Rarity"

### ISSUE THREAD

**Issue by CAS-ual-TY** [AlanOC91/YGOPRODeck#240]
So question about these two:  

"Alternate Rare":  
So according to Yugipedia, "Alternate Rare" has officially been confirmed to be "Starlight Rare". Do you purposely keep the "Alternate Rare" label in eg. Chaos Impact?  

"Unknown Rarity":  
Can you share more info on this rarity? A lot of sets share both of them on different cards, are they both meant to be the rarity, that wasnt officially labeled back in the day (and is now consideres "Starlight Rare" as mentioned already)?  

Thanks!

**Comment by AlanOC91** [comment]
I've fixed these up and removed the entries.

The "Unknown Rarity" is pulled from the Yugioh Prices API when they get card information early and don't have the rarity. There was ~11 instances of this. They were safely removed as the proper rarities were already inserted. Same applied to Alternate Rare.
