### ISSUE TITLE
Pack opening pull rates

### ISSUE THREAD

**Issue by forsetite** [AlanOC91/YGOPRODeck#241]
I was testing pack pulls for tournament pack 7 and I pulled 3 ultra rares in a row when the odds for pulling an ultra rare from tournament pack 7 are 1 in 108 - making those pulls statistically impossible (I did about 200 pack pulls for tp7 and got 30 ultras) unless the pack opening script is following different odds

Anyway - was wondering what the pull odds are for each rarity across the website as I've had some bizarre results in the past as well testing pulls - alternatively how does the script determine what rarity and cards are pulled exactly?

**Comment by CAS-ual-TY** [comment]
Do you have a source for the 1-in-108 pull rates? Just out of curiosity

**Comment by forsetite** [comment]
It says on the back of packs due to regulation requirements - but also these pojo threads

https://www.pojo.biz/board/showthread.php?t=371876

https://www.pojo.biz/board/showthread.php?t=109424

**Comment by AlanOC91** [comment]
The odds were indeed a little high for the Ultra Rares. I have dropped them significantly and made them harder to pull. It should be roughly equivalent now.

**Comment by forsetite** [comment]
It's still unrealistically high? I did more test pulls - can you make the pull ratios publicly available?
