### ISSUE TITLE
Card Set Information - Card Image Variants dont work (?)

### ISSUE THREAD

**Issue by CAS-ual-TY** [AlanOC91/YGOPRODeck#242]
Hello,  
I have manually checked some card image variants in sets to see how it works. For this I used the Blue-Eyes White Dragon. I have found an issue I believe. If I look up any entries for that (eg. LOB-001, MAGO-EN001 or YAP1-EN001) they all list the latest card art ID (eg. LOB lists 89631146 as ID, but should be 89631139).  
Are there any issues with that, or do I just interpret this wrongly?  
Thanks

**Comment by AlanOC91** [comment]
We don't correlate card art variants with specific sets. You won't be able to get that with this API.

We have no immediate plans to change this in the near future.
