### ISSUE TITLE
Missing german translations in database

### ISSUE THREAD

**Issue by uberhalit** [AlanOC91/YGOPRODeck#243]
Hello, 
following is a list of all GX era cards that are currently lacking german translations. List has been created automatically by comparing JSONs.

Card ID | Card Name
------------ | -------------
11714098	|	30,000-Year White Turtle
68170903	|	A Feint Plan
40387124	|	Abyss Flower
25345186	|	After The Struggle
36904469	|	Akihiron
99785935	|	Alpha the Magnet Warrior
40173854	|	Amphibious Bugroth
31557782	|	Ancient Gear
81492226	|	Ancient Jar
36821538	|	Ancient Sorcerer
86421986	|	Ancient Tree of Enlightenment
86164529	|	Aqua Dragon
12436646	|	Aqua Snake
14708569	|	Arlownay
89832901	|	B. Dragon Jungle King
14148099	|	B.E.S. Big Core
15317640	|	B.E.S. Covered Core
22790789	|	B.E.S. Crystal Core
44954628	|	B.E.S. Tetran
72076281	|	Bat
19028307	|	Beast Machine King Barbaros Ur
29616941	|	Beautiful Beast Trainer
39256679	|	Beta the Magnet Warrior
8058240	|	Binding Chain
7670542	|	Bio Plant
21239280	|	Bone Mouse
68963107	|	Boo Koo
501000006	|	Chimaera, the Master of Beasts
75109441	|	Cobraman Sakuzy
38289717	|	Crawling Dragon #2
77998771	|	Crow Goblin
10789972	|	Cu Chulainn the Awakened
81057959	|	D. Human
2833249	|	D. Tribe
9910360	|	D.3.S. Frog
70074904	|	D.D. Assailant
60912752	|	D.D. Borderline
48148828	|	D.D. Crazy Beast
24508238	|	D.D. Crow
33423043	|	D.D. Designator
8628798	|	D.D. Dynamite
52702748	|	D.D. Guide
3773196	|	D.D. Scout Plane
48092532	|	D.D. Survivor
86498013	|	D.D. Trainer
5606466	|	D.D. Trap Hole
37043180	|	D.D. Warrior
7572887	|	D.D. Warrior Lady
82112775	|	D.D.M. - Different Dimension Master
9622164	|	D.D.R. - Different Dimension Reincarnation
59983499	|	Dancing Elf
40196604	|	Dark Shade
5388481	|	Darkfire Soldier #0
78861134	|	Darkfire Soldier #2
96967123	|	Dharma Cannon
69893315	|	Dice Armadillo
97843505	|	Djinn the Watcher of the Wind
25882881	|	Dokuroizo the Grim Reaper
97973387	|	Droll Bird
6367785	|	Eldeen
64154377	|	Embryonic Beast
501000007	|	Emperor of Lightning
11250655	|	Emperor of the Land and Sea
81563416	|	Fairy of the Fountain
37160778	|	Fairywitch
68870276	|	Fiend Reflection #1
2863439	|	Fiend Reflection #1
82556058	|	Fiendish Engine Omega
84834865	|	Flying Kamakiri #1
3134241	|	Flying Kamakiri #1
53830602	|	Fungi of the Musk
11549357	|	Gamma the Magnet Warrior
34536276	|	Ganigumo
69780745	|	Garvas
49370026	|	Genin
111000561	|	Get Your Game On!
95265975	|	Ghoul with an Appetite
41403766	|	Giant Scorpion of the Tundra
98299011	|	Gift of the Mystical Elf
51828629	|	Giltia the D. Knight
7526150	|	Golgoil
11793047	|	Gorgon Egg
27094595	|	Graveyard and the Hand of Invitation
15042735	|	Hurricail
38982356	|	Hyo
20848593	|	Ice Water
81686058	|	Ill Witch
32809211	|	Jinzo #7
55948544	|	Judgment of the Pharaoh
94566432	|	Kaiser Dragon
84103702	|	Kanikabuto
48109103	|	Kappa Avenger
81179446	|	Kattapillar
20541432	|	Key Mace #2
501000002	|	King of Destruction - Xexex
32569498	|	Korogashi
66526672	|	Labyrinth of Nightmare
9430387	|	LaLa Li-Oon
75850803	|	LaMoon
42591472	|	Laughing Flower
4392470	|	Leo Wizard
90500169	|	Level Down!?
55210709	|	Lisark
34320307	|	Living Vase
81618817	|	Lord of Zemia
3985011	|	Lucky Trinket
62210247	|	Lunar Queen Elzaim
17658803	|	Luster Dragon #2
98795934	|	Mabarrel
38116136	|	Machine Attacker
43905751	|	Madjinn Gunn
79629370	|	Maiden of the Moonlight
80727036	|	Man-Eating Black Shark
77581312	|	Masked Clown
50176820	|	Mech Bass
94412545	|	Mechaleon
23032273	|	Megirus Light
501000001	|	Meteo the Matchless
83678433	|	Midnight Fiend
46864967	|	Minomushi Warrior
17192817	|	Molten Behemoth
7225792	|	Mon Larvas
84133008	|	Monster Eye
15820147	|	Monsturtle
45909477	|	Moon Envoy
58074572	|	Mooyan Curry
79106360	|	Morphing Jar #2
31477025	|	Mr. Volcano
69992868	|	Muse-A
93900406	|	Mushroom Man #2
56342351	|	M-Warrior #1
92731455	|	M-Warrior #2
62793020	|	Mystery Hand
63515678	|	Mystical Capture Chain
30451366	|	Mystical Sheep #1
83464209	|	Mystical Sheep #2
1761063	|	Nekogal #0
43352213	|	Nekogal #2
78402798	|	Night Lizard
88643173	|	Nightmare Scorpion
56713552	|	Obese Marmot of Nefariousness
3606209	|	One Who Hunts Souls
2971090	|	Orion the Battle King
77603950	|	Phantom Dewan
52550973	|	Pharaoh's Servant
55567161	|	Pot the Trick
33691040	|	Pragtical
4179849	|	Queen of Autumn Leaves
501000003	|	Queen of Fate - Eternia
29402771	|	Rainbow Marine Mermaid
92421852	|	Robolady
38916461	|	Roboyarou
68846917	|	Rock Ogre Grotto #1
62193699	|	Rock Ogre Grotto #2
82818645	|	Rock Spirit
42647539	|	Ryu-Kishin Clown
11760174	|	Sasuke Samurai #2
77379481	|	Sasuke Samurai #3
64538655	|	Sasuke Samurai #4
2792265	|	Servant of Catabolism
10449150	|	Shuttleroid
15653824	|	Skull Knight #2
95288024	|	Sky Dragon
98075147	|	Spiked Snail
14037717	|	Spirit of the Books
34690519	|	Spirit of the Mountain
54615781	|	Spirit of the Winds
21175632	|	St. Joan
29172562	|	Steel Ogre Grotto #1
90908427	|	Steel Ogre Grotto #2
68171737	|	Stone Dragon
72269672	|	Stone Ghost
6859683	|	Success Probability 0%
75646173	|	Synchar
46247516	|	Tao the Chanter
60715406	|	Tentacle Plant
501000004	|	Testament of the Arcane Lords
403847	|	The A. Forces
1525329	|	The Hunter with 7 Weapons
98898173	|	The Melting Red Shadow
18180762	|	The Thing That Hides in the Mud
93788854	|	The Wandering Doomed
76075810	|	Throwstone Unit
62671448	|	Toad Master
79759861	|	Tribute to the Doomed
72929454	|	Turtle Bird
59053232	|	Turu-Purun
29692206	|	Twin Long Rods #2
60589682	|	Twin Long Rods 1
56789759	|	Tyhone #2
68811206	|	Tyler the Great Warrior
501000000	|	Ulevo
14731897	|	Unity
48649353	|	Ushi Oni
78556320	|	Vishwar Randi
55014050	|	Water Girl
66836598	|	Waterdragon Fairy
37243151	|	Weather Control
92409659	|	White Dolphin
2957055	|	Wicked Dragon with the Ersatz Head
92391084	|	Wilmee
47319141	|	Wing Eagle
98582704	|	Wing Egg Elf
87796900	|	Winged Dragon, Guardian of the Fortress #1
57405307	|	Winged Dragon, Guardian of the Fortress #2
42418084	|	Winged Egg of New Life
17511156	|	Wood Clown
76704943	|	Yamatano Dragon Scroll
41061625	|	Yashinoki
17115745	|	Yormungarde
81332143	|	Yu-Jo Friendship
10598400	|	Zarigun
86100785	|	Zone Eater

**Comment by AlanOC91** [comment]
Hi there,

We get our translations from Yugipedia. I checked a handful of cards and a lot of them either have no German translation in Yugipedia or only have the name in German (we have a hard clause of name + description for a translation).

Example: https://yugipedia.com/wiki/White_Dolphin

There isn't a whole lot I can do about this unfortunately. If someone wants to translate the above cards for us then I'd be more than happy to accept the translations.

However, some other cards are failing for other reasons and I will look into that and attempt to fix it. One example if St. Joan.

**Comment by AlanOC91** [comment]
One of our team members was actually table to translate all of these cards. We now have German translations for each of the cards you have listed here.

If you have any issues with it, please do let us know. 

Thanks!

**Comment by uberhalit** [comment]
> If you have any issues with it, please do let us know.

First of all thank you very much for your insanely fast fix. I do indeed have an issue with a few though.

Card ID | Card Name | Issue
------------ | ------------- | -------------
38289717 | Crawling Dragon #2 | Translation missing, has official German release
60589682 | Twin Long Rods 1 | Translation missing, no official German release; 29692206 can be used as a template: **Zwillings-Langrute 1** - *Mit ihren zwei peitschen-ähnlichen Schweifen greift diese Kreatur aus der Distanz an.*
86164529 / 85066822 | Aqua Dragon / Water Dragon | Have the exact same german name now and the API is not returning the german one. This is btw. even an issue in some old YGO games where the german translation was actually the same for these 2 cards. I'd suggest to either remove the german translation or rename Aqua Dragon to **Aqua Drache** as 85639257 also used *Aqua* in its german name
81563416 / 20188127 | Fairy of the Fountain / Fairy of the Spring | same name in german now, suggestion: Fairy of the Fountain -> **Fee der Quellen**
82818645 / 76305638 | Rock Spirit / The Rock Spirit | same name in german now, suggestion: Rock Spirit -> **Felsgeist**
3606209 / 72869010 | One Who Hunts Souls / Soul Hunter | same name in german now, suggestion: One Who Hunts Souls -> **Der Seelenjäger**

**Comment by AlanOC91** [comment]
Thanks for the feedback on this! I have applied the changes that you have recommended with the exception of:

Twin Long Rods #1. This translation does exist in our Database:

`Zwillings-Langrute #1 / Mit peitschen-ähnlichen Armen can diese Kreatur Gegner aus der Distanz angreifen.`

Are you seeing this?

Let me know if there are any other issues!

**Comment by uberhalit** [comment]
Thank you again for the fast reply. All except for 60589682 (Twin Long Rods 1) are updated and will be returned from API on my end.

> Twin Long Rods 1. This translation does exist in our Database:

Zwillings-Langrute #1 / Mit peitschen-ähnlichen Armen **kann** diese Kreatur Gegner aus der Distanz angreifen.

This would be correct, otherwise I'd say GX era is complete.
