### ISSUE TITLE
Card Database List

### ISSUE THREAD

**Issue by GX4600** [AlanOC91/YGOPRODeck#244]
Is there anyway you can add an option to generate a txt or json file of all the tcg cards for offline resource handy use?  It's time consuming to browse every single card page for 2-3 days just to say, make a wants list or look up a few cards for deck building purposes.

**Comment by AlanOC91** [comment]
If you are a developer you can use our API and make your own guide: https://db.ygoprodeck.com/api-guide/

If not, then no. That would almost defeat the purpose of having a database site :)
