### ISSUE TITLE
Pack opening pull rates (again)

### ISSUE THREAD

**Issue by forsetite** [AlanOC91/YGOPRODeck#245]
I raised the issue here (https://github.com/AlanOC91/YGOPRODeck/issues/241) and it's still absolutely broken. I still managed to pull 2 Ultras within 5 packs and Supers are way too common.

I also don't understand why you can't make the pull ratios publicly available for each pack?

**Comment by AlanOC91** [comment]
Firstly, please refrain from using phrases such as `absolutely broken`. It's not broken. Broken signifies it doesn't work at all which would have been a completely different issue I'd have to investigate. It does work and it works quite well.

Pulling 2 Ultras within 5 packs doesn't absolutely mean it's not working as intended. Our packs are not based on box ratios which is a very important point. In Yu-Gi-Oh, boxes have set ratios usually. Take the old boxes as an example. you are limited to 1 Secret Rare per box.

Our pack simulator does not follow this since it's not in the scope of a box, it's per pack. That means you could in theory pull 1, 2, 3 or more Secret Rares within 24/36 packs.

Our pull ratios are adjusted accordingly to accommodate this. 

> I also don't understand why you can't make the pull ratios publicly available for each pack?

Because I have tons of different algorithms for all the different packs and sharing it is absolutely not a priority based on my current workload. If you aren't happy with that then unfortunately it has to be that way. 

I'll will return to investigate the ratios during this week or early next week but you are honestly the first person to be so vocal to me about the pull ratios (after 19 million + packs have been opened).

**Comment by forsetite** [comment]
>Firstly, please refrain from using phrases such as absolutely broken. It's not broken. Broken signifies it doesn't work at all which would have been a completely different issue I'd have to investigate. It does work and it works quite well.

Alright - fair point on the phrase, I won't use it from now on.

>Pulling 2 Ultras within 5 packs doesn't absolutely mean it's not working as intended. Our packs are not based on box ratios which is a very important point. In Yu-Gi-Oh, boxes have set ratios usually. Take the old boxes as an example. you are limited to 1 Secret Rare per box.

While that's a good point, if knowledge of a individual pack's ratio is publicly available, why not simulate it accurately? I personally do not have a problem with regular sets as I feel like they're simulated fairly accurately. However, as I mentioned in the previous thread, tournament packs have known pull ratios:

>1 in 3 for a rare
1 in 18 for a super rare
1 in 108 for an ultra rare

There's no 1 secret guarantee per TP box, so it's not an issue like regular sets. 

At the very least, you could put a disclaimer somewhere which says that pull odds may not be reflective of real-life odds. People could be purchasing packs based on what they see on the simulator. This is particularly concerning considering you have adverts which sell TCG products.

>Because I have tons of different algorithms for all the different packs and sharing it is absolutely not a priority based on my current workload. If you aren't happy with that then unfortunately it has to be that way.

I mean, I only asked because it was ignored in the previous thread. Ideally, making the whole sim open-source would be good practice, but that's ultimately your choice, and I'll respect your decision regardless.

>I'll will return to investigate the ratios during this week or early next week but you are honestly the first person to be so vocal to me about the pull ratios (after 19 million + packs have been opened).

If people assume the pull odds are accurate, they'd have no reason to raise it as an issue? I'm only raising this because, when using the sim, I noticed things seemed off, and I want to help improve what is a good service.

Thanks for getting back to me.

**Comment by AlanOC91** [comment]
Thanks for the detailed response! To break it down:

> At the very least, you could put a disclaimer somewhere which says that pull odds may not be reflective of real-life odds. People could be purchasing packs based on what they see on the simulator. This is particularly concerning considering you have adverts which sell TCG products.

This is actually a really good point and I'm going to make this a priority.

> However, as I mentioned in the previous thread, tournament packs have known pull ratios:

I can specifically take a look at the tournament packs to see if I can improve that. Have you found this issue to be purely tournament pack related? If so, I can simply update my Tournament Pack algorithm to these odds.

> making the whole sim open-source would be good practice

For now, I won't be doing that. However, I'm definitely not completely opposed to the idea in the future.

> If people assume the pull odds are accurate, they'd have no reason to raise it as an issue? 

That's a fair point

Thanks!

**Comment by forsetite** [comment]
>I can specifically take a look at the tournament packs to see if I can improve that. Have you found this issue to be purely tournament pack related? If so, I can simply update my Tournament Pack algorithm to these odds.

Hmm, I investigated champion pack pulls and it had a similar result, although their odds are slightly different, with 1:12 for supers and 1:48 (I'm assuming rares are probably still 1:3) https://www.pojo.biz/board/showthread.php?t=404979

Otherwise, couldn't find information on exact odds for turbo/astral/ots/star packs, but there's a possibility they're off too. I did some test openings for turbo packs and high-rarity pulls still seemed a little high, but I wouldn't know what odds to change them to besides being lower.

**Comment by AlanOC91** [comment]
> > I can specifically take a look at the tournament packs to see if I can improve that. Have you found this issue to be purely tournament pack related? If so, I can simply update my Tournament Pack algorithm to these odds.
> 
> Hmm, I investigated champion pack pulls and it had a similar result, although their odds are slightly different, with 1:12 for supers and 1:48 (I'm assuming rares are probably still 1:3) https://www.pojo.biz/board/showthread.php?t=404979
> 
> Otherwise, couldn't find information on exact odds for turbo/astral/ots/star packs, but there's a possibility they're off too. I did some test openings for turbo packs and high-rarity pulls still seemed a little high, but I wouldn't know what odds to change them to besides being lower.

Hey there.

For the moment I have closely matched the Tournament Pack with the ratios you have provided. I will now do the same for Champion Packs.

Can you check Tournament Packs again for me?

**Comment by forsetite** [comment]
Heya, sorry I sorta disappeared - tournament packs seem to behaving properly, same with champ, turbo, astral packs.

Although, I'd like to raise a different issue with pack openings - Ghost Rares seem to be really easy to pull; in Cimoooo's Progression Series there's been instances where both Gage and Cimoooo both pull the cover card as a Ghost Rare (sometimes multiples); likewise in a progression league I've seen on discord there were more than 10 Ghost Rare Honests from Light of Destruction pulled, which seems rather off since Ghost Rares have a 1:288 chance of being pulled.

https://www.reddit.com/r/yugioh/comments/aezc6b/why_no_ghost_rares_information/

I think the problem is that Ghost Rares are given the same rarity weighting as "All Others" - Ultimate Rares might be too easy to pull as well but I'm not too sure about them.
