### ISSUE TITLE
Pack Opening Sim - TU04.jpg file issues

### ISSUE THREAD

**Issue by CAS-ual-TY** [AlanOC91/YGOPRODeck#246]
I have been doing some sealed draft play with a friend and we noticed something weird. The image of Tournament Pack 4 was never loading for my said friend, but it worked for me. So out of curiosity, I took a look at it. Photoshop can not edit this image at all, Paint can for whatever reason, but can not save it like any other jpg file (just hit CTRL+S to override), I have to click on "Save As" and specify the file type, as it believes that there is transparency involved (yes, in a jpg).
After just opening and saving it as jpg using Paint, it worked normal again.
This is the image in question:
https://ygoprodeck.com/pics_sets/TU04.jpg
While it does work for most people, I would still suggest just doing the same and just re-uploading it.
Cheers.

**Comment by CAS-ual-TY** [comment]
My goodness I am so dumb. Just looked at the file again while it was still in a new tab, Mozilla says its a webp file. So the file ending is just not matching to the file, not a weird jpg issue.
Wellp, now you know

**Comment by AlanOC91** [comment]
Thanks for catching this! I have converted it to be an actual .jpg file. It should work fine for you now.

Thanks!
