### ISSUE TITLE
API route for historic banned lists

### ISSUE THREAD

**Issue by SgtMurv** [AlanOC91/YGOPRODeck#247]
Hi there, firstly thank you for this API I use it all the time in test apps and it's great 😄 

I'm looking to make an app for searching historic yugioh banned lists. My question is, is this currently possible using your API? If not would this ever be possible with the data you currently have stored for each card? I think it would be a great addition to the API.

Thanks again, I hope to hear from you soon! 👍

**Comment by AlanOC91** [comment]
Hi there,

Thanks for the kind words on the API. I appreciate it!

We currently don't have this information. However, this site should contain what you need: http://ygo.anihelp.co.uk/

One day I will possibly get around to adding this info to our Database/API but for now my workload is a little high.

Thanks!

**Comment by SgtMurv** [comment]
Thanks for replying to me so fast !

I can completely understand the high workload. Thanks for the link to that
site, looks very helpful!
