### ISSUE TITLE
Random Card API endpoint doesn't seem to be encoding characters correctly

### ISSUE THREAD

**Issue by SolaceFZ** [AlanOC91/YGOPRODeck#248]
When I call `https://db.ygoprodeck.com/api/v7/randomcard.php`, this was the response:
`{
"id": 300302018,
"name": "Spell of Mask",
"type": "Skill Card",
"desc": "Activate the following Skill(s). ? If a Ritual Summoned "The Masked Beast" you control is destroyed by an opponent's card effect, you can Special Summon "Masked Beast Des Gardius" from your hand, Deck or GY, ignoring its Summoning conditions. ? You can Tribute 1 "Masked Beast Des Gardius", then add 1 "The Masked Beast" and 1 "Curse of the Masked Beast" from your Deck and/or GY to your hand. Each of these Skills can only be used once per Duel.",
"atk": null,
"def": null,
"level": null,
"race": "Lumis Umbra",
"attribute": null,
"card_sets": [
  {
"set_name": "Speed Duel: Battle City Box",
"set_code": "SBCB-ENS08",
"set_rarity": "Common",
"set_price": "$0.00"
}
],
"card_images": [
  {
"image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/300302018.jpg",
"image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/300302018.jpg"
}
],
"card_prices": [
  {
"cardmarket_price": "0.11",
"tcgplayer_price": "0.61",
"ebay_price": "1.00",
"amazon_price": "3.99"
}
],
}`

The bullet points are returned as `?` but this doesn't seem to be the case for the search or ID APIs.
`https://db.ygoprodeck.com/api/v7/cardinfo.php?id=300302018`
`{
"data": [
  {
"id": 300302018,
"name": "Spell of Mask",
"type": "Skill Card",
"desc": "Activate the following Skill(s). ● If a Ritual Summoned "The Masked Beast" you control is destroyed by an opponent's card effect, you can Special Summon "Masked Beast Des Gardius" from your hand, Deck or GY, ignoring its Summoning conditions. ● You can Tribute 1 "Masked Beast Des Gardius", then add 1 "The Masked Beast" and 1 "Curse of the Masked Beast" from your Deck and/or GY to your hand. Each of these Skills can only be used once per Duel.",
"race": "Lumis Umbra",
"card_sets": [
  {
"set_name": "Speed Duel: Battle City Box",
"set_code": "SBCB-ENS08",
"set_rarity": "Common",
"set_rarity_code": "(C)",
"set_price": "0.00"
}
],
"card_images": [
  {
"id": 300302018,
"image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/300302018.jpg",
"image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/300302018.jpg"
}
],
"card_prices": [
  {
"cardmarket_price": "0.11",
"tcgplayer_price": "0.61",
"ebay_price": "1.00",
"amazon_price": "3.99",
"coolstuffinc_price": "0.39"
}
],
}
],
}`

**Comment by SolaceFZ** [comment]
By the way I also tried both reqs with and without `Content-Type: application/json; charset=utf-8` and seems the same issue persists.

**Comment by AlanOC91** [comment]
Thanks for the report! This is fixed now.

I forgot to set the query default client character set to utf-8

**Comment by SolaceFZ** [comment]
Can verify that this is fixed. Thanks!
