### ISSUE TITLE
Stardust Synchron and Stardust Trail are swapped

### ISSUE THREAD

**Issue by aDudman** [AlanOC91/YGOPRODeck#255]
The card images of [Stardust Syncrhon](https://db.ygoprodeck.com/card/?search=Stardust%20Synchron) and [Stardust Trail](https://db.ygoprodeck.com/card/?search=Stardust%20Trail) are swapped, with the Stardust Synchron page showing Stardust Trail and the Stardust Trail page showing Stardust Synchron. The information on each page seems correct, just the images are wrong.

**Comment by AlanOC91** [comment]
Thanks for the report! This is all fixed now!
