### ISSUE TITLE
Blazing Vortex Starlight Set Cards Problems 

### ISSUE THREAD

**Issue by n1xx1** [AlanOC91/YGOPRODeck#256]
There are some issues with the Blazing Vortex cards set informations for Starlight cards.

* *Armed Dragon Thunder LV10* has `"set_rarity": "StR"` and `"set_rarity": "Starlight Rare"`
* *Heavenly Zephyr - Miradora* has `"set_rarity": "StR"` and `"set_rarity": "Starlight Rare"`
* *Pot of Prosperity* has `"set_rarity": "StR"` and `"set_rarity": "Starlight Rare"`
* *Trishula, Dragon of the Ice Barrier* has `"set_rarity": "StR"` and `"set_rarity": "Starlight Rare"`
* *Live☆Twin Lil-la Treat* has only `"set_rarity": "StR"` 

Thank you for the great work with the API.

**Comment by AlanOC91** [comment]
Thanks for the report on this! I've fixed these and identified the cause of the issue so this shouldn't happened again in the future.
