### ISSUE TITLE
Some rarities need fixing

### ISSUE THREAD

**Issue by westhouseit** [AlanOC91/YGOPRODeck#258]
I've come across some rarity issues that can hopefully be solved quite easily.

1. Super Short Print. Apparently there's no such thing, just Short Print. See Trivia section on: https://yugioh.fandom.com/wiki/Short_Print
2. A few rarities listed as "c", should be "Common", although they may be duplicates to be removed. See OP15-EN017, OP15-EN024
3. The rarity "Duel Terminal Normal Parallel Rare" is shown in cases like DT06-EN008 with the correct code DNPR, but then also duplicated with the same code, but the wrong name "Duel Terminal Normal Parallel"

**Comment by AlanOC91** [comment]
Thanks for the feedback on this!

1. I see your point. However there was indeed a long standing [rumor](https://yugipedia.com/wiki/Forum:Card_in_MRL_listed_as_Super_Short_Print%3F) that it did exists but was never officially acknowledged. You can see a couple more [references to it here](https://www.pojo.biz/board/showthread.php?t=109495) from 2004 even. Considering the pool of "Super Short Print" cards is so small, I'm going to leave it as is for now.
2. Fixed! 
3. Fixed!
