### ISSUE TITLE
Missing Rarities & Incorrect Card Info

### ISSUE THREAD

**Issue by blackedge0** [AlanOC91/YGOPRODeck#259]
I've noticed that many cards are missing rarities from the database, all of which are included in this txt document.

[MIssing Rarities.txt](https://github.com/AlanOC91/YGOPRODeck/files/6079456/MIssing.Rarities.txt)

I also noticed that Premium Gold Rare (PGR) (from Maximum Gold), Collectors Rare (CR) (from Toon Chaos onward), and 10000 Secret Rare (10000ScR) are entirely missing from the database. Consider adding?

---

Also, a few cards have incorrect information as far as card numbers and sets are concerned, included in this txt document.

[Missing&Incorrect Cards.txt](https://github.com/AlanOC91/YGOPRODeck/files/6079496/Missing.Incorrect.Cards.txt)

Consider renaming Falchion Beta to its correct name Falchionβ? Cards like Evil★Twin Ki-sikil already use non-ASCII encoding so it shouldn't be an issue.

**Comment by AlanOC91** [comment]
Hey there,

Thanks for the report! Indeed you are correct and I was missing a lot of rarity codes.
I've added these rarity codes now and they will appear once the cache updates! 

Also thank you for the missing/incorrect cards.

MF03-EN010 Cyber Dragon -> Not a Card
Good shout on this. It was [recently discovered](https://www.reddit.com/r/yugioh/comments/kqm2yb/confirmed_authentic_psa_graded_parallel_rare/) that it was EN009. I've fixed that.

The rest should also be fixed now.

I'll consider Falchion Beta. I agree it makes sense to do it but I need to double check a few other table joins to make sure nothing breaks. 

Thanks again!
