### ISSUE TITLE
Incorrect card data: Link Monsters & Link values

### ISSUE THREAD

**Issue by TheOtterlord** [AlanOC91/YGOPRODeck#260]
I've found a few card issues with the link monsters and their link values/markers. At first I only spotted Underworld Goddess, but as I use your API as a core part of my project (thanks btw. Love your API) I decided to write a script to test all cards for similar faults. These are the results of that script, and I've added notes to 2 who's situation is different from the rest. 

- Traptrix Utricularia (952523) has a link value of 1 and a total of 2 link markers
- Sunavalon Daphne (7984540) has a link value of 1 and a total of 2 link markers
- Evil★Twin Ki-sikil (9205573) has a link value of 1 and a total of 2 link markers
- Lyna the Light Charmer, Shining (9839945) has a link value of 1 and a total of 2 link markers
- The Arrival Cyberse @Ignister (11738489) has a link value of 6 and a total of 5 link markers **(missing bottom)**
- Tri-Brigade Ferrijit the Barren Blossom (26847978) has a link value of 1 and a total of 2 link markers
- Steel Star Regulator (32986898) has a link value of 1 and a total of 3 link markers
- S-Force Justify (35334193) has a link value of 1 and a total of 3 link markers
- Paleozoic Cambroraster (36346532) has a link value of 1 and a total of 2 link markers
- Evil★Twin Lil-la (36609518) has a link value of 1 and a total of 2 link markers
- Sunavalon Melias (44478599) has a link value of 1 and a total of 3 link markers
- Tri-Brigade Bearbloom the Heavy Hitter (47163170) has a link value of 1 and a total of 2 link markers
- Tri-Brigade Rugal the Silver Sheller (52331012) has a link value of 1 and a total of 3 link markers
- Heavymetalfoes Amalgam (61728808) has a link value of 1 and a total of 2 link markers
- Sunavalon Dryanome (65285459) has a link value of 1 and a total of 3 link markers
- Benghalances of the Samsaric Cycle (73345237) has a link value of 1 and a total of 4 link markers
- Taotie Dragon (82566662) has a link value of 1 and a total of 3 link markers
- Underworld Goddess of the Closed World (98127546) has a link value of 1 and a total of 5 link markers
- Borrelend Dragon (98630720) has a link value of 5 and a total of 6 link markers **(includes bottom which is incorrect)**
- Tri-Brigade Shuraig the Ominous Omen (99726621) has a link value of 1 and a total of 4 link markers

**Comment by AlanOC91** [comment]
Thank you for this excellent feedback! I have fixed all of these link monsters now.

I have also identified an issue in my new card script that was setting the link value to 1 for all the new link monster cards. This has now also been resolved.
