### ISSUE TITLE
German Translation missing on 4 cards

### ISSUE THREAD

**Issue by BentiGorlich** [AlanOC91/YGOPRODeck#261]
Hello,

I am using your API and I noticed that the german translation on these 4 cards is missing:
- "F.A. Shining Star GT" (37414347)
- "F.A. Sonic Meister" (67045745)
- "Where Arf Thou?" (51405049)
- "Tri-gate Wizard" (32617464)

The error message from the api is just the same as if the card would't be available at all. (I think that should be changed as well)
Can they be added?
I would like to help with the german translation (I do have the german cards for them)

**Comment by AlanOC91** [comment]
Fixed! I found an issue whereby these translations weren't inserted (and a couple of others). Working on fixing that now. Thanks!
