### ISSUE TITLE
API: Ghosts from the Past cards return two GFTP sets with different values

### ISSUE THREAD

**Issue by wolfborg** [AlanOC91/YGOPRODeck#267]
When I do an API query of cards from the Ghosts from the Past set, there are two card sets returned for the one cardset:
1. "Ghosts from the Past": has default "Common" rarities and "0" set prices
2. "Ghosts from the Past (set)": correct rarities and set prices

The two cardset infos share the same set code values, but all the other values seem to differ.
Example: https://db.ygoprodeck.com/api/v7/cardinfo.php?fname=Arkbrave%20Dragon

But some cards don't have this double set issue, such as all six "Ghost Rare" cards.
Example: https://db.ygoprodeck.com/api/v7/cardinfo.php?fname=Crystal%20Wing%20Synchro%20Dragon

Query for the whole cardset: https://db.ygoprodeck.com/api/v7/cardinfo.php?cardset=ghosts%20from%20the%20past

I'm not sure if it's because this set is new or from some kind of issue due to the Ghosts from the Past set and a [trap card](https://db.ygoprodeck.com/card/?search=Ghosts%20From%20the%20Past) sharing the same name causing the cardset in many places to append "(set)" to the name.

The correct information is sent using cardsetsinfo.php:
https://db.ygoprodeck.com/api/v7/cardsetsinfo.php?setcode=GFTP-EN072
However I need to get the cards through the card name instead of a setcode, so using this wouldn't help for my purposes, but it probably helps with looking into this issue.

Although I did also notice while trying to use cardsetsinfo.php that an error response says you need the parameter "setname" when it should be "setcode", which should probably be updated.

To add onto this: searching the set on the website brings up no prices and only classifies the ghost rares properly.
https://db.ygoprodeck.com/set/?search=Ghosts%20from%20the%20Past

Thank you so much for your work on this API, it's been a huge help!

**Comment by AlanOC91** [comment]
Ghosts from the Past (set) as a naming scheme was a mistake and should have been stripped down to "Ghosts From the Past". This has now been remedied and the set should now be corrected. You may need to clear your own local cache on your end when calling it again.

Thank you for the report on this.

I'll also get cardsetsinfo.php updated also!
