### ISSUE TITLE
Set codes problems in the database

### ISSUE THREAD

**Issue by n1xx1** [AlanOC91/YGOPRODeck#269]
I was doing some experiments and I checked the uniqueness of set codes, so I'm reporting what I've found.

* _Dark Scorpion - Meanae the Thorn_ also has the set code `SBCB-EN155`
* _Amplifier_ also has the set code `SBCB-EN156`
* _Book of life_ also has the set code `SBSC-EN012`
* _I'm Just Gonna Attack!_ also has the set code `SBCB-ENS11`
* _Rise of the Fallen_ also has the set code `SBCB-ENS12`
* _Beasts of Phantom_ also has the set code `SBCB-ENS13`
* _Roaring Earth_ also has the set code `YDT1-EN001`
* _Enemy Controller_ also has the set code `LDK2-ENK25`
* _Spell Power Grasp_ also has the set code `SDSC-EN004`, the set is named _Speed Duel: Scars of Battle_
* _Skill Proof Armor_ also has the set code `EVSD-ENS02`
* _Spiral Flame Strike_ also has the set code `LEDD-ENC19`
* _Sword of Dark Destruction_ also has the set code `SBAD-EN020`
* _Vision HERO Witch Raider_ also has the set code `BLHR-EN059`
* _Winged Kuriboh LV10_ has the set code `MF03-EN001` even though it's actual set code is not known
* _Zubaba Knight_ also has the set code `DL15-EN008`, I think it's an error in the wiki. Zubaba Knight is not listed in [that set](https://yugipedia.com/wiki/Duelist_League_13_participation_cards)

While skimming through this list I also noticed that some sets are duplicated with the same code and rarity, but interestingly different price.

Here is a list, I didn't have time to check every single entry.
* _A.I.'s Ritual_
* _Aroma Strategy_
* _Bandit_
* _Beatdown!_
* _Bluebeard, the Plunder Patroll Shipwright_
* _Call of the Haunted (Skill Card)_
* _Catch of the Day_
* _Chaos Daedalus_
* _Cocoon of Ultra Evolution (Skill Card)_
* _Cybernetic Overflow_
* _Destined Rivals_
* _Destiny Draw_
* _Destiny Draw (Skill Card)_
* _Digging for Gold_
* _Dino Destruction_
* _Dinosaur Kingdom_
* _DoSolfachord Coolia_
* _Double Evolution Pill (Skill Card)_
* _Dragon Caller_
* _Ectoplasmic Fortification!_
* _Emblem of the Plunder Patroll_
* _Eternal Chaos_
* _FaSolfachord Fancia_
* _Final Draw_
* _Flight of the Harpies_
* _Flourishing Frolic_
* _Fusion Party!_
* _Goldenhair, the Newest Plunder Patroll_
* _Gravekeeper's Lot_
* _Grit_
* _Heavy Metal Raiders (Skill Card)_
* _Hidden Parasite_
* _Hollow Giants_
* _Hyper Metamorphosis_
* _It's a Toon World!_
* _It's My Lucky Day!_
* _Jabbing Panda_
* _Last Gamble_
* _Low Blow_
* _Mahaama the Fairy Dragon_
* _Mayakashi Mayhem_
* _Millennium Eye (Skill Card)_
* _Millennium Necklace (Skill Card)_
* _Mind Scan (Skill Card)_
* _Mythic Depths_
* _Myutant Arsenal_
* _Myutant Beast_
* _Myutant Blast_
* _Myutant Clash_
* _Myutant Cry_
* _Myutant Evolution Lab_
* _Myutant Expansion_
* _Myutant Fusion_
* _Myutant GB-88_
* _Myutant M-05_
* _Myutant Mist_
* _Myutant ST-46_
* _Myutant Synthesis_
* _Myutant Ultimus_
* _Necroquip Prism_
* _Nightmare Sonic Blast!_
* _Pal-O'Mine-zation!_
* _Peak Performance_
* _Periallis, Empress of Blossoms_
* _Photon Vanisher_
* _Plunder Patroll Parrrty_
* _Plunder Patroll Shipshape Ships Shipping_
* _Plunder Patrollship Lys_
* _Power of Dark_
* _Prescience_
* _Pride of the Plunder Patroll_
* _Red Blossoms from Underroot_
* _Ritual Ceremony_
* _Rose Girl_
* _Royal Flush_
* _Scrypton_
* _Servants of the Fallen King_
* _Skull Meister_
* _Snake Rain_
* _Spell Proof Armor_
* _Straight to the Grave_
* _Strength in Unity_
* _Successor Soul_
* _Switcheroo_
* _Taotie Dragon_
* _Terror from the Deep!_
* _The World's Greatest Fisherman_
* _Tomb of the Pharaoh_
* _Toon Bookmark_
* _Toon Harpie Lady_
* _Toon Page-Flip_
* _Toon Terror_
* _Traptrix Genlisea_
* _Tribal Synergy_
* _Ursarctic Septentrion_
* _Vennominaga the Deity of Poisonous Snakes_
* _Viral Infection_
* _Zombie Master (Skill Card)_

**Comment by AlanOC91** [comment]
Hi there,

Thank you for the detailed bug report on this.

I can confirm that I have pretty much cleaned and fixed almost all of this. Cache has been cleared so you should receive the new information on future calls.

 I will monitor and investigate further for other data discrepancies.
