### ISSUE TITLE
Auster the South Wind not marked as Tuner

### ISSUE THREAD

**Issue by aDudman** [AlanOC91/YGOPRODeck#271]
The card [Blackwing - Auster the South Wind](https://db.ygoprodeck.com/card/?search=Blackwing%20-%20Auster%20the%20South%20Wind) is a Tuner monster, but it is not marked as a Tuner monster on its page and it doesn't show up in a search for [Blackwing Tuners](https://db.ygoprodeck.com/search/?&type=Tuner%20Monster&archetype=Blackwing&num=30&offset=0&view=List).

**Comment by AlanOC91** [comment]
Thanks for the report! This is fixed now.
