### ISSUE TITLE
Inconsistency concerning Pack simulator

### ISSUE THREAD

**Issue by BantramFidian** [AlanOC91/YGOPRODeck#273]
Greetings,

I have been doing some pack openings and stumbled over inconsistencies with the Spell Ruler Set.

When opening "Magic Ruler" via pack simulator it draws from the european release. 
[e.g. I got Pot of greed several times]
I am located in Germany, so that part might be intentional from what I gathered from 
https://github.com/AlanOC91/YGOPRODeck/issues/229

But when looking at the set list it lists the original international release.
[ https://db.ygoprodeck.com/set/?search=Spell%20Ruler ]

This is the first instance that I noticed this behaviour.

I would love to do a pack opening of the international release, to have a fair drafting tournament with friends from overseas.
So an option to set prefered releaseVersion or something would be highly appreciated.

**Comment by AlanOC91** [comment]
Definitely doable and at this stage, it's been requested enough that I might just swap it over to the international release for now and add an option for the European release later.

**Comment by AlanOC91** [comment]
Magic Ruler has now been split into two: "Magic Ruler" and "Magic Ruler (European)". The European version correctly includes the LOB cards while the regular version does not.
