### ISSUE TITLE
Limit / error with importing high volume sealed draft to the collection log

### ISSUE THREAD

**Issue by heyitsthatdude17** [AlanOC91/YGOPRODeck#277]
I noticed while doing some tests of the sealed draft mode on the pack opener that not all the cards were making it to my collection when I attempted to import them. The limit appears to be 248 cards. At the rate of 9 cards per pack (I tested with LOB and MRD), this means only 248/9 = 27.5 worth of packs were able to be imported. Therefore when doing a sealed draft and selecting either the 29, 30, or 36 pack option there would be 1.5, 2.5 or 8.5 packs worth of cards missing. 24 packs and under works perfectly fine since this is under the 248 card limitation. I tested this with both LOB and MRD, testing pulls of 6, 24, 29, 30, and 36 packs.

**Comment by AlanOC91** [comment]
Can replicate the issue. Will investigate.

**Comment by AlanOC91** [comment]
Test - Open 30 Packs of Legend of Blue Eyes.
30x9 = 270.

- Front end Javascript = Array Correctly holds 270 cards once draft is complete.
- Split down for posting using Ajax POST.
- Split 1 size = 135
- Split 2 size = 68
- Split 3 size = 34
- Split 4 size = 33
- Total = 270

However, the server is reading it as 260 cards. I set up a track on the server and the result was:
- Split 1 size = 125
- Split 2 size = 68
- Split 3 size = 34
- Split 4 size = 33
- Total = 260

It seems sending 135 cards in one request is too large and needs to be broken down more. 

Will attempt that now.

**Comment by AlanOC91** [comment]
Evenly splitting it into 4 chunks has successfully uploaded the 270 cards to the collection.

- Split 1 size = 67
- Split 2 size = 68
- Split 3 size = 68
- Split 4 size = 67
- Total = 270

So this is essentially fixed. I need to implement a tracker to make sure a single Ajax POST request doesn't get too large and ends up being evenly split down into chunks.
