### ISSUE TITLE
Incorrect Cards in King's Court

### ISSUE THREAD

**Issue by blackedge0** [AlanOC91/YGOPRODeck#282]
For some reason Common is showing up as a rarity within many of the cards in King's Court (KICO), even though Common does not exist within the release.

Also, KICO-EN013 Number F0: Utopic Draco Future is missing from the set entirely.

**Comment by AlanOC91** [comment]
Good catch. This was a result of our data being added before the full rarity reveal meaning they all had a fallback to a default of common rarity.

This is resolved now!
