### ISSUE TITLE
Missing set - War of the Giants Reinforcements/Round 2

### ISSUE THREAD

**Issue by forsetite** [AlanOC91/YGOPRODeck#283]
Just noticed this set was missing so I figured I'd submit it here in the hopes that it could be included on the sim.

The set contains 104 (Reinforcements) or 103 (Round 2) cards, with the only difference being that Round 2 is the US set release and is only missing Zubaba General.

Each pack has 16 cards, 1 UR, 6 SR, 9 C.

The breakdown can be found here: https://yugioh.fandom.com/wiki/War_of_the_Giants_Reinforcements

Given that packs like movie packs, McDonalds promos, and tin-exclusive packs are also on the sim, it'd be nice to see this one too; shouldn't be relatively hard to either.

Thanks! :)

**Comment by forsetite** [comment]
Bumping this because I saw OTS pack 16 got added when someone else reported it as missing - why not this set as well?

**Comment by forsetite** [comment]
Bumping again - can we at least have a reason why this pack shouldn't be included on the sim? :\

**Comment by AlanOC91** [comment]
War of the Giants Round 2 has been added.
