### ISSUE TITLE
Wrong 'has_effect' parameter on some Monsters in API

### ISSUE THREAD

**Issue by HadesTeufel** [AlanOC91/YGOPRODeck#287]
While using the API, the following Extra Deck Monsters without effects return a wrong 'has_effect' parameter:

- Gaia Knight, the Force of Earth
- Gaia Saber, the Lightning Shadow
- Vector Pendulum, the Dracoverlord

I only checked the Monsters listed in the pastebin link in #218.
Therefore I do not know, if there are other instances regarding this issue.

**Comment by AlanOC91** [comment]
Fixed. Should be updated on the next cache clear.

**Comment by The0mbudsman** [comment]
Feels silly to open a new issue, but the following four cards should also have a 0 for has_effect

"power-pro-lady-sisters"
"anotherverse-dragon"
"doll-monster-miss-madchen"
"doll-monster-bear-bear"
