### ISSUE TITLE
[Suggestion] Include anchor tags on the website endpoint descriptions

### ISSUE THREAD

**Issue by nathaneastwood** [AlanOC91/YGOPRODeck#288]
This would allow me to point users of my API wrapper to elements of the documentation on the website rather than just the generic https://db.ygoprodeck.com/api-guide/ link. It would be nice to say something like "you can find all races \[here\](...)".

**Comment by AlanOC91** [comment]
Good idea. I'll work on adding a table of contents to the page but for now;

https://db.ygoprodeck.com/api-guide#card-info
https://db.ygoprodeck.com/api-guide#api-examples
https://db.ygoprodeck.com/api-guide#endpoint-information
https://db.ygoprodeck.com/api-guide#api-languages
https://db.ygoprodeck.com/api-guide#card-images
https://db.ygoprodeck.com/api-guide#random-card
https://db.ygoprodeck.com/api-guide#card-sets
https://db.ygoprodeck.com/api-guide#card-archetypes
https://db.ygoprodeck.com/api-guide#code-ver
https://db.ygoprodeck.com/api-guide#api-credits

**Comment by nathaneastwood** [comment]
Thanks a lot - this is great!
