### ISSUE TITLE
[Suggestion] Add an Open All button 

### ISSUE THREAD

**Issue by UnkleYug** [AlanOC91/YGOPRODeck#289]
I don't see anywhere for suggestions so I'm going to try my luck here, apologies in advance. 

Is there any chance you could add a button that opens all of the packs at once? Like if I want to open 24 packs, can I just press a button that opens all of them at once and then save them to my trunk instead of opening singular packs. It'd save a lot of time if you're trying to draft more than one set.

**Comment by f-master** [comment]
https://github.com/AlanOC91/YGOPRODeck/issues/179

**Comment by AlanOC91** [comment]
We are in the middle of overhauling a lot of features on YGOPRODeck. This includes the Pack Simulator. I've finished up an "Open All" feature this morning. 

However, please do not expect this feature to be released for another couple of months.

Preview can be viewed here: https://imgur.com/a/apqAxsZ

A new announcement will be made once released.
