### ISSUE TITLE
Fortune Chariot incorrect attribute

### ISSUE THREAD

**Issue by aDudman** [AlanOC91/YGOPRODeck#292]
In the DB the card [Fortune Chariot](https://db.ygoprodeck.com/card/?search=Fortune%20Chariot) is listed as LIGHT attribute, but as can be seen in the card image and the [official DB](https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=13996) the correct attribute is WIND.

**Comment by AlanOC91** [comment]
Fixed!
