### ISSUE TITLE
P.U.N.K. archetype cards have no description

### ISSUE THREAD

**Issue by aDudman** [AlanOC91/YGOPRODeck#296]
All cards in the P.U.N.K. archetype have an empty `desc` field, which shows up in [your own search](https://db.ygoprodeck.com/search/?&fname=P.U.N.K.&desc=P.U.N.K.&num=30&offset=0&view=List) as well as [API requests](https://cdn.discordapp.com/attachments/612948481715208193/878818098596171836/unknown.png)

**Comment by AlanOC91** [comment]
Found the bug in one of my scripts that caused this. Now fixed. API cache will be cleared soon.
