### ISSUE TITLE
King's Court Set: Double Listing of Collector's Rare cards (Collector's Rare & Collectors Rare)

### ISSUE THREAD

**Issue by CAS-ual-TY** [AlanOC91/YGOPRODeck#298]
Eg. check out Arcana Triumph Joker: https://db.ygoprodeck.com/api/v7/cardinfo.php?name=Arcana%20Triumph%20Joker

It is listed in the set King's Court as "Collector's Rare" and "Collectors Rare".

This is the case for the following cards:
KICO-EN001
KICO-EN002
KICO-EN003
KICO-EN004

**Comment by CAS-ual-TY** [comment]
Oh, and to add to this: "Burning Soul" (card) is still named "Blazing Soul".

**Comment by AlanOC91** [comment]
Both issues now fixed.
