### ISSUE TITLE
New Rush Duel Sets Missing

### ISSUE THREAD

**Issue by smith-ross** [AlanOC91/YGOPRODeck#305]
Strongest Battle Deck (Yuga, Luke, Gakuto, Romin, Roa, Neiru, Asana)
Saikyo Battle Pack
Deck Modification Pack - Fierce Thunder Storm!!

I've noticed the cards from these sets are missing from the API, would be appreciated if they could be added. Thanks.

**Comment by AlanOC91** [comment]
Hey there,

These are all added now!
