### ISSUE TITLE
Rush Duel Cards missing without specific filter

### ISSUE THREAD

**Issue by necrodraco** [AlanOC91/YGOPRODeck#310]
If I get all the cards via 
`https://db.ygoprodeck.com/api/v7/cardinfo.php`
then I can't find Rush Duel Cards in the response. 

If I filter it by the format, the cards appear: 
`https://db.ygoprodeck.com/api/v7/cardinfo.php?format=Rush%20Duel`

If that is on purpose, please add this information to the API Documentation (https://db.ygoprodeck.com/api-guide/) so to get information if other games get the same treatment. Because under the example "Get all cards" I guess I would get "all cards". 

If it's not, then this is a bug report.

**Comment by AlanOC91** [comment]
This is intentionally done as Rush Duel cards are completely different from the Yu-Gi-Oh! TCG in general.
