### ISSUE TITLE
Tribute to the Doomed has an "\t" at the end of the german name

### ISSUE THREAD

**Issue by larikk** [AlanOC91/YGOPRODeck#326]
Example query: https://db.ygoprodeck.com/api/v7/cardinfo.php?language=de&fname=Ehrung%20der

German name is "Ehrung der Verdammten\t"

**Comment by larikk** [comment]
Found some more cards with that issue:

82112775 D.D.M. - Different Dimension Master
51828629 Giltia the D. Knight
11760174 Sasuke Samurai #2

**Comment by AlanOC91** [comment]
This is fixed now and implement a fix on the script that updates the alternative languages. This also helped me discover a major bug with adding new cards to our language database so thanks for that!

These changes will go live when cache on the server clears later today.
