### ISSUE TITLE
Archetype Endpoint don't support special characters

### ISSUE THREAD

**Issue by necrodraco** [AlanOC91/YGOPRODeck#327]
When I call https://db.ygoprodeck.com/api/v7/archetypes.php the endpoint doesn't return special characters like ★ in "evil twins" and the same for live twin. But the cardinfo-endpoint supports this characters and set the correct characters into the "archetype" field. this makes matching actions really hard. 

On the way: it seems like there is an error in the archetype name of "attraction": the archetype endpoint returns the "beta name" of amazements attraction with the ? instead of the correct character: {"archetype_name":"?ttraction"}]
But when I don't miss anything, these where updated into an normal "A" in tcg: https://yugipedia.com/wiki/Attraction
So it seems like it's an incorrect data.

**Comment by AlanOC91** [comment]
Thanks for this! This is now fixed.
