### ISSUE TITLE
Burst of destiny has possibly a wrong date in card set endpoint

### ISSUE THREAD

**Issue by larikk** [AlanOC91/YGOPRODeck#328]
Endpoint in question: https://db.ygoprodeck.com/api/v7/cardsets.php

Date in the DB is 2021-10-21

According to Yugipedia and Konami it should be the 4th/5th of November though:

* https://yugipedia.com/wiki/Burst_of_Destiny
* https://www.yugioh-card.com/en/products/bp-bode.html

**Comment by AlanOC91** [comment]
Thanks for the report. This is fixed now. Will update when the server cache is cleared.
