### ISSUE TITLE
Incorrect rarities in Rising Rampage

### ISSUE THREAD

**Issue by larikk** [AlanOC91/YGOPRODeck#330]
Query with affected cards: https://db.ygoprodeck.com/api/v7/cardinfo.php?id=36492575,%2095192919,50820852

Three cards have one rarity entry too much for Rising Rampage.

Marincess Sea Horse: "Rare" rarity is incorrect, others are correct
Simorgh, Bird of Beginning: "Super Rare" is incorrect other is correct
Simorgh, Lord of the Storm: "Secret Rare" is incorrect, other is correct

I compared the rarities with Yugipedia and the Konami DB:
* https://yugipedia.com/wiki/Rising_Rampage
* https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=1&sess=1&pid=11118006&rp=99999

**Comment by AlanOC91** [comment]
Thanks for the report, this is fixed now.
