### ISSUE TITLE
Mistakes in Blazing Vortex

### ISSUE THREAD

**Issue by larikk** [AlanOC91/YGOPRODeck#331]
Query with affected cards: https://db.ygoprodeck.com/api/v7/cardinfo.php?id=%2057030525,21546416,57605303,56518311,09322133

These cards are incorrectly listed as having a common printing:
Armed Dragon Thunder LV3
Armed Dragon Thunder LV5
Armed Dragon Thunderbolt
Metalfoes Vanisher 
Psychic Eraser Laser

Their other printings are correct.

**Comment by AlanOC91** [comment]
This is fixed now!
