### ISSUE TITLE
Same set code is used for different cards

### ISSUE THREAD

**Issue by larikk** [AlanOC91/YGOPRODeck#333]
After the issues with numbered cards mentioned in #332 (Luster Dragon, Sasuke Samurai etc) I decided to write a script that checks for set codes that are listed for two different cards. Here is what I found.

`SBSC-EN012: ['Book of Life', 'Fire Reaper']`
https://db.ygoprodeck.com/api/v7/cardinfo.php?id=2204140,53581214
Book of Life is SBSC-EN013 which is correctly present. Fire Reaper has the correct set code.

`LDK2-ENK25: ['Enemy Controller 98045062', 'Silent Doom 42534368']`
https://db.ygoprodeck.com/api/v7/cardinfo.php?id=98045062,42534368
Enemy Controller is LDK2-ENK23 which is correctly present. Silent Doom has the correct set code.

`DL15-EN008: ['Granmarg the Rock Monarch 60229110', 'Zubaba Knight 97896503']`
https://db.ygoprodeck.com/api/v7/cardinfo.php?cardset=Duelist%20League%2013%20participation%20cards
https://db.ygoprodeck.com/api/v7/cardinfo.php?id=60229110,97896503
Granmarg should be DL13, not DL15

```
BP02-EN001: ['Luster Dragon #2 17658803', 'Luster Dragon 11091375']
BP01-EN111: ['Luster Dragon #2 17658803', 'Luster Dragon 11091375']
DR1-EN113: ['Luster Dragon #2 17658803', 'Luster Dragon 11091375']
SDBE-EN004: ['Luster Dragon #2 17658803', 'Luster Dragon 11091375']
YSD-EN005: ['Luster Dragon #2 17658803', 'Luster Dragon 11091375']
YSKR-EN007: ['Luster Dragon #2 17658803', 'Luster Dragon 11091375']
SD1-EN003: ['Luster Dragon #2 17658803', 'Luster Dragon 11091375']
SDKS-EN019: ['Luster Dragon #2 17658803', 'Luster Dragon 11091375']
YS14-EN002: ['Luster Dragon #2 17658803', 'Luster Dragon 11091375']
TP5-EN004: ['Luster Dragon #2 17658803', 'Luster Dragon 11091375']
```
I looked them all up, all of these set codes belong to the first one.

```
DB2-EN216: ['Sasuke Samurai #4 64538655', 'Sasuke Samurai 16222645']
LCJW-EN034: ['Sasuke Samurai #4 64538655', 'Sasuke Samurai 16222645']
PGD-015: ['Sasuke Samurai #4 64538655', 'Sasuke Samurai 16222645']
SBTK-EN015: ['Sasuke Samurai #4 64538655', 'Sasuke Samurai 16222645']
5DS2-EN010: ['Sasuke Samurai #4 64538655', 'Sasuke Samurai 16222645']
```
Same thing that I mentioned in the other issue.

`CP08-EN012: ['Mushroom Man #2 93900406', 'Mushroom Man 14181608']`
https://db.ygoprodeck.com/api/v7/cardinfo.php?id=93900406,14181608
Set code belongs to the first `#1` only

**Comment by AlanOC91** [comment]
These should all be fixed now!

**Comment by larikk** [comment]
Luster Dragon 2 still has two set codes of the first one.
```
YSD-EN005: ['Luster Dragon #2 17658803', 'Luster Dragon 11091375']
SDKS-EN019: ['Luster Dragon #2 17658803', 'Luster Dragon 11091375']
```

Everything else is fixed 👍

**Comment by AlanOC91** [comment]
Can you try again for me? I cleared both server-side cache and Cloudflare cache.

**Comment by larikk** [comment]
I'm not sure why but it looks like everything from the first comment is back:

```
SBSC-EN012: ['Book of Life 2204140', 'Fire Reaper 53581214']
MRD-012: ['Crawling Dragon #2 38289717', 'Crawling Dragon 67494157']
MRD-E012: ['Crawling Dragon #2 38289717', 'Crawling Dragon 67494157']
MRD-EN012: ['Crawling Dragon #2 38289717', 'Crawling Dragon 67494157']
LDK2-ENK25: ['Enemy Controller 98045062', 'Silent Doom 42534368']
DL15-EN008: ['Granmarg the Rock Monarch 60229110', 'Zubaba Knight 97896503']
SDKS-EN019: ['Luster Dragon #2 17658803', 'Luster Dragon 11091375']
DB2-EN216: ['Sasuke Samurai #4 64538655', 'Sasuke Samurai 16222645']
LCJW-EN034: ['Sasuke Samurai #4 64538655', 'Sasuke Samurai 16222645']
PGD-015: ['Sasuke Samurai #4 64538655', 'Sasuke Samurai 16222645']
SBTK-EN015: ['Sasuke Samurai #4 64538655', 'Sasuke Samurai 16222645']
5DS2-EN010: ['Sasuke Samurai #4 64538655', 'Sasuke Samurai 16222645']
```

I use `https://db.ygoprodeck.com/api/v7/cardinfo.php?format=tcg` in my script btw.

**Comment by AlanOC91** [comment]
Arghhh I found the culprit. A very old cron job script from 2017 that was pulling from a relatively unreliable source for data. This cron has been removed and the data you posted there has been fixed once again.

**Comment by larikk** [comment]
Looks good, my script does not find any duplicates anymore. Thank you :)
