### ISSUE TITLE
german cards with false umlauts, probably bigger encoding

### ISSUE THREAD

**Issue by necrodraco** [AlanOC91/YGOPRODeck#338]
Today, I let my matching script running to your api again. Last Time was done last week. 

I found some problems with missing "umlauts" (äöü, probably also ß and other non ascii-stuff). E.g. for the card Tailwind of Gusto in german "Rückenwind von gusto" I got these change: 

-Name changed: Rückenwind von Gusto->Rckenwind von Gusto

I simply checked this for round about 1000/10000 cards, but it got a lot of this missing umlauts. I guess this error also occures in other languages as well, and is a typical encoding error. I found this issue and guess the error results from these changes: https://github.com/AlanOC91/YGOPRODeck/issues/332

My script also detect changes of the (german) card effect, but I couldn't find any real change by looking at it (I guess there are some invisible characters that changed as well). But simply to inform that the card effect could also contains bugs: 
-card effect changed:
Rüste nur ein „Gusto“-Monster mit dieser Karte aus. Das ausgerüstete Monster kann nicht durch Karteneffekte deines Gegners zerstört werden. Du kannst jeden der folgenden Effekte von „Rückenwind von Gusto“ nur einmal pro Spielzug verwenden. Du kannst diese Karte von deinem Friedhof verbannen und 1 WIND Monster abwerfen; füge deiner Hand 1 „Gusto“-Zauber/Falle von deinem Deck hinzu. Du kannst diesen Effekt aktivieren, basierend auf der Stufe / dem Rang des ausgerüsteten Monsters;

● 4 oder niedriger: Beschwöre 1 „Gusto“-Monster mit einem unterschiedlichen Typ als das ausgerüstete Monster als Spezialbeschwörung von deinem Deck.

● 5 oder höher: Beschwöre 1 Empfänger der Stufe 1 als Spezialbeschwörung von deinem Deck.

->
Rüste nur ein „Gusto“-Monster mit dieser Karte aus. Das ausgerüstete Monster kann nicht durch Karteneffekte deines Gegners zerstört werden. Du kannst jeden der folgenden Effekte von „Rückenwind von Gusto“ nur einmal pro Spielzug verwenden. Du kannst diese Karte von deinem Friedhof verbannen und 1 WIND Monster abwerfen; füge deiner Hand 1 „Gusto“-Zauber/Falle von deinem Deck hinzu. Du kannst diesen Effekt aktivieren, basierend auf der Stufe / dem Rang des ausgerüsteten Monsters;

● 4 oder niedriger: Beschwöre 1 „Gusto“-Monster mit einem unterschiedlichen Typ als das ausgerüstete Monster als Spezialbeschwörung von deinem Deck.

● 5 oder höher: Beschwöre 1 Empfänger der Stufe 1 als Spezialbeschwörung von deinem Deck.

When I ask the API simply for this one specific card, the error still exists, so it's an global bug, and not only an endpoint error: 
https://db.ygoprodeck.com/api/v7/cardinfo.php?language=de&fname=kenwind%20von%20Gusto

**Comment by AlanOC91** [comment]
This was due to a recent update in our card language scripts. Specifically:

`$de_name = filter_var($de_name, FILTER_UNSAFE_RAW, FILTER_FLAG_STRIP_LOW|FILTER_FLAG_STRIP_HIGH);`

And within that: `FILTER_FLAG_STRIP_HIGH` which is causing the issue. 

`FILTER_FLAG_STRIP_LOW` should be used in this case but `FILTER_FLAG_STRIP_HIGH` is stripping out non-ASCII such as umlauts.

For now updating to this should work:

`$de_name = filter_var($de_name, FILTER_UNSAFE_RAW, FILTER_FLAG_STRIP_LOW);`

Will re-run my script soon.

**Comment by AlanOC91** [comment]
Script re-ran. Issue should be fixed.

**Comment by necrodraco** [comment]
@AlanOC91 
are you sure it's fixed? 
I've now waiting more then 24h to secure that there isn't anything cached anymore, but I still find card names with missing umlauts (e.g. the link in the issue description). Card Effects doesn't contain the failure, but all the card names.

**Comment by AlanOC91** [comment]
Mistake on my end, should be fixed and live soon
