### ISSUE TITLE
No Card type image for ritual pendulum monsters

### ISSUE THREAD

**Issue by AexDEye9** [AlanOC91/YGOPRODeck#344]
![image](https://user-images.githubusercontent.com/61853861/143523549-9d155db3-070f-43ca-a6e7-ab2514067247.png)

**Comment by AexDEye9** [comment]
ALSO: Odd-eyes pendulumgraph dragon excluded from published decks
![image](https://user-images.githubusercontent.com/61853861/143523789-28aa3b7a-730c-41ad-a8ac-28f764b44dc0.png)

**Comment by AlanOC91** [comment]
Good catch about the deck, I thought I had it updated already.

Fixed both issues. Unfortunately, decks without the card will need to be re-edited by the user.
