### ISSUE TITLE
Erro. 500 when reach API with fr / de / it language.

### ISSUE THREAD

**Issue by Nhaakq** [AlanOC91/YGOPRODeck#345]
Hello,

Thanks for your work, it's amazing.

I  get an error 500 when I try to reach the API with specific language.

URL from doc : 
https://db.ygoprodeck.com/api/v7/cardinfo.php?name=Survie%20du%20Plus%20Fort&language=fr

Same for 'fr', 'de', 'it' or 'pt'.

NK_

**Comment by AlanOC91** [comment]
Fixed now!
