### ISSUE TITLE
Boxes missing from the Duel Links pack opener

### ISSUE THREAD

**Issue by davidehj** [AlanOC91/YGOPRODeck#347]
I commented this below the post announcing the DL pack opener, but I'm not sure if that's the right place to do so, so I'm also posting it here, will delete if needed

Hi.
We're missing the first minibox for Duel Links, Age of Discovery.
I've also found some other things. We're missing Abyss Encounters. Instead there is a so called "New pack" where it should be, with cards that are not from Abyss Encounters, so this isn't a name mistake.
Absolute Inferno is missing.
Aerial Assault is missing.
I haven't checked Structure Decks so no information there.

**Comment by AlanOC91** [comment]
These are being actively added at the moment and should all be available in about 20 minutes or so.

**Comment by AlanOC91** [comment]
These should be added now!
