### ISSUE TITLE
Suggestion: Custom Packs: Editing

### ISSUE THREAD

**Issue by AexDEye9** [AlanOC91/YGOPRODeck#352]
I'd like to see people have the ability to edit their existing custom packs, via https://db.ygoprodeck.com/saved-packs/ in some way.

**Comment by AlanOC91** [comment]
Yeah, editing is something I purposely left out for the moment until I can figure a good solution out for it.

My reasoning: 

User 1 creates custom pack.
User 1,2,3,4 are using this custom pack to open drafts.
In the middle of opening drafts, user 1 purposely edits the deck contents. User 2,3,4 are now suddenly opening different cards.

I can see a LOT of ways user can abuse this system so I need to figure out a more elegant solution.

**Comment by AexDEye9** [comment]
I understand that, i've got one idea for it though:

- Display the release date/time below the pack, and inside the pack view, and also it's most recent update date/time (if on the pack cover, prioritize showing most recent update date/time, in pack view display both.

In addition to this suggestion, i'd like to see the ability to sort packs by "Most recently updated", to go along with it.

**Comment by AlanOC91** [comment]
Done with the YGOPRODeck overhaul which should be live ~tomorrow
