### ISSUE TITLE
Some alternates cards not in database

### ISSUE THREAD

**Issue by GB127** [AlanOC91/YGOPRODeck#354]
So I'm using the api to retrieve all the IDs of the cards, and came across, when comparing with project ignis, some cards that aren't in your database.

For example, mystic tomato seems to have an alternate art (so a different card ID) that is not in your code apparently.

Here are the cards IDs I recensed:

64335804
81480460
83011277
84080938
56043446
39751093
82044279
18144506
73134081
62219643
36114945
33331231
83764718
84257639
19230407
34293667
35686187
68540058
18807108
80604091

From memory, here are some of the cards:
Ultimate offering
Monster Reborn
Red eyes black metal dragon
Mystic Tomato

**Comment by GB127** [comment]
Note that the cards IDs are one digit off. For example, for 64335804, the code in your database is either 64335805 or 64335803.

**Comment by AlanOC91** [comment]
Hi there,

We do have many alternative arts.

Example: https://db.ygoprodeck.com/card/?search=83011277

When searching by name, it will also show alternative arts below: https://db.ygoprodeck.com/card/?search=Mystic%20Tomato

I believe you are calling the API where the results are grouped together. 

Take: https://db.ygoprodeck.com/api/v7/cardinfo.php?name=Mystic%20Tomato

![Screenshot 2022-01-13 094652](https://user-images.githubusercontent.com/37552458/149306190-cb75ae3c-6c3f-43ae-b5f2-4674bc5c4791.png)

**Comment by GB127** [comment]
Hih I did not know they were there. Thank you for the reply I will investigate eventually on my side.

Sorry.
