### ISSUE TITLE
How do I know if a card has been updated?

### ISSUE THREAD

**Issue by lucasbsrs** [AlanOC91/YGOPRODeck#355]
There is the endpoint that returns the db version: https://db.ygoprodeck.com/api/v7/checkDBVer.php

But how do I know which card has been updated?

**Comment by AlanOC91** [comment]
We don't have a lot of good data for this at the moment but we do have changelogs that can be viewed: 

https://db.ygoprodeck.com/api/v7/changelogDesc.php
https://db.ygoprodeck.com/api/v7/changelogID.php
https://db.ygoprodeck.com/api/v7/changelogName.php

These currently aren't shown on our API page. We'll make an announcement in the future should we release more thorough changelog information.
