### ISSUE TITLE
Lubellion the Searing Dragon has two card image ID's that are the same

### ISSUE THREAD

**Issue by TheEclipsedLock** [AlanOC91/YGOPRODeck#356]
https://db.ygoprodeck.com/api/v7/cardinfo.php?fname=Lubellion

The JSON information will return:

"card_images": [
                {
                    "id": 70534340,
                    "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/70534340.jpg",
                    "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/70534340.jpg"
                },
                {
                    "id": 70534340,
                    "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/70534340.jpg",
                    "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/70534340.jpg"
                }
            ],

However, they are the exact same id.

**Comment by AlanOC91** [comment]
Fixed
