### ISSUE TITLE
Metalfoes effect monsters marked normal

### ISSUE THREAD

**Issue by aDudman** [AlanOC91/YGOPRODeck#365]
The monsters [Metalfoes Vanisher](https://db.ygoprodeck.com/card/?search=Metalfoes%20Vanisher) and [Parametalfoes Melcaster](https://db.ygoprodeck.com/card/?search=Parametalfoes%20Melcaster) are listed in the database as "Pendulum Normal Monster", but they are actually Pendulum Effect Monsters.

**Comment by AlanOC91** [comment]
Good catch! These are fixed now.
