### ISSUE TITLE
Certain values for Monster Card "Race" not stated in API Documentation

### ISSUE THREAD

**Issue by joseph-bravo** [AlanOC91/YGOPRODeck#369]
Within the **Endpoint Information** section of the YGO API Guide,  the values `"Wyrm"` and `"Zombie"` are missing from the possible Monster Race values, despite actually being available for query. Just a small typo, but figured I'd point it out! :)

---

### Endpoint Information section as of now

<img width="212" alt="image" src="https://user-images.githubusercontent.com/78003700/164112646-42762829-3fb6-475f-9f16-174c3405c402.png">

**Comment by AlanOC91** [comment]
Thanks! Fixed!
