### ISSUE TITLE
Use GraphQL instead of REST

### ISSUE THREAD

**Issue by DrewGuillien** [AlanOC91/YGOPRODeck#375]
GraphQL (https://graphql.org/) (https://webonyx.github.io/graphql-php/) is a new emerging technology that allows consumers of an API determine how much data they want returned from any request.  Making a query to the REST API will return a lot of card information that I did not want and will not use. Using GraphQL would reduce the payload of each request to the API. I was looking to consume this API but I am only interested in a cards id, name, and set names. With GraphQL I could request exactly what I needed:

```
cards {
    id
    name
    sets {
        name
    }
}
```

I also believe that crafting complicated search queries would be easier with a GraphQL query than it would be to create a REST url with all of the search parameters in it. A GraphQL endpoint could be created along side your REST endpoints and call the same database functions and only do the work of reducing what is returned in order to be worth the effort.

**Comment by AlanOC91** [comment]
While I can indeed see the advantages of GraphQL and how our API users can benefit from it I just don't see it being worth the current time investment necessary at the moment. 

We are unfortunately at a position where projects like this need to be seriously looked at based on time-scale and how necessary the project actually is. Considering our REST API is working perfectly fine for our many API users I would consider this low priority and thus doesn't warrant action at this very moment.

You may not know, but I also run pokemoncard.io, digimoncard.io, rushcard.io and vanguardcard.io along with a couple of others (and working a full time job alongside these!). This stretches me thin for the most part which pushes projects like this aside.

I will never say never and it is absolutely something I would like to look into for the future but at this moment it won't be happening anytime soon.
