### ISSUE TITLE
Suggestion: Search A Specific Decklist, More Sort Options

### ISSUE THREAD

**Issue by NARFNra** [AlanOC91/YGOPRODeck#376]
So the idea for this one comes from when people download collections or large draft sets and then check them out on another computer, or from someone else's account. You can search through a collection no problem, but it's impossible to convert a YDK to a collection easily due to the lack of information contained in them. Yet this problem comes up a lot, especially with people doing multiple Progression series.

I think it'd be useful if the Deckbuilder feature had a checkbox that let you specifically look through an imported ydk, like if you have 1800 cards to choose from from multiple sets. I also think it'd be neat if the sorting tools used to search through your collection could be applied to the deck sort as well - something as simple as sorting all cards by ATK, DEF, or alphabetically, would be a great way to find things and get a quick look at archetypes in your pool and stuff.

Thank you again for all your hard work!

**Comment by AlanOC91** [comment]
Hello,

I'm not fully following what you are requesting for "search specific decklist". Can you please go into more detail on what exactly it is you are looking for?

When you ask for the deck builder to look at a .ydk I'm not sure I get what you mean? The deck builder can already import .ydk decks and view them fully.

**Comment by NARFNra** [comment]
I would really appreciate if there was some way to search through the cards contained in a large .ydk file the same way we can search our collection. If there was a way to import ydks into the collection that would solve this problem, but I saw another issue on here where you explained that that wasn't possible because the files don't contain enough information. Still, it does sometimes become an issue.

I'm running into this problem from helping people with their progression series. Some creators will post their combined pulls from many sets as giant .ydk files, and ask for people for help determining what decks they can build. But these end up as very large files that are very difficult to look through by hand.

![image](https://user-images.githubusercontent.com/7265358/165906222-1fff5b62-45c9-4e65-a812-a20181ebc871.png)

Suppose I wanted to find out whether I had enough cards to play Blackwings in a file like this. Unfortunately, I don't have any way to search this deck - I cannot find how many Blackwing cards I have unless I scroll through and find them individually. And even if I know to look for Armed Blackwing cards, I might miss cards that don't refer to BWs but work well with them like DARK support and Winged-Beast support.

If I had this file in my collection, it'd be really easy to look for these things - I could just go into filter cards and use my collection and search "Blackwing", "Winged Beast", "DARK", and so forth. But I can't do that with a .ydk, and I can't add a .ydk to my collection to use those features either. So I can end up with a bunch of saved .ydks from prog openings that are extremely hard to get information from unless I go through one at a time and verify things myself.

So it would be something like the "use user collection" button, but in that it only shows you cards already in the deck. This might seem weird, but it even has applications for normal deck-building - suppose you want to add one more of a few cards you already have. You could toggle the button and the filter cards panel would immediately show you cards you already had, and you could quickly add a few more copies in. I could see reasons this might be helpful.

The last thing I was mentioning was the idea of having multiple ways to sort the decklist. The current sorting is good, but sometimes it's not the best way to find what you want out of a deck. Sorting alphabetically by name could help you find archetypes, for instance. I think that this would be a lot less trouble to implement than the searching would be, and you could base it on the way filter cards already works - letting us sort the cards in the deck by ATK, or DEF, or date, and so forth. I think this could be useful to everyone.

Does that make sense? I'm sorry if it seems like a strange or troublesome suggestion.

**Comment by AlanOC91** [comment]
Hi there, yes that makes sense now.

However, it would require extensive rework to our deck builder so I am unsure if this is the way forward.

I think instead, I may add a import .ydk file into the collection manager.

Since .ydks are missing information, it would have to work like so:

- Read each line of .ydk
- Get card information from database, do database joins to find the first matched information for the card (regardless of what card set it is, since we don't know)
- Price can be got from above
- Set default edition/condition

The data would technically be inaccurate but I don't think people who do prog series cares too much about the misc collection data.

I think this would potentially be a better method.

**Comment by NARFNra** [comment]
I think that importing a .ydk would solve my issues very well, I definitely agree. It would be tricky and lack accuracy, but it would make things a lot simpler for people in my situation. I would definitely appreciate that!

**Comment by AlanOC91** [comment]
Working on it at the moment! I should have it done today all going well and no issues arising.

**Comment by AlanOC91** [comment]
This is now live. Button is next to the "Import Collection" button. 

![Screenshot 2022-04-29 120043](https://user-images.githubusercontent.com/37552458/165932358-ab8cc2aa-b147-44b7-8137-b58635e07701.png)
