### ISSUE TITLE
Releases in cardset endpoint are missing a date

### ISSUE THREAD

**Issue by Larikk** [AlanOC91/YGOPRODeck#377]
The following releases in the cardset endpoint have no date:

* OTS Tournament Pack 18 (POR): Should be 2022-02-17 like the other versions of OTS 18
* Speel Duel Tournament Pack 2: Should be 2019-10-10
* The Lost Art Promotion 2021 K: Should be 2021-12-01

**Comment by AlanOC91** [comment]
Hey there,

I've fixed the "OTS Tournament Pack 18 (POR)". However. the other ones already have those dates associated. Can you let me know exactly what endpoint you are using?

Thanks!

**Comment by Larikk** [comment]
Oh, my bad. My script had an of-by-one error. I noticed that yesterday but missed to fix the text in my issue.

* Speed Duel Tournament Pack 3: Should be 2022-03-24 or 30. It has a later release for NA
* The Lost Art Promotion 2021 L: Should be 2021-12-01

Endpoint is just https://db.ygoprodeck.com/api/v7/cardsets.php

**Comment by AlanOC91** [comment]
Thank you! Data added. Will show when cache clears in a few hours.
