### ISSUE TITLE
Suggestion: Spirit Sculptor Search Tool (Attack + Defense Total comparison between cards) 

### ISSUE THREAD

**Issue by Ikeypoo** [AlanOC91/YGOPRODeck#382]
Spirit Sculptor allows you to search monsters by tributing a monster then adding one from your deck to your hand with the same TOTAL Attack + Defense of the monster. Can you create a tool to let players type in a stat total then it searches the database?

If it's computationally heavy, perhaps the card data structure could be expanded, or a script could be ran to assign card I.D. links a stat total then pull from the regular API when you want to actually look at the card? This card has a lot of potential for competitive, like Small World, which has a tool devoted to allowing players to explore it. This card deserves one too.

I feel this would improve the website by virtue of doing something no one else has ever done before. Thanks for your time.

**Comment by AlanOC91** [comment]
![Spirit](https://user-images.githubusercontent.com/37552458/171812490-27739377-3778-4ef1-b9dc-d1829f82aa91.gif)

This is done now:
https://db.ygoprodeck.com/spirit-sculpt-tool/
