### ISSUE TITLE
BUG: Lonefire Blossom Is Not Listed as "Semi-Limited" in OCG

### ISSUE THREAD

**Issue by StupidStudiosN** [AlanOC91/YGOPRODeck#386]
Recently noticed that the banlist information for _Lonefire Blossom_ was cut from the database, despite being Semi-Limited in the OCG.
https://db.ygoprodeck.com/api/v7/cardinfo.php?name=Lonefire%20Blossom

**Comment by AlanOC91** [comment]
Fixed. Will update cache soon.
