### ISSUE TITLE
Mislabeled Pendulums

### ISSUE THREAD

**Issue by CDGCodes** [AlanOC91/YGOPRODeck#388]
There are a lot of Pendulum Monsters who aren't properly labeled
Most of them are Extra Deck Monsters, but also one of the Normal Monsters, Magicalibra, is labeled as an Effect Monster while it's actually a Normal Tuner (I couldn't find anything else that was an issue in the Main Deck, even Pendulumgraph is labeled correctly despite Pendulum Ritual not being a valid search tag in the database)

As for the Extra Deck Monsters I could find, I have:
D/D/D Deviser King Deux Machinex
Parametalfoes Azortless
Patissciel Couverture
Starving Venemy Dragon
Symphonic Warrior Rockks
Valiants Assemble - Mamonaka
Valiants' Genesis - Granduke

None of the Extra Deck Monsters listed above are labeled as Pendulum Monsters in the database (although they all have scales, and their descriptions do all contain "[ Pendulum Effect ]", so it's possible to parse out, but it's still a hassle)

**Comment by AlanOC91** [comment]
Thanks! The cards listed have been fixed. We currently don't have a "Pendulum Normal Tuner Monster" typing so I've changed Magicalibra to Pendulum Normal Monster for now.

These changes will update when our cache clears in a couple of hours. Thank you!
