### ISSUE TITLE
Adventurer Token cards

### ISSUE THREAD

**Issue by laaners** [AlanOC91/YGOPRODeck#391]
Many cards of the "Adventurer Token" archetype are still labelled as "Brave Token":

Breath of Resurrection
Dracoback, the Rideable Dragon
Dunnell, the Noble Arms of Light
Fateful Adventure
Forest of Lost Flowers
Illegal Knight
Magicore Warrior of the Relics
Rite of Aramesir
Water Enchantress of the Temple
Zaralaam the Dark Palace
Starlit Papillon
Thunder Discharge
Wandering Gryphon Rider

The same problem can be found in the descriptions, some of them still mention "Brave Token" in the effect:

Starlit Papillon
Thunder Discharge
Wandering Gryphon Rider

**Comment by AlanOC91** [comment]
Fixed! It will reflect on the site/API when the cache updates.
