### ISSUE TITLE
Several Rush cards missing from API

### ISSUE THREAD

**Issue by smith-ross** [AlanOC91/YGOPRODeck#397]
Lots of Rush cards, including every monster with the Galaxy type, currently appear to be missing from the API. On top of this, a lot of cards are not correctly formatted with [REQUIREMENT] [EFFECT] and instead only state the effect.

**Comment by AlanOC91** [comment]
Hi there,

Rush Cards are going to be deprecated and eventually removed from the API. All of our Rush Content has moved over to rushcard.io.

A Rush Duel specific API will be released soon (once the YGOPRODeck overhaul is completed).
