### ISSUE TITLE
Incorrect sorting order for Card Sets page

### ISSUE THREAD

**Issue by metallicity** [AlanOC91/YGOPRODeck#400]
The [Card Sets page](https://ygoprodeck.com/packs/) sorts sets by release date, descending by default. But the data it uses to sort these items is malformed in some instances, with "\r\n" control characters appended to the end of the date. This is likely causing the dates to be mis-parsed, as all sets with this issue appear at the front of the list.

Looking at last year's "Lost Art" sets, the sets appearing on the first page match exactly to the sets which have these stray characters:

```json
[
  { "set_name": "The Lost Art Promotion 2021 L", "set_code": "LART", "num_of_cards": 1, "tcg_date": "2021-12-01" },
  { "set_name": "The Lost Art Promotion 2021 K", "set_code": "LART", "num_of_cards": 1, "tcg_date": "2021-11-01" },
  { "set_name": "The Lost Art Promotion 2021 J", "set_code": "LART", "num_of_cards": 1, "tcg_date": "2021-10-01\r\n" },
  { "set_name": "The Lost Art Promotion 2021 I", "set_code": "LART", "num_of_cards": 1, "tcg_date": "2021-09-01" },
  { "set_name": "The Lost Art Promotion 2021 H", "set_code": "LART", "num_of_cards": 1, "tcg_date": "2021-08-01" },
  { "set_name": "The Lost Art Promotion 2021 G", "set_code": "LART", "num_of_cards": 1, "tcg_date": "2021-07-01\r\n" },
  { "set_name": "The Lost Art Promotion 2021 F", "set_code": "LART", "num_of_cards": 1, "tcg_date": "2021-07-01" },
  { "set_name": "The Lost Art Promotion 2021 E", "set_code": "LART", "num_of_cards": 1, "tcg_date": "2021-05-05\r\n" },
  { "set_name": "The Lost Art Promotion 2021 D", "set_code": "LART", "num_of_cards": 1, "tcg_date": "2021-04-07\r\n" },
  { "set_name": "The Lost Art Promotion 2021 C", "set_code": "LART", "num_of_cards": 1, "tcg_date": "2021-03-15\r\n" },
  { "set_name": "The Lost Art Promotion 2021 B", "set_code": "LART", "num_of_cards": 1, "tcg_date": "2021-02-19\r\n" },
  { "set_name": "The Lost Art Promotion 2021 A", "set_code": "LART", "num_of_cards": 1, "tcg_date": "2021-01-01" },
]
```

## First page of sets list, core boosters and many other sets seem to be missing

![sets_page_1](https://user-images.githubusercontent.com/15206291/189494615-c51de2cd-094b-4406-a6c4-1f26d1519f9c.png)

## Fourth page of sets list, missing sets start to reappear here

![sets_page_4](https://user-images.githubusercontent.com/15206291/189494618-ae5e5b78-4ee8-492a-8ded-1978353b7e24.png)

**Comment by AlanOC91** [comment]
Rolled out a fix for this! Should be live on both the API and site when our caching clears soon.
