### ISSUE TITLE
Deck Brew Broken Table

### ISSUE THREAD

**Issue by trim345** [AlanOC91/YGOPRODeck#409]
I tried out the Deck Brew. Upon doing so, I received the following error.

DataTables warning: table id=myTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7

I backed up my collection, deleted it, and tried a toy case that was just 1 copy of every card from Legend of Blue Eyes White Dragon. This seemed to work. I tried 3 copies of LOB, which also worked fine. Adding every card from Metal Raiders worked as well. However, when I added every card from Spell Ruler, the error popped up again, and it was the same for adding more cards.

**Comment by AlanOC91** [comment]
It seems to have been hitting it's maximum execution time on the script. I'll roll out a fix for this!

**Comment by AlanOC91** [comment]
This is now resolved! However, there is some work to do with memory optimizations for the script. Will need to look into some solutions for potentially very large collections.
