### ISSUE TITLE
Deck Brew Multiple Copies

### ISSUE THREAD

**Issue by trim345** [AlanOC91/YGOPRODeck#410]
It seems that if you have 3 copies of a card, Deck Brew only understands it as one. For example, if your collection includes 3 Blue-Eyes White Dragons, and a matching deck requires 3 copies of Blue-Eyes, Deck Brew shows you as missing two copies, which messes up the match rate a lot.

I backed up my collection, then deleted it and added 3 copies of every card in LOB so those were the only cards in my collection. Many decks that should have had a 100% match rate instead were much lower, because, for example, if the deck required 3 copies of Man-Eater Bug, it would show that you were missing 2 copies.

Please allow the Deck Brew to read the number of copies of a card you have and take those into account when matching similar decks.

**Comment by AlanOC91** [comment]
Hey there! I found a pretty poor bug in the match implementation that I have since resolved on our dev site. It'll be rolled out to production today!

**Comment by AlanOC91** [comment]
This is now resolved! Thank you for bringing this to my attention.

![match rate](https://user-images.githubusercontent.com/37552458/192735132-5d1f7a6e-ce60-467e-a1ec-63acd42bd551.png)

![matched cards](https://user-images.githubusercontent.com/37552458/192735171-ebe03ac0-2fea-43ed-baba-8483f1d37865.png)
