### ISSUE TITLE
Incorrect Deck brew matching. Does not match extra deck

### ISSUE THREAD

**Issue by dandelea** [AlanOC91/YGOPRODeck#412]
It seems like the deck brew does not take in consideration the extra deck cards for matching the decks. A deck appears in my brew listing as 100% but I don't have the full extra deck. The actual matching is enough for my use of the tool, but not perfect.

**Comment by AlanOC91** [comment]
Extra Deck has now been added to the Deck Brew and considered into the match calculation %
