### ISSUE TITLE
API missing Darkwing Blast TCG exclusives & more

### ISSUE THREAD

**Issue by snow-skateer** [AlanOC91/YGOPRODeck#416]
All of the DABL exclusives (except Daruma Cannon, weirdly) are not present in the API, along with several newly revealed cards, despite cards from the same reveal being present. I've produced a list:

- Bayerock Dragon
- Zalamander Catalyzer
- Tilting Entrainment
- Zep, Ruby of the Ghoti
- Ixeep, Omen of the Ghoti
- Snopios, Shade of the Ghoti
- Arionpos, Serpent of the Ghoti
- Guoglim, Spear of the Ghoti
- Ghoti Cosmos
- Ghoti Fury
- Assault Synchron
- Dark Magician the Magical Knight of Dragons
- Traptrix Atypus
- Traptrix Pinguicula
- Beetle Amalgamaton Zekstagger
- Spellbound

**Comment by AlanOC91** [comment]
This should be resolved now.
