### ISSUE TITLE
Wrong ids on some cards

### ISSUE THREAD

**Issue by SantiagoRivera92** [AlanOC91/YGOPRODeck#419]
Some cards (newer TCG exclusives) are returning 9 digit codes that aren't correct

> Arionpos, Serpent of the Ghoti
> Bayerock Dragon
> Destructive Daruma Karma Cannon
> Ghoti Cosmos
> Ghoti Fury
> Guoglim, Spear of the Ghoti
> Ixeep, Omen of the Ghoti
> Pendulum Scale
> Snopios, Shade of the Ghoti
> Spellbound
> The Breaking Ruin God
> The Revived Sky God
> The True Sun God
> Tilting Entrainment
> Zalamander Catalyzer
> Zep, Ruby of the Ghoti

**Comment by AlanOC91** [comment]
This should be resolved now. We had an issue where our Beta IDs weren't updating to the Official Released IDs.
