### ISSUE TITLE
Clicking on cards in the Cube Builder doesn't visually remove them from the cube.

### ISSUE THREAD

**Issue by SantiagoRivera92** [AlanOC91/YGOPRODeck#421]
The cards themselves are gone and if you save the cube and reload it, they disappear, but until you do that, they still apear in the cube and can be clicked to remove them again, which decreases the card count by 1. I'm unsure of what clicking the card multiple times does, but this is likely not intended behavior.

**Comment by AlanOC91** [comment]
I'm struggling to replicate this bug.

Can I get some more information?

- Web Browser
- Steps to reproduce (did you import via ydk, csv, add them via search, etc etc)
- Does it happen every card in the cube?

**Comment by SantiagoRivera92** [comment]
It's apparently no longer happening, I can't reproduce it again.

I use Opera. I was just adding cards manually via search, and it happened with every card in the cube, but I can't reproduce it now.

**Comment by AlanOC91** [comment]
Closing for now but feel free to re-open if you come across it again
