### ISSUE TITLE
[CardsCropped] No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by kooriookami** [AlanOC91/YGOPRODeck#423]
Hello, when I want to get card cropped image and use url `https://images.ygoprodeck.com/images/cards_cropped/${id}.jpg`, it occurred an error.
```
Access to image at 'https://images.ygoprodeck.com/images/cards_cropped/xxx.jpg' from origin 'xxx' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
The url `https://storage.googleapis.com/ygoprodeck.com/pics_artgame` worked well before, but it's not working anymore, could you resolve this problem?

**Comment by AlanOC91** [comment]
Hello, 

The Google storage has been shut down as it's been costing us upwards of $1k/month because people refuse to download and are just hotlinking.

Regarding images from our image server, as per the API they are supposed to be downloaded and self-hosted.

**Comment by kooriookami** [comment]
> 

I do understand your situation, If I can pay to use CardsCropped, I will provide support. :D

**Comment by AlanOC91** [comment]
Heya!

You can use them but they must be downloaded and self-hosted. You have complete access to download them via URL. For example: https://images.ygoprodeck.com/images/cards_cropped/34541863.jpg

**Comment by kooriookami** [comment]
> 

Yes, I can download the pic. Is there any way to use the url in website. Or can I only save the image locally

**Comment by The0mbudsman** [comment]
Downloading and hosting the images yourself will ease the strain on ygoprodeck servers and also might make your site load faster, it's win win

**Comment by kooriookami** [comment]
> Downloading and hosting the images yourself will ease the strain on ygoprodeck servers and also might make your site load faster, it's win win

Thank you for answering my questions. I will clse this issue~
