### ISSUE TITLE
Issues in newest core sets

### ISSUE THREAD

**Issue by Larikk** [AlanOC91/YGOPRODeck#431]
## Battle of Chaos (BACH)

Dark Magician as Ultra Rare is missing
Master Of Chaos should only be an Ultra Rare, not a Starlight Rare (and the Ultra Rare printing is missing on the site; The API has both)

## Darkwing Blast (DABL)

Baku the Beast Ninja
Blackwing - Chinook the Snow Blast
Blackwing - Shamal the Sandstorm
Blackwing - Vata the Emblem of Wandering
Bystial Saronir

All of those are listed as Common in addition to their correct rarity. The web site only display the Common one while the API has both.

**Comment by AlanOC91** [comment]
Fixed! Thanks for the report!
