### ISSUE TITLE
Incorrect OCG Ban List

### ISSUE THREAD

**Issue by truedr4co** [AlanOC91/YGOPRODeck#434]
For the OCG format January 1 2023 Ban List

should be BANNED:
Number S0: Utopic Zexal (Currently appears as UNLIMITED)

should be LIMITED:
Girsu, The Orcust Mekk-Knight (Currently appears as UNLIMITED)
One for One (Currently appears as SEMI-LIMITED)

should be SEMI-LIMITED:
Called by the Grave (Currently appears as UNLIMITED)

should be UNLIMITED: 
Lonefire Blossom (Currently appears as SEMI-LIMITED)

referenced against 
https://www.yugioh-card.com/japan/event/rankingduel/limitregulation/?list=202301

(and out of curiosity)
https://cardcluster.com/limited-list/ocg

**Comment by AlanOC91** [comment]
Thanks for the report! These are fixed now!
