### ISSUE TITLE
missing cropped image

### ISSUE THREAD

**Issue by joseehilton147** [AlanOC91/YGOPRODeck#436]
this card give's 404 when click on cropped image.

https://ygoprodeck.com/card/armed-and-ready-13213

**Comment by The0mbudsman** [comment]
There are many where the cropped image isnt available yet, usually new OCG releases, eg: https://ygoprodeck.com/card/despian-luluwalilith-13690

There's no manifest available in the API, and no entries to indicate whether images exist, so your best option is to query the cropped image endpoint and check if the response contains a valid image.

**Comment by joseehilton147** [comment]
yep, im doing this, im uploading cropped images to a cdn to release the API request and saving a status sucess or error when cropped isnt available.
