### ISSUE TITLE
Syntax error on 'image_url_croppped' key name

### ISSUE THREAD

**Issue by ghost** [AlanOC91/YGOPRODeck#437]
I've noticed that the key name in image_url json have a inconsistency.
Example:

![image](https://user-images.githubusercontent.com/42438976/210618514-0e314c45-e1b5-4d38-a8b8-75ecfcfdd571.png)

In the key is is written `croppped` while in in the url is written `cropped`

**Comment by AlanOC91** [comment]
Thanks! Should be fixed now
