### ISSUE TITLE
Incorrect lflist being generated after collection update

### ISSUE THREAD

**Issue by BurgerBurgman** [AlanOC91/YGOPRODeck#441]
Previously, using the lflist feature created a banlist based on the current collection selected.

However, after the update, using the lflist feature generates an incomplete lflist based on the collection.

These two issues primarily appear.

Many cards, despite being in the collection, are not displayed while viewing the collection. These cards are not included in the lflist, but do appear when searched.

Cards of different editions were, prior to the update, considered the same card for the purpose of the lflist (ie, 1 first edition and 2 unlimited would have the card at unlimited). Now, the lflist seems to decide at random which (generating a banlist from 1 first edition and 2 unlimited resulted in the card being semi-limited)

Steps to reproduce:
1) Create a collection containing a large amount of cards (currently tested with 24 packs of 5 sets)
2) Select the collection and generate lflist.conf
3) Import the lflist to be used; (tested by via EDOPRO)

Expected behaviour:
The lflist contains all of the cards within the collection.

Actual behaviour:
The lflist contains an incomplete selection of cards within the collection, semi-controllable by the search function and sort options.

**Comment by AlanOC91** [comment]
This should be resolved now. It will pull all the cards (of the box/unassigned pile you are currently viewing) regardless of filters and will correctly group them again.

Can you please re-open the issue if you find an issue still occurs with it.

**Comment by BurgerBurgman** [comment]
Thank you! This is a big help for my pals as we're pretty reliant on this feature. I can confirm that it pulls all cards out of the box, including the ones not currently displayed.

However, it still appears that duplicate cards (ie, first edition and unlimited, possibly of different sets but I have not tested that) do not count towards the same banlist. As seen, I have 3 hydrogeddon in the collection

![image](https://user-images.githubusercontent.com/122132950/211162911-193efc8d-28b5-48b6-b9b6-992aec8a3acf.png)

However, when generating a banlist of solely the searched Hydrogeddon, it only considers one seemingly at random (the previous lflist was 2x hydrogeddon).

![image](https://user-images.githubusercontent.com/122132950/211162957-845fa1a8-066b-4eb9-9e77-649c59326c60.png)

Also excuse my ineptitude as I'm trying to figure out how to reopen an issue (first time using github to report a bug).
