### ISSUE TITLE
Lflist not considering different editions as the same card

### ISSUE THREAD

**Issue by BurgerBurgman** [AlanOC91/YGOPRODeck#442]
Sorry for making a new issue for this. I just can't seem to find how to re-open an issue, whether I don't have permission, I'm just straight blind, or some third thing (from what I've seen, it should be right beside post, but it's not there for me; not very important).

Thank you for helping with this issue.

It still appears that duplicate cards (ie, first edition and unlimited, possibly of different sets but I have not tested that) do not count towards the same banlist. As seen, I have 3 hydrogeddon in the collection

![image](https://user-images.githubusercontent.com/122132950/211162911-193efc8d-28b5-48b6-b9b6-992aec8a3acf.png)

However, when generating a banlist of solely the searched Hydrogeddon, it only considers one seemingly at random (the previous lflist generated was 2x Hydrogeddon).

![image](https://user-images.githubusercontent.com/122132950/211162957-845fa1a8-066b-4eb9-9e77-649c59326c60.png)

Also excuse my ineptitude as I'm trying to figure out how to reopen an issue (first time using github to report a bug).

_Originally posted by @BurgerBurgman in https://github.com/AlanOC91/YGOPRODeck/issues/441#issuecomment-1374545231_

**Comment by AlanOC91** [comment]
I'm struggling to replicate this. I have 2 Dark Energies in my Collection and it's correctly grouping them:

![denergy](https://user-images.githubusercontent.com/37552458/211167755-f913d434-0039-4098-aba0-3335c41d4f1c.jpg)

The output:

![denergy2](https://user-images.githubusercontent.com/37552458/211167760-82ecf1cc-f575-4b7c-aaee-ffaf1a822610.jpg)

Can you shoot me your site name and I make sure the cards in your collection are stored with the same ID (they should be). The query that is ran groups them by IDs so they should absolutely be grouped together.

**Comment by AlanOC91** [comment]
Just speaking to another user and I think you are still using the old update.
To fix it, either press ctrl + f5 on the collection page to force an update or go to your profile, preferences and hit "delete cache". 

Hopefully, that will fix it!

**Comment by AlanOC91** [comment]
I belive this is fixed now!
