### ISSUE TITLE
"C" Archetype only contains 1 Card

### ISSUE THREAD

**Issue by Haembina** [AlanOC91/YGOPRODeck#449]
the "C" Archetype only contains the most recent card in the archetype, Hiding "C" or Sneaky "C" the older cards in this archetype like Maxx "C" for example, don't have an archetype in the Database yet.

**Comment by AlanOC91** [comment]
Yeah I noticed this yesterday when testing something. Will fix!

**Comment by AlanOC91** [comment]
Done. Will be live on next data refresh.
