### ISSUE TITLE
Kashtira Arise-Heart text not up to date

### ISSUE THREAD

**Issue by GuillaumeRiffaud** [AlanOC91/YGOPRODeck#450]
The card effect of Kashtira Arise-Heart does not correspond to the official text printed and displayed in the official database.

_Currently returned text:_ 
3 Level 7 monsters
Once per turn, if "Kashtira Shangri-Ira" activated its effect(s) this turn, you can also Xyz Summon "Kashtira Arise-Heart" by using a "Kashtira" monster you control. (Transfer its materials to this card.) Any card sent to the GY is banished instead. Once per Chain, each time a card(s) is banished: Attach 1 banished card to this card as material. Once per turn (Quick Effect): You can detach 3 materials from this card, then target 1 card on the field; banish it face-down.

_Official text:_
3 Level 7 monsters
Once per turn, **you can also Xyz Summon "Kashtira Arise-Heart" by using 1 "Kashtira" monster you control, if an effect of "Kashtira Shangri-Ira" was successfully activated this turn.** (Transfer its materials to this card.) Any card sent to the GY is banished instead. Once per Chain, each time a card(s) is banished: Attach 1 banished card to this card as material. Once per turn (Quick Effect): You can detach 3 materials from this card, then target 1 card on the field; banish it face-down.

**Comment by AlanOC91** [comment]
Fixed! Along with a host of other card descriptions. Will be live in the next cache refresh.
