### ISSUE TITLE
Card Lists for packs won't show lower rarity duplicates

### ISSUE THREAD

**Issue by btvanhooser** [AlanOC91/YGOPRODeck#452]
As an example, on [Maze Of Memories](https://ygoprodeck.com/pack/Maze%20of%20Memories) that pack has a bunch of ultra rares available but it only shows 1 ultra rare on the card list. The other ultra rares are there but they only show up on the "Collector's Rare" section. On older sets like [The Lost Millennium](https://ygoprodeck.com/pack/The%20Lost%20Millennium), that set shows no Ultra rares, but all of the Ultimate Rares there can be Ultra too. It just makes it a bit confusing when navigating the packs because it gives the impression that some sets don't have ultra rare cards

**Comment by AlanOC91** [comment]
Thanks for the report! I pushed out an update that made numerous improvements to the card set page:

- Correctly groups cards now. So on Maze of Memories "Gate Guardian" appears under Rare and "Collector's Rare".
- Image optimization which reduces image size by roughly 80-90%.
- Links in to our TCGplayer Database to show much more accurate prices for the TCGplayer set over our internal system (which was missing a bunch of prices).

**Comment by btvanhooser** [comment]
Dang, solid turn around time on this. Thanks
