### ISSUE TITLE
Cards with konami_id missing but existing

### ISSUE THREAD

**Issue by magicDGS** [AlanOC91/YGOPRODeck#463]
The following cards have a konami ID on its database but they are not present when `misc=yes`:

* [15175429](https://db.ygoprodeck.com/api/v7/cardinfo.php?misc=yes&id=15175429) -> [8002](https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=8002&request_locale=en) 
* [89493368](https://db.ygoprodeck.com/api/v7/cardinfo.php?misc=yes&id=89493368) -> [7998](https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=7998&request_locale=en)
* [52286175](https://db.ygoprodeck.com/api/v7/cardinfo.php?misc=yes&id=52286175) -> [8000](https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=8000&request_locale=en)

How this information is usually fetched into the DB? I wonder cause I wanna use both id (password of the card) and konami_id as driving identifiers to update information, and I wonder if I can expect them to be up-to-date. Thank you!

**Comment by AlanOC91** [comment]
Thanks! Fixed! It will go live on the next cache refresh.
