### ISSUE TITLE
Duplicated konami-id on 2 cards

### ISSUE THREAD

**Issue by magicDGS** [AlanOC91/YGOPRODeck#464]
I found that there is a konami-id that is duplicated and assigned to 2 different cards: https://db.ygoprodeck.com/api/v7/cardinfo.php?konami_id=4828&misc=yes

The card 47695416 has assigned it wrongly, as the correct one is `4248` (see https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=4248&request_locale=ja).

**Comment by AlanOC91** [comment]
Fixed! It will go live on the next cache refresh!
