### ISSUE TITLE
Can no longer log in using discord

### ISSUE THREAD

**Issue by Jason158** [AlanOC91/YGOPRODeck#465]
When I try to log in using discord, I get a white page with an error message of "Error : Duplicate entry '693831609018875984' for key 'discord_id' ". It used to work fine; this started like 2 months ago. Not sure if this is an issue on your end or discord's.

**Comment by AlanOC91** [comment]
Hey! Did you email address change on your discord account? If you want to email admin@ygoprodeck.com we can discuss the situation in private.
