### ISSUE TITLE
some articles are working in a weird way

### ISSUE THREAD

**Issue by ommar654321** [AlanOC91/YGOPRODeck#466]
some articles dont appear in the articles page no matter what you search for example
the New VJUMP card: future fusion rework article
this is a news type article when i search for it in the news article search it doesn't show up even though i am searching for news type articles and they dont appear in the new news page and the only way to view thesr weird articles is through links on google/discord
i want you to fix this bug as it makes some articles invisible unless you specifically search for them on google

**Comment by AlanOC91** [comment]
This is fixed now. Thanks for the report!
