### ISSUE TITLE
Fonts Not Aligning to the Center

### ISSUE THREAD

**Issue by Esparanta** [AlanOC91/YGOPRODeck#467]
Title, literally. For more information, you can check the link:

https://ygoprodeck.com/forum/viewtopic.php?id=60309

In short, after I embedded a video, I can't align italiced words to the middle just below the video and I have no idea why. Any workarounds?

**Comment by AlanOC91** [comment]
This should be allowed now.

**Comment by Esparanta** [comment]
Yep, working as intended. Thanks a lot
