### ISSUE TITLE
deck: "..danger!? tri-combojama / ojamass in side (😠MAKE OJAMAS COMPETITIVE GRAAHHHH)" not showing up when i click on it. 

### ISSUE THREAD

**Issue by bigw2150** [AlanOC91/YGOPRODeck#468]
I think it is an issue with the link or some. Maybe I can't put emojis?

https://ygoprodeck.com/deck/336864
https://ygoprodeck.com/deck/danger-tri-combojama-invoked-ojamas-in-side-%D1%91%D1%8F%D1%88%D0%B0make-ojamas-competitive-graahhhh-336864/

pls help. i want people to find this beautiful new take on ojamas

**Comment by bigw2150** [comment]
also lmk if you can access either link

**Comment by bigw2150** [comment]
I removed the emoji and no change... idk anymore

**Comment by AlanOC91** [comment]
Fixed. I had to modify the url of the deck. New URL is:
https://ygoprodeck.com/deck/danger-tri-combojama-invoked-ojamas-in-side-ojamas-competitive-graahhhh-336864

This will be reflected on the site.
