### ISSUE TITLE
Terminal World set missing from the API

### ISSUE THREAD

**Issue by Snowskateer** [AlanOC91/YGOPRODeck#473]
This set, which has the new Infernoid, Genex, etc support is not present in the API, despite cards like the new Raidraptor support being present, which was revealed weeks after.

**Comment by AlanOC91** [comment]
Added. Will show when the cache clears.

**Comment by Snowskateer** [comment]
Any update on this? There doesn't appear to have been any new cards in general added to the API since

**Comment by Snowskateer** [comment]
Interestingly, they now show up when searched individually, but are not returned by https://db.ygoprodeck.com/api/v7/cardinfo.php with no parameters. The Quarter Century Box cards are not in the API at all either.
