### ISSUE TITLE
Random card endpoint caching is enabled

### ISSUE THREAD

**Issue by Doarakko** [AlanOC91/YGOPRODeck#474]
> Cache Control is disabled for this endpoint so it should always provide a fresh card.
https://ygoprodeck.com/api-guide/

The above is in the documentation, but with caching enabled.
I would like you to invalidate the cache.

PS
I always have fun with the bot that lets you draw Yu-Gi-Oh cards on Slack.
Thank you for providing great API.
https://github.com/Doarakko/draw-edge

**Comment by AlanOC91** [comment]
Hey! Thanks for the report! This should be fixed now. We've been making some adjustments to our page caches recently.

**Comment by Doarakko** [comment]
Thank you for quick fix!
