### ISSUE TITLE
"Illusion" card race property available in the actual card data but not accessible with the race URL parameter.

### ISSUE THREAD

**Issue by ddkasa** [AlanOC91/YGOPRODeck#477]
So for example [Chimera the Illusion Beast](https://db.ygoprodeck.com/api/v7/cardinfo.php?name=Chimera%20the%20Illusion%20Beast) will return a card with "Illusion" in the race property , but it's not working for this [endpoint](https://db.ygoprodeck.com/api/v7/cardinfo.php?race=illusion) with the race parameter.

The race(typing) image is also missing from the card [page](https://ygoprodeck.com/card/chimera-the-illusion-beast-13873) on the website:
![Screenshot from 2023-12-06 18-44-24](https://github.com/AlanOC91/YGOPRODeck/assets/23727748/032df377-201b-4d02-85b1-62eeadbfb015)

Its not mentioned on the API guide either, so I am guessing this is missed race as its still a relatively new release.

**Comment by AlanOC91** [comment]
Thanks for the report, this works now!
