### ISSUE TITLE
Collection Manager: filtering by set and rarity broken

### ISSUE THREAD

**Issue by martsawup** [AlanOC91/YGOPRODeck#487]
In the Collection Manager, when filtering by set and rarity, the results first show "No Cards Found" and then shows many cards which are not necessarily from the set. 

![Screen Shot 2024-04-18 at 9 02 56 PM](https://github.com/AlanOC91/YGOPRODeck/assets/102047359/b41aa09a-1990-4c12-9a33-576704498473)

You can still see the correct set and card code in the overlay, and the menu on the left with the set names still shows the accurate number of cards that I have from that set in my collection.

![Screen Shot 2024-04-18 at 9 05 12 PM](https://github.com/AlanOC91/YGOPRODeck/assets/102047359/a1f0c016-02f5-46a7-a748-7b66831de3ec)

For rarities, there is only the 'Common' option.

**Comment by AlanOC91** [comment]
Ha. Beat me to it. Only rolled out a fix for this about 30 seconds ago.
