### ISSUE TITLE
Should have pagination

### ISSUE THREAD

**Issue by Victor-Palha** [AlanOC91/YGOPRODeck#490]
Hello There.
I am using the YGOPro API to create a website, and I noticed from the documentation that there is no pagination when the API is called. It would be interesting to have an option to paginate searches, especially when using the endpoint `https://db.ygoprodeck.com/api/v7/cardinfo.php`.

**Comment by AlanOC91** [comment]
Hello,

Please read the API guide in full: https://ygoprodeck.com/api-guide/

**Comment by Frederisk** [comment]
There are two parameters to do this: `num` and `offset`. It is written in the corner of the document.
