### ISSUE TITLE
Language API Endpoint not working anymore

### ISSUE THREAD

**Issue by necrodraco** [AlanOC91/YGOPRODeck#500]
Between the 10th July to 11th July the language endpoint/Language Option got corrupted. 

When I start for example any of the examples from the api guide (https://ygoprodeck.com/api-guide/), they don't return the specified language anymore. It always return english language of card text and card names. 

e.g. using
https://db.ygoprodeck.com/api/v7/cardinfo.php?name=Survie%20du%20Plus%20Fort&language=fr

returns: 
`{"data":[{"id":58272005,"name":"Survival of the Fittest","type":"Trap Card","frameType":"trap","desc":"Target 1 Dinosaur-Type monster you control; equip this card to that target. It gains 1000 ATK. When that attacking monster destroys an opponent's monster by battle and sends it to the Graveyard: You can activate this effect; the equipped monster can make a second attack on an opponent's monster in a row.","race":"Normal","name_en":"Survival of the Fittest","ygoprodeck_url":"https://ygoprodeck.com/card/survival-of-the-fittest-4958","card_sets":[{"set_name":"2014 Mega-Tin Mega Pack","set_code":"MP14-EN178","set_rarity":"Common","set_rarity_code":"(C)","set_price":"0"},{"set_name":"Dinosmasher's Fury Structure Deck","set_code":"SR04-EN031","set_rarity":"Common","set_rarity_code":"(C)","set_price":"0"},{"set_name":"Shadow Specters","set_code":"SHSP-EN079","set_rarity":"Common","set_rarity_code":"(C)","set_price":"0"}],"card_images":[{"id":58272005,"image_url":"https://images.ygoprodeck.com/images/cards/58272005.jpg","image_url_small":"https://images.ygoprodeck.com/images/cards_small/58272005.jpg","image_url_cropped":"https://images.ygoprodeck.com/images/cards_cropped/58272005.jpg"}],"card_prices":[{"cardmarket_price":"0.07","tcgplayer_price":"0.10","ebay_price":"0.99","amazon_price":"0.99","coolstuffinc_price":"0.25"}]}]}`

instead of the expected language FR. Same Error happens in German for all cards and all the other examples.

**Comment by SilvanP** [comment]
@AlanOC91 imo this is a high prio issue, just wanted to ping you here in case you missed it out ;)

**Comment by SilvanP** [comment]
Seems to be working again!

**Comment by necrodraco** [comment]
Yeah. its working now again.
