### ISSUE TITLE
Api not returning all cards

### ISSUE THREAD

**Issue by BrandonCasasnovas** [AlanOC91/YGOPRODeck#56]
Hello Alan,

I am working on a personal side project using the YGOPRO api. I have been working on this for a few weeks now. Typically when I call the api I get a response of 9800+ cards. Today however when calling the api, I am getting 304 cards returned to me in the response. I am pretty sure I am not messing up the call as I have been using the same function for weeks. I thought I would share this with you. Thank you for everything you are doing with YGOPro.

-Brandon

**Comment by AlanOC91** [comment]
This was a server side caching issue on our end. I've cleared the cache and returned the API to it's usual state. It should be responding with every card now again.

**Comment by BrandonCasasnovas** [comment]
Thank you so much. Appreciate it.
