### ISSUE TITLE
% Increase for Card of the Week

### ISSUE THREAD

**Issue by AlanOC91** [AlanOC91/YGOPRODeck#60]
Since Card of the Week started, it's only ever been Ash Blossom & Joyous Spring (except maybe once) as it's the most viewed card in the database. 

To shake things up, an interesting idea is to maybe get the card with the largest % increase for the week which should be quite easy to do with my current data model.

**Comment by AlanOC91** [comment]
% increase is now implemented. Should be much more interesting and varied than the usual "Ash Blossom & Joyous Spring is Card of the Week".

The following image is a test example. The live example will be rounded to two decimal places. 

![increase](https://user-images.githubusercontent.com/37552458/53723054-c4bbca00-3e5e-11e9-908b-d8edd3539ccb.png)

**Comment by Cristichi** [comment]
Konami pls ban ass blossom :C
