### ISSUE TITLE
Add "rarity" and enhance global "set" information in API

### ISSUE THREAD

**Issue by NoahReyson** [AlanOC91/YGOPRODeck#72]
Rarities are available on the site but not through the API. I don't know where you stock these data but I think it wouldn't be too difficult to add them to the file returned by the API.

In a second time, the data structure for 'sets' information is a bit messy. We have two fields in the Json file: 'set_tag' and 'setcode'.
First, the relation between the two values is not clear (even if we can guess they're in the same order).
Second, these values are String typed while they clearly should be Array typed.

Here my proposition to solve these two issues (Buster Blader example):

`"sets":[
{"code": "Speed Duel: Arena of Lost Souls", "tag": "SBLS-EN001", "rarity": "Common"},
{"code":"Pharaoh's Servant", "tag":"PSV-050", "rarity": "Ultra rare"},
{"code":"Pharaoh's Servant", "tag":"PSV-E050", "rarity": "Ultra rare"}
etc.
]`

We can also imagine adding 'image' fields "image_url" and "image_url_small" as well as 'price' fields "cardmarket_price", etc. in each sub-element.

This could also be useful for suppressing duplicate returns for a query with the exact card name since all information differentiating two copies of a card will be in the "set" field.

Thanks for your feedback

**Comment by AlanOC91** [comment]
Excellent feedback.

I've decided to rework the way I capture the card set data based on this feedback and I'll provide the data in a way that the example above shows.

Because of the way I am re-working this. The data won't be available for a bit of time. It should be ready by the end of June in which case I will create a new API version (v5) that will house the new response data.

v5 will also make use of Arrays for images and card prices.

Thanks for the feedback.

**Comment by NoahReyson** [comment]
Thank you for your quick reply.
I didn't know if you accepted this kind of comment on your work.

To go a little further, I noticed some other perfectible details.
- The field 'archetype' could also be Array typed. This could be useful for some cards belonging to two very different archetypes:
Blue-eyes Toon Dragon: Blue-eyes and Toon
Dark Paladin: Dark Magician and Buster Blader
Or for cards that are part of an archetype and its sub-archetype
Cyber End Dragon: Cyber and Cyber Dragon
- The 'linkmarkers' field could also be Array typed.
- All data returned by the API are included in a double array. I haven't found examples where this is relevant. I think only one array is enough.

If I can help in any other way, contact me.

Thanks

**Comment by AlanOC91** [comment]
Thanks for the feedback! I always appreciate good constructive feedback such as this which helps me to improve things.

Here is an example my current beta v5 of the API that I worked on since receiving your feedback:

![beta](https://user-images.githubusercontent.com/37552458/58754070-283aaf80-84c1-11e9-9535-7368951366b0.png)

**Archetype** to array will have to wait. I only store 1 archetype value at the moment and don't store any sub-archetypes/supported archetypes. This will take some new data integration so it will be a while yet before it's ready but I do plan on doing it.

**Comment by AlanOC91** [comment]
Multiple of the same card (with different IDs for alternative artwork) such as Dark Magician will no longer return multiple results and will instead be concatenated into the one result with card images being arrayed.

![card_images](https://user-images.githubusercontent.com/37552458/58754280-80bf7c00-84c4-11e9-8f45-13647e07fa1c.png)

**Comment by AlanOC91** [comment]
Here is current v5 example for Dark Magician:

[{
    "id": "46986414",
    "name": "Dark Magician",
    "type": "Normal Monster",
    "desc": "The ultimate wizard in terms of attack and defense.",
    "atk": "2500",
    "def": "2100",
    "level": "7",
    "race": "Spellcaster",
    "attribute": "DARK",
    "archetype": "Dark Magician",
    "card_sets": [{
            "set_name": "2016 Mega-Tins",
            "set_code": "CT13-EN003",
            "set_rarity": "Ultra Rare"
        },
        {
            "set_name": "2017 Mega-Tins",
            "set_code": "CT14-EN001",
            "set_rarity": "Secret Rare"
        },
        {
            "set_name": "Booster Pack Collectors Tins 2002",
            "set_code": "BPT-001",
            "set_rarity": "Secret Rare"
        },
        {
            "set_name": "Collectible Tins 2003",
            "set_code": "BPT-007",
            "set_rarity": "Secret Rare"
        },
        {
            "set_name": "Dark Beginning 1",
            "set_code": "DB1-EN102",
            "set_rarity": "Ultra Rare"
        },
        {
            "set_name": "Dark Legends",
            "set_code": "DLG1-EN004",
            "set_rarity": "Rare"
        },
        {
            "set_name": "Duel Power",
            "set_code": "DUPO-EN101",
            "set_rarity": "Ultra Rare"
        },
        {
            "set_name": "Duel Terminal - Preview Wave 1",
            "set_code": "DTP1-EN002",
            "set_rarity": "Duel Terminal Normal Parallel "
        },
        {
            "set_name": "Duel Terminal 1",
            "set_code": "DT01-EN002",
            "set_rarity": "Duel Terminal Rare Parallel Ra"
        },
        {
            "set_name": "Duelist League 2 participation cards",
            "set_code": "DL11-EN001",
            "set_rarity": "Rare"
        },
        {
            "set_name": "Duelist Pack: Battle City",
            "set_code": "DPBC-EN008",
            "set_rarity": "Super Rare"
        },
        {
            "set_name": "Duelist Pack: Yugi",
            "set_code": "DPYG-EN001",
            "set_rarity": "Rare"
        },
        {
            "set_name": "Duelist Saga",
            "set_code": "DUSA-EN100",
            "set_rarity": "Ultra Rare"
        },
        {
            "set_name": "Forbidden Legacy",
            "set_code": "FL1-EN002",
            "set_rarity": "Secret Rare"
        },
        {
            "set_name": "Legend of Blue Eyes White Dragon",
            "set_code": "LOB-005",
            "set_rarity": "Ultra Rare"
        },
        {
            "set_name": "Legend of Blue Eyes White Dragon",
            "set_code": "LOB-E003",
            "set_rarity": "Ultra Rare"
        },
        {
            "set_name": "Legend of Blue Eyes White Dragon",
            "set_code": "LOB-EN005",
            "set_rarity": "Ultra Rare"
        },
        {
            "set_name": "Legendary Collection",
            "set_code": "LC01-EN005",
            "set_rarity": "Ultra Rare"
        },
        {
            "set_name": "Legendary Decks II",
            "set_code": "LDK2-ENY10",
            "set_rarity": "Common"
        },
        {
            "set_name": "Legendary Dragon Decks",
            "set_code": "LEDD-ENA01",
            "set_rarity": "Common"
        },
        {
            "set_name": "Retro Pack",
            "set_code": "RP01-EN003",
            "set_rarity": "Ultra Rare"
        },
        {
            "set_name": "Shonen Jump Vol. 9, Issue 4 promotional card",
            "set_code": "JUMP-EN049",
            "set_rarity": "Ultra Rare"
        },
        {
            "set_name": "Speed Duel Starter Decks: Destiny Masters",
            "set_code": "SS01-ENA01",
            "set_rarity": "Common"
        },
        {
            "set_name": "Speed Duel Tournament Pack 1",
            "set_code": "STP1-EN001",
            "set_rarity": "Ultra Rare"
        },
        {
            "set_name": "Starter Deck: Yugi",
            "set_code": "SDY-006",
            "set_rarity": "Ultra Rare"
        },
        {
            "set_name": "Starter Deck: Yugi",
            "set_code": "SDY-E005",
            "set_rarity": "Ultra Rare"
        },
        {
            "set_name": "Starter Deck: Yugi Evolution",
            "set_code": "SYE-001",
            "set_rarity": "Super Rare"
        },
        {
            "set_name": "Starter Deck: Yugi Reloaded",
            "set_code": "YSYR-EN001",
            "set_rarity": "Common"
        },
        {
            "set_name": "Structure Deck: Yugi Muto",
            "set_code": "SDMY-EN010",
            "set_rarity": "Common"
        },
        {
            "set_name": "WSJ Jump Pack Fall 2016 promotional card",
            "set_code": "JMPS-EN003",
            "set_rarity": "Ultra Rare"
        },
        {
            "set_name": "Yu-Gi-Oh! Dark Duel Stories promotional cards",
            "set_code": "DDS-002",
            "set_rarity": "Prismatic Secret Rare"
        },
        {
            "set_name": "Yu-Gi-Oh! Power of Chaos: Yugi the Destiny promotional cards",
            "set_code": "PCY-004",
            "set_rarity": "Prismatic Secret Rare"
        },
        {
            "set_name": "Yu-Gi-Oh! Power of Chaos: Yugi the Destiny promotional cards",
            "set_code": "PCY-E004",
            "set_rarity": "Prismatic Secret Rare"
        },
        {
            "set_name": "Yu-Gi-Oh! The Dark Side of Dimensions Movie Pack",
            "set_code": "MVP1-EN054",
            "set_rarity": "Ultra Rare"
        },
        {
            "set_name": "Yu-Gi-Oh! The Dark Side of Dimensions Movie Pack Special Edition",
            "set_code": "MVP1-ENSE3",
            "set_rarity": "Ultra Rare"
        },
        {
            "set_name": "Yu-Gi-Oh! The Dark Side of Dimensions Movie Pack: Gold Edition",
            "set_code": "MVP1-ENG54",
            "set_rarity": "Gold Rare"
        },
        {
            "set_name": "Yu-Gi-Oh! The Dark Side of Dimensions Movie Pack: Gold Edition",
            "set_code": "MVP1-ENGV3",
            "set_rarity": "Gold Secret Rare"
        },
        {
            "set_name": "Yugi & Kaiba Collector Box",
            "set_code": "YUCB-EN001",
            "set_rarity": "Ultra Rare"
        }
    ],
    "card_images": [{
            "id": "46986414",
            "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/46986414.jpg",
            "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/46986414.jpg"
        },
        {
            "id": "46986415",
            "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/46986415.jpg",
            "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/46986415.jpg"
        },
        {
            "id": "46986416",
            "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/46986416.jpg",
            "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/46986416.jpg"
        },
        {
            "id": "46986417",
            "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/46986417.jpg",
            "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/46986417.jpg"
        },
        {
            "id": "46986418",
            "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/46986418.jpg",
            "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/46986418.jpg"
        },
        {
            "id": "46986419",
            "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/46986419.jpg",
            "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/46986419.jpg"
        },
        {
            "id": "36996508",
            "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/36996508.jpg",
            "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/36996508.jpg"
        },
        {
            "id": "46986420",
            "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/46986420.jpg",
            "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/46986420.jpg"
        },
        {
            "id": "46986421",
            "image_url": "https://storage.googleapis.com/ygoprodeck.com/pics/46986421.jpg",
            "image_url_small": "https://storage.googleapis.com/ygoprodeck.com/pics_small/46986421.jpg"
        }
    ],
    "card_prices": {
        "cardmarket_price": "0.19",
        "tcgplayer_price": "0.16",
        "ebay_price": "0.99",
        "amazon_price": "0.81"
    }
}]

**Comment by AlanOC91** [comment]
Current v5 example with Decode Talker:

![decode talker](https://user-images.githubusercontent.com/37552458/58764065-be6ee400-855a-11e9-903b-6cfd5d6803df.png)

**Comment by NoahReyson** [comment]
That looks really good to me.
Just be careful, some cards appear twice in the same set with the same code (example EH Chaos Neos in GLAS). The only difference is the rarity.

**Comment by AlanOC91** [comment]
Price for each set now added:

![price](https://user-images.githubusercontent.com/37552458/58915101-26b6f480-8718-11e9-9538-ca8ec7d63a88.png)

**Comment by AlanOC91** [comment]
Initial API v5 has been released: https://db.ygoprodeck.com/api-guide/

More features to come in the future.
