### ISSUE TITLE
Please consider add spaces and "format" to the description of the cards

### ISSUE THREAD

**Issue by DevGlogicM** [AlanOC91/YGOPRODeck#8]
After check the tweet you made about "Astrograph Sorcerer" and its description, I suggest you consider add line breaks and format to other cards.

An card example can be [Knightmare Cerberus](https://db.ygoprodeck.com/card/?search=Knightmare%20Cerberus).

If you check the card image "in the description" you'll see the text is organized.

Checking the "Network" tab in Google Chrome, the **_desc_** attribute of the JSON response has "\r\n", but in the render of the response, it doesn't have the desired effect.

Just in case, this is the [URL](https://db.ygoprodeck.com/getcardbyid.php?cardid=75452921&callback=jQuery112405488581512889485_1532697973223&_=1532697973225) of the petition for get the details of Knightmare Cerberus.

Maybe this happens only with some cards, I remembered saw this bug with [Gravekeeper's Esper](https://db.ygoprodeck.com/card/?search=Gravekeeper%27s%20Esper), but now its shows correctly.

**Comment by AlanOC91** [comment]
Are you sure your browser cache is up to date? You might have viewed the card previously before the change and your web browser still has it cached (Ctrl + F5) on the page for it should force update it. 

Here is how it looks for me: ![Knightmare Cerberus Formatting Picture](https://i.imgur.com/pm6qo7X.png)

**Comment by AlanOC91** [comment]
I definitely do have to do a run-down on some cards though and update them, there are some consistency issues at the moment.
