### ISSUE TITLE
API v5 parameter name returns wrong card

### ISSUE THREAD

**Issue by AignerGames** [AlanOC91/YGOPRODeck#80]
I think the implemention of the name and fname parameter is mixed up or the documentation is wrong: 

The following endpoint parameters can be passed:

    name - The exact name of the card. You can also pass a card ID to this.
    fname - A fuzzy search using a string. For example &fname=Magician to search by all cards with "Magician" in the name.

But the API with name returns a different card for example: https://db.ygoprodeck.com/api/v5/cardinfo.php?name=Dark%20Magician returns Amulet Dragon (which contains the text Dark Magican). 

The call with https://db.ygoprodeck.com/api/v5/cardinfo.php?fname=Dark%20Magician returns the correct Dark Magician card.

**Comment by AlanOC91** [comment]
Can you try this again for me.

There seems to have been a weird server side cache issue. I'll have to investigate this deeper but for now clearing the server cache has fixed the issue.

**Comment by AignerGames** [comment]
I also deleted my local data (cookies etc) for the website and it seems to work, the name=Dark%20Magician returns the correct Dark Magican card.

**Comment by AlanOC91** [comment]
Perfect, I will consider this closed for now.
