### ISSUE TITLE
Some archtypes are mising

### ISSUE THREAD

**Issue by DevGlogicM** [AlanOC91/YGOPRODeck#9]
Some architypes are not present yet in YGOPRODeck website.

For example, if you search the card called [Guardian Kay'Est](https://db.ygoprodeck.com/card/?search=Guardian%20Kay%27est) or the card called [Arsenal Summoner](https://db.ygoprodeck.com/card/?search=Arsenal%20Summoner), it doesn't show that these example cards belongs to ["Guardian" archtype](http://yugioh.wikia.com/wiki/Guardian).

My suggestion _(only if is possible/convenient)_ is add an entry on GitHub with the missing architypes and this entry will be updating each time an archtype is added.

**Comment by AlanOC91** [comment]
That's a great idea! I'll open a master archetype list issue of missing archetypes that users can comment on for missing ones. 

I had no idea "Guardian" was even an archetype!

**Comment by AlanOC91** [comment]
#10
