### ISSUE TITLE
Specify search by card name, card lore/description or both

### ISSUE THREAD

**Issue by DevGlogicM** [AlanOC91/YGOPRODeck#96]
While I was searching cards with "chain" on its name, I figured out that "thanks to Fuzzy Search", this can be done, but I have a few suggestions:

- In the "Advanced" page - "gear icon" it should have an option where you can selected whether the text search results is applied _(*by card name, *by card description/lore, * both)_.

- The input text's placeholder (i.e: _Search by Card Name/Desccription_) is not re-draw after the text is deleted on it -  you can try by enter to ["Advanced" page](https://db.ygoprodeck.com/search/), type "chain" on the input text, press ENTER, then delete the "chain" input = no placeholder is shown as it was at the beginning - [see image](https://imgur.com/EZXkGzD).

- Back to the "search by card name, lore", I was using "Semantic Search" on Yugioh! Wikia - for comparassion - and _after some googling_, I could get these results: [Cards with "Chain" on its *english card name*](https://yugioh.fandom.com/index.php?title=Special%3AAsk&q=%5B%5BMedium%3A%3ATCG%5D%5D+%5B%5BEnglish+name%3A%3A%7E*Chain*%5D%5D+%5B%5BCard+type%3A%3AMonster+Card%7C%7CSpell+Card%7C%7CTrap+Card%5D%5D&po=%3FEnglish+name%0D%0A%3FCard+type%0D%0A%3FType%0D%0A%3FATK+string%3D%5B%5BATK%5D%5D%0D%0A%3FDEF+string%3D%5B%5BDEF%5D%5D%0D%0A&eq=yes&p%5Bformat%5D=broadtable&sort_num=&order_num=ASC&p%5Blimit%5D=500&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=&p%5Border%5D%5Bascending%5D=1&p%5Bheaders%5D=show&p%5Bmainlabel%5D=English+name+with+link&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=+...+further+results+%28143+more%29&p%5Bdefault%5D=&p%5Bclass%5D=sortable+wikitable+smwtable&p%5Bsep%5D=%2C&eq=yes). With this in mind "and since, Semantic Search it kind of difficult to learn and try", this feature of set the search cards by card name, description/lore or both _might_ lead get more specific results.

Side note: I ask for this feature, because your page is the only one I know is searching case-insensitive; [Semantic Search has this feature](https://www.semantic-mediawiki.org/wiki/Help:Search_operators#Case_insensitivity), but I couldn't understand its settings.

- In the ["Settings" page](https://db.ygoprodeck.com/settings/), what is "Filter Compact Mode:"? - I think it would be usefult that these options has an "?" button for help and / or a short and clear description about its meaning and use _(as *Default Card Image* has)_.

Side note #2: after trying some query strings manipulation, I could get these results: [Cards with "dark" text on it](https://db.ygoprodeck.com/search/?card=darkness&sortby=A-Z&perpage=100%20Per%20Page); in this case, I'm more interested in filter cards who has "darkness" text on its _card name_.

> I know these are unique websites, but, if some of the existing features that not all users might know in the Wikia can be available and easy to understand and use, that would be good for your users.

**Comment by AlanOC91** [comment]
Thanks for the detailed feedback! I've pushed out a few updates to the site now:

1. Settings page has been updates to add a description for the compact filters option.
2. A fix has been applied where the placeholder stopped showing when the input text has been manually removed.
3. You can now force a search by name only on the input text box for the advanced search page. If you type * before the string, it will force a name only check. Example: *time wizard
https://db.ygoprodeck.com/search/?card=*time%20wizard
4. Updated the Syntax page to explain point number 3. Will look into showing this on the actual advanced search page, just need to find the right place to put put.

**Please note, you may need to update your web browser cache to view these changes now.** 

TODO: Allow to search by description/lore only.

**Comment by DevGlogicM** [comment]
Excellent!
Now I can keep searching cards! :)

By the way, I share the results I have so far:

- [Cards with "darkness" on its english card name](https://db.ygoprodeck.com/search/?card=*darkness&sortby=A-Z&perpage=100%20Per%20Page) - with "darkness", though, I had to reload the page - was receiving "in the Console tab of F12 developer tools" a 500 error.
- [Cards with "skull" on its english card name](https://db.ygoprodeck.com/search/?card=*skull&sortby=A-Z&perpage=100%20Per%20Page).

Thanks for your response and I hope find more to add and make your website even more fitting to our needs :)

**Comment by AlanOC91** [comment]
Thanks for the feedback!

Can you try again for darkness and skull and check if it works?

In terms of console logs, they have little to no impact on performance. I definitely made sure to check that out :P

Quantity of results is shown (although not yet visible on mobile):

![quantity](https://user-images.githubusercontent.com/37552458/64560491-82f56a00-d340-11e9-9914-e1f48768cf86.png)

Filter Applied is currently on the bottom/small/out of the way on purpose as a design decision. I added to so people know what filters are applied if they are linked to it by someone else.

**Comment by DevGlogicM** [comment]
Looks good, thanks.
Please check the changes in dark theme mode, the quantity of cards should also be in white color "as the filters appled has".
